/*
 * Generated by JasperReports - 12/6/17 5:51 PM
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import com.infy.finacle.finrpt.utils.*;
import net.sf.jasperreports.engine.*;
import com.infy.finacle.finrpt.ireport.*;
import java.util.*;
import com.infy.finacle.finrpt.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
class OpenForeignCurrencyAccount_1512559295266_158341 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_REPORT_TIME_ZONE = null;
    private JRFillParameter parameter_FIN_REPORT_TYPE = null;
    private JRFillParameter parameter_REPORT_FILE_RESOLVER = null;
    private JRFillParameter parameter_FIN_OUT_REC = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_FIN_REPORT_DESC = null;
    private JRFillParameter parameter_FIN_SER_FINQUERY = null;
    private JRFillParameter parameter_FINRPT_DEFAULT_FORMAT = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_REPORT_URL_HANDLER_FACTORY = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillParameter parameter_REPORT_TEMPLATES = null;
    private JRFillParameter parameter_FIN_DB_CONN = null;
    private JRFillParameter parameter_FIN_REPOS_FILE = null;
    private JRFillParameter parameter_FIN_OUT_RETCODE = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_FIN_REPORT_TO = null;
    private JRFillParameter parameter_FIN_BANKREPOS_PARAM = null;
    private JRFillParameter parameter_FIN_IMG_PATH = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_FIN_REPOS_LIST = null;
    private JRFillParameter parameter_TodayDate = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_FIN_SESSION_ID = null;
    private JRFillParameter parameter_FIN_TEMPLATE_PATH = null;
    private JRFillParameter parameter_FIN_APP_UTIL = null;
    private JRFillParameter parameter_REPORT_FORMAT_FACTORY = null;
    private JRFillParameter parameter_FIN_JASPER_PATH = null;
    private JRFillParameter parameter_FIN_INP_STR = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillField field_CountUSD = null;
    private JRFillField field_CountJPY = null;
    private JRFillField field_JPY = null;
    private JRFillField field_SGD = null;
    private JRFillField field_BankAddress = null;
    private JRFillField field_Project_Bank_Name = null;
    private JRFillField field_BankFax = null;
    private JRFillField field_CountTHB = null;
    private JRFillField field_Image_Name = null;
    private JRFillField field_MYR = null;
    private JRFillField field_GLSH = null;
    private JRFillField field_BranchName = null;
    private JRFillField field_EUR = null;
    private JRFillField field_CountSGD = null;
    private JRFillField field_CountEUR = null;
    private JRFillField field_INR = null;
    private JRFillField field_USD = null;
    private JRFillField field_THB = null;
    private JRFillField field_CountINR = null;
    private JRFillField field_CountMYR = null;
    private JRFillField field_BankPhone = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_FIN_REPOSITORY = null;
    private JRFillVariable variable_TODAY = null;
    private JRFillVariable variable_FIN_DB_CONN = null;
    private JRFillVariable variable_CountUSDTotal = null;
    private JRFillVariable variable_USDTotal = null;
    private JRFillVariable variable_CountEURTotal = null;
    private JRFillVariable variable_EURTotal = null;
    private JRFillVariable variable_CountTHBTotal = null;
    private JRFillVariable variable_THBTotal = null;
    private JRFillVariable variable_CountJPYTotal = null;
    private JRFillVariable variable_JPYTotal = null;
    private JRFillVariable variable_CountINRTotal = null;
    private JRFillVariable variable_INRTotal = null;
    private JRFillVariable variable_CountMYRTotal = null;
    private JRFillVariable variable_MYRTotal = null;
    private JRFillVariable variable_CountSGDTotal = null;
    private JRFillVariable variable_SGDTotal = null;


    /**
     *
     */
    void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    void initParams(Map pm)
    {
        parameter_REPORT_TIME_ZONE = (JRFillParameter)pm.get("REPORT_TIME_ZONE");
        parameter_FIN_REPORT_TYPE = (JRFillParameter)pm.get("FIN_REPORT_TYPE");
        parameter_REPORT_FILE_RESOLVER = (JRFillParameter)pm.get("REPORT_FILE_RESOLVER");
        parameter_FIN_OUT_REC = (JRFillParameter)pm.get("FIN_OUT_REC");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_FIN_REPORT_DESC = (JRFillParameter)pm.get("FIN_REPORT_DESC");
        parameter_FIN_SER_FINQUERY = (JRFillParameter)pm.get("FIN_SER_FINQUERY");
        parameter_FINRPT_DEFAULT_FORMAT = (JRFillParameter)pm.get("FINRPT_DEFAULT_FORMAT");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_REPORT_URL_HANDLER_FACTORY = (JRFillParameter)pm.get("REPORT_URL_HANDLER_FACTORY");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
        parameter_REPORT_TEMPLATES = (JRFillParameter)pm.get("REPORT_TEMPLATES");
        parameter_FIN_DB_CONN = (JRFillParameter)pm.get("FIN_DB_CONN");
        parameter_FIN_REPOS_FILE = (JRFillParameter)pm.get("FIN_REPOS_FILE");
        parameter_FIN_OUT_RETCODE = (JRFillParameter)pm.get("FIN_OUT_RETCODE");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_FIN_REPORT_TO = (JRFillParameter)pm.get("FIN_REPORT_TO");
        parameter_FIN_BANKREPOS_PARAM = (JRFillParameter)pm.get("FIN_BANKREPOS_PARAM");
        parameter_FIN_IMG_PATH = (JRFillParameter)pm.get("FIN_IMG_PATH");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_FIN_REPOS_LIST = (JRFillParameter)pm.get("FIN_REPOS_LIST");
        parameter_TodayDate = (JRFillParameter)pm.get("TodayDate");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_FIN_SESSION_ID = (JRFillParameter)pm.get("FIN_SESSION_ID");
        parameter_FIN_TEMPLATE_PATH = (JRFillParameter)pm.get("FIN_TEMPLATE_PATH");
        parameter_FIN_APP_UTIL = (JRFillParameter)pm.get("FIN_APP_UTIL");
        parameter_REPORT_FORMAT_FACTORY = (JRFillParameter)pm.get("REPORT_FORMAT_FACTORY");
        parameter_FIN_JASPER_PATH = (JRFillParameter)pm.get("FIN_JASPER_PATH");
        parameter_FIN_INP_STR = (JRFillParameter)pm.get("FIN_INP_STR");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
    }


    /**
     *
     */
    void initFields(Map fm)
    {
        field_CountUSD = (JRFillField)fm.get("CountUSD");
        field_CountJPY = (JRFillField)fm.get("CountJPY");
        field_JPY = (JRFillField)fm.get("JPY");
        field_SGD = (JRFillField)fm.get("SGD");
        field_BankAddress = (JRFillField)fm.get("BankAddress");
        field_Project_Bank_Name = (JRFillField)fm.get("Project_Bank_Name");
        field_BankFax = (JRFillField)fm.get("BankFax");
        field_CountTHB = (JRFillField)fm.get("CountTHB");
        field_Image_Name = (JRFillField)fm.get("Image_Name");
        field_MYR = (JRFillField)fm.get("MYR");
        field_GLSH = (JRFillField)fm.get("GLSH");
        field_BranchName = (JRFillField)fm.get("BranchName");
        field_EUR = (JRFillField)fm.get("EUR");
        field_CountSGD = (JRFillField)fm.get("CountSGD");
        field_CountEUR = (JRFillField)fm.get("CountEUR");
        field_INR = (JRFillField)fm.get("INR");
        field_USD = (JRFillField)fm.get("USD");
        field_THB = (JRFillField)fm.get("THB");
        field_CountINR = (JRFillField)fm.get("CountINR");
        field_CountMYR = (JRFillField)fm.get("CountMYR");
        field_BankPhone = (JRFillField)fm.get("BankPhone");
    }


    /**
     *
     */
    void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
        variable_FIN_REPOSITORY = (JRFillVariable)vm.get("FIN_REPOSITORY");
        variable_TODAY = (JRFillVariable)vm.get("TODAY");
        variable_FIN_DB_CONN = (JRFillVariable)vm.get("FIN_DB_CONN");
        variable_CountUSDTotal = (JRFillVariable)vm.get("CountUSDTotal");
        variable_USDTotal = (JRFillVariable)vm.get("USDTotal");
        variable_CountEURTotal = (JRFillVariable)vm.get("CountEURTotal");
        variable_EURTotal = (JRFillVariable)vm.get("EURTotal");
        variable_CountTHBTotal = (JRFillVariable)vm.get("CountTHBTotal");
        variable_THBTotal = (JRFillVariable)vm.get("THBTotal");
        variable_CountJPYTotal = (JRFillVariable)vm.get("CountJPYTotal");
        variable_JPYTotal = (JRFillVariable)vm.get("JPYTotal");
        variable_CountINRTotal = (JRFillVariable)vm.get("CountINRTotal");
        variable_INRTotal = (JRFillVariable)vm.get("INRTotal");
        variable_CountMYRTotal = (JRFillVariable)vm.get("CountMYRTotal");
        variable_MYRTotal = (JRFillVariable)vm.get("MYRTotal");
        variable_CountSGDTotal = (JRFillVariable)vm.get("CountSGDTotal");
        variable_SGDTotal = (JRFillVariable)vm.get("SGDTotal");
    }


    /**
     *
     */
    Object evaluate(int id)
    {
        Object value = null;

        if (id >= 100)
        {
            value = evaluate1(id);
        }
        else if (id == 0)
        {
            value = (java.lang.String)("");
        }
        else if (id == 1)
        {
            value = (java.sql.Connection)(null);
        }
        else if (id == 2)
        {
            value = (java.lang.String)("../images");
        }
        else if (id == 3)
        {
            value = (java.lang.String)("../jrxml");
        }
        else if (id == 4)
        {
            value = (java.lang.String)("");
        }
        else if (id == 5)
        {
            value = (java.lang.String)("CUSTOM|FIN_FOREIGN_CURR_FCYBANK.FIN_FOREIGN_CURR_FCYBANK%3%CUSTOM::|where%TodayDate%=%((java.lang.String)parameter_TodayDate.getValue())%Parameter%Date::|INP_STR%1%java.lang.String%VARCHAR2::OUT_RETCODE%4%java.math.BigDecimal%NUMBER::OUT_REC%4%java.lang.String%VARCHAR2::|TodayDate%java.sql.Timestamp%10%!NULL!%Today Date@DBQUERY%NONE%java.sql.Timestamp!@!DEFAULT!@!8!@!10%CONSTANT%N%N::|{call CUSTOM.FIN_FOREIGN_CURR_FCYBANK.FIN_FOREIGN_CURR_FCYBANK( ((java.lang.String)parameter_FIN_INP_STR.getValue())  , ((java.math.BigDecimal)parameter_FIN_OUT_RETCODE.getValue()) , ((java.lang.String)parameter_FIN_OUT_REC.getValue()) ) } |{call CUSTOM.FIN_FOREIGN_CURR_FCYBANK.FIN_FOREIGN_CURR_FCYBANK( ((java.lang.String)parameter_FIN_INP_STR.getValue())  , ((java.math.BigDecimal)parameter_FIN_OUT_RETCODE.getValue()) , ((java.lang.String)parameter_FIN_OUT_REC.getValue()) ) } |false");
        }
        else if (id == 6)
        {
            value = (java.lang.String)(((java.lang.String)parameter_TodayDate.getValue()));
        }
        else if (id == 7)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 8)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 9)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 10)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 11)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 12)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 13)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 14)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 15)
        {
            value = (java.util.Date)(DateUtil.today());
        }
        else if (id == 16)
        {
            value = (java.util.Date)(DateUtil.today());
        }
        else if (id == 17)
        {
            value = (java.sql.Connection)(null);
        }
        else if (id == 18)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountUSD.getValue()));
        }
        else if (id == 19)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_USD.getValue()));
        }
        else if (id == 20)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountEUR.getValue()));
        }
        else if (id == 21)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_EUR.getValue()));
        }
        else if (id == 22)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountTHB.getValue()));
        }
        else if (id == 23)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_THB.getValue()));
        }
        else if (id == 24)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountJPY.getValue()));
        }
        else if (id == 25)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_JPY.getValue()));
        }
        else if (id == 26)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountINR.getValue()));
        }
        else if (id == 27)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_INR.getValue()));
        }
        else if (id == 28)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountMYR.getValue()));
        }
        else if (id == 29)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_MYR.getValue()));
        }
        else if (id == 30)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountSGD.getValue()));
        }
        else if (id == 31)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_SGD.getValue()));
        }
        else if (id == 32)
        {
            value = (java.lang.String)(FinUtil.getImage(((java.lang.String)field_Image_Name.getValue()), ((java.lang.String)parameter_FIN_IMG_PATH.getValue())));
        }
        else if (id == 33)
        {
            value = (java.lang.String)(((java.lang.String)field_Project_Bank_Name.getValue())+ "(" +((java.lang.String)field_BranchName.getValue()) +")");
        }
        else if (id == 34)
        {
            value = (java.lang.String)("Condition Of Opening Foreign Currency Account With Private Bank at "+((java.lang.String)parameter_TodayDate.getValue()));
        }
        else if (id == 35)
        {
            value = (java.lang.String)(((java.lang.String)field_BranchName.getValue()));
        }
        else if (id == 36)
        {
            value = (java.util.Date)(((java.util.Date)variable_TODAY.getValue()));
        }
        else if (id == 37)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getValue()));
        }
        else if (id == 38)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountUSD.getValue()));
        }
        else if (id == 39)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)field_USD.getValue())));
        }
        else if (id == 40)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountEUR.getValue()));
        }
        else if (id == 41)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)field_EUR.getValue())));
        }
        else if (id == 42)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountTHB.getValue()));
        }
        else if (id == 43)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)field_THB.getValue())));
        }
        else if (id == 44)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountJPY.getValue()));
        }
        else if (id == 45)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)field_JPY.getValue())));
        }
        else if (id == 46)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountINR.getValue()));
        }
        else if (id == 47)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)field_INR.getValue())));
        }
        else if (id == 48)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountMYR.getValue()));
        }
        else if (id == 49)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)field_MYR.getValue())));
        }
        else if (id == 50)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountSGD.getValue()));
        }
        else if (id == 51)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)field_SGD.getValue())));
        }
        else if (id == 52)
        {
            value = (java.lang.String)(((java.lang.String)field_Project_Bank_Name.getValue()));
        }
        else if (id == 53)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getValue())+1);
        }
        else if (id == 54)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 55)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 56)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 57)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 58)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 59)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 60)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 61)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 62)
        {
            value = (java.lang.String)("Co-operative Bank");
        }
        else if (id == 63)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 64)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 65)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 66)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 67)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 68)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 69)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getValue())+2);
        }
        else if (id == 70)
        {
            value = (java.lang.String)("Myawaddy Bank");
        }
        else if (id == 71)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 72)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 73)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 74)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 75)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 76)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 77)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 78)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 79)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 80)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 81)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 82)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 83)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 84)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 85)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getValue())+3);
        }
        else if (id == 86)
        {
            value = (java.lang.String)("Myanmar Oriental Bank");
        }
        else if (id == 87)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 88)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 89)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 90)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 91)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 92)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 93)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 94)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 95)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 96)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 97)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 98)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 99)
        {
            value = (java.lang.String)('-');
        }

        return value;
    }


    /**
     *
     */
    Object evaluate1(int id)
    {
        Object value = null;

        if (id >= 200)
        {
            value = evaluate2(id);
        }
        else if (id == 100)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 101)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getValue())+4);
        }
        else if (id == 102)
        {
            value = (java.lang.String)("Tun Foundation Bank");
        }
        else if (id == 103)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 104)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 105)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 106)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 107)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 108)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 109)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 110)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 111)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 112)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 113)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 114)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 115)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 116)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 117)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 118)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 119)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 120)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 121)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 122)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 123)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 124)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 125)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 126)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 127)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 128)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 129)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 130)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 131)
        {
            value = (java.lang.String)("Myanmar Industrial Development Bank");
        }
        else if (id == 132)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getValue())+5);
        }
        else if (id == 133)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getValue())+6);
        }
        else if (id == 134)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 135)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 136)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 137)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 138)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 139)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 140)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 141)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 142)
        {
            value = (java.lang.String)("Innwa Bank");
        }
        else if (id == 143)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getValue())+7);
        }
        else if (id == 144)
        {
            value = (java.lang.String)("Ayeyarwady Bank");
        }
        else if (id == 145)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 146)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 147)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 148)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 149)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 150)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 151)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 152)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 153)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getValue())+8);
        }
        else if (id == 154)
        {
            value = (java.lang.String)("United Amara Bank");
        }
        else if (id == 155)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 156)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 157)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 158)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 159)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 160)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 161)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 162)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 163)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getValue())+9);
        }
        else if (id == 164)
        {
            value = (java.lang.String)("Myanmar Apex Bank");
        }
        else if (id == 165)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 166)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 167)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 168)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 169)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 170)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 171)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 172)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 173)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 174)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 175)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 176)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 177)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 178)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 179)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 180)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 181)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 182)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 183)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 184)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 185)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 186)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 187)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 188)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 189)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 190)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 191)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 192)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 193)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 194)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 195)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 196)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 197)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getValue())+10);
        }
        else if (id == 198)
        {
            value = (java.lang.String)("Kanbawza Bank");
        }
        else if (id == 199)
        {
            value = (java.lang.String)('-');
        }

        return value;
    }


    /**
     *
     */
    Object evaluate2(int id)
    {
        Object value = null;

        if (id == 200)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 201)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 202)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 203)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 204)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 205)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 206)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 207)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 208)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 209)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 210)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 211)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 212)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 213)
        {
            value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
        }
        else if (id == 214)
        {
            value = (java.lang.String)("Total ( " + ((java.lang.Integer)variable_REPORT_COUNT.getValue())+ " ) Records Listed.");
        }
        else if (id == 215)
        {
            value = (java.lang.String)("Grand Total");
        }
        else if (id == 216)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_USDTotal.getValue())));
        }
        else if (id == 217)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_CountUSDTotal.getValue()));
        }
        else if (id == 218)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_CountEURTotal.getValue()));
        }
        else if (id == 219)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_EURTotal.getValue())));
        }
        else if (id == 220)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_THBTotal.getValue())));
        }
        else if (id == 221)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_CountTHBTotal.getValue()));
        }
        else if (id == 222)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_CountJPYTotal.getValue()));
        }
        else if (id == 223)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_JPYTotal.getValue())));
        }
        else if (id == 224)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_INRTotal.getValue())));
        }
        else if (id == 225)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_CountINRTotal.getValue()));
        }
        else if (id == 226)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_CountMYRTotal.getValue()));
        }
        else if (id == 227)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_MYRTotal.getValue())));
        }
        else if (id == 228)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_SGDTotal.getValue())));
        }
        else if (id == 229)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_CountSGDTotal.getValue()));
        }

        return value;
    }


    /**
     *
     */
    Object evaluateOld(int id)
    {
        Object value = null;

        if (id >= 100)
        {
            value = evaluateOld1(id);
        }
        else if (id == 0)
        {
            value = (java.lang.String)("");
        }
        else if (id == 1)
        {
            value = (java.sql.Connection)(null);
        }
        else if (id == 2)
        {
            value = (java.lang.String)("../images");
        }
        else if (id == 3)
        {
            value = (java.lang.String)("../jrxml");
        }
        else if (id == 4)
        {
            value = (java.lang.String)("");
        }
        else if (id == 5)
        {
            value = (java.lang.String)("CUSTOM|FIN_FOREIGN_CURR_FCYBANK.FIN_FOREIGN_CURR_FCYBANK%3%CUSTOM::|where%TodayDate%=%((java.lang.String)parameter_TodayDate.getValue())%Parameter%Date::|INP_STR%1%java.lang.String%VARCHAR2::OUT_RETCODE%4%java.math.BigDecimal%NUMBER::OUT_REC%4%java.lang.String%VARCHAR2::|TodayDate%java.sql.Timestamp%10%!NULL!%Today Date@DBQUERY%NONE%java.sql.Timestamp!@!DEFAULT!@!8!@!10%CONSTANT%N%N::|{call CUSTOM.FIN_FOREIGN_CURR_FCYBANK.FIN_FOREIGN_CURR_FCYBANK( ((java.lang.String)parameter_FIN_INP_STR.getValue())  , ((java.math.BigDecimal)parameter_FIN_OUT_RETCODE.getValue()) , ((java.lang.String)parameter_FIN_OUT_REC.getValue()) ) } |{call CUSTOM.FIN_FOREIGN_CURR_FCYBANK.FIN_FOREIGN_CURR_FCYBANK( ((java.lang.String)parameter_FIN_INP_STR.getValue())  , ((java.math.BigDecimal)parameter_FIN_OUT_RETCODE.getValue()) , ((java.lang.String)parameter_FIN_OUT_REC.getValue()) ) } |false");
        }
        else if (id == 6)
        {
            value = (java.lang.String)(((java.lang.String)parameter_TodayDate.getValue()));
        }
        else if (id == 7)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 8)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 9)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 10)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 11)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 12)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 13)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 14)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 15)
        {
            value = (java.util.Date)(DateUtil.today());
        }
        else if (id == 16)
        {
            value = (java.util.Date)(DateUtil.today());
        }
        else if (id == 17)
        {
            value = (java.sql.Connection)(null);
        }
        else if (id == 18)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountUSD.getOldValue()));
        }
        else if (id == 19)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_USD.getOldValue()));
        }
        else if (id == 20)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountEUR.getOldValue()));
        }
        else if (id == 21)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_EUR.getOldValue()));
        }
        else if (id == 22)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountTHB.getOldValue()));
        }
        else if (id == 23)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_THB.getOldValue()));
        }
        else if (id == 24)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountJPY.getOldValue()));
        }
        else if (id == 25)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_JPY.getOldValue()));
        }
        else if (id == 26)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountINR.getOldValue()));
        }
        else if (id == 27)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_INR.getOldValue()));
        }
        else if (id == 28)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountMYR.getOldValue()));
        }
        else if (id == 29)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_MYR.getOldValue()));
        }
        else if (id == 30)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountSGD.getOldValue()));
        }
        else if (id == 31)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_SGD.getOldValue()));
        }
        else if (id == 32)
        {
            value = (java.lang.String)(FinUtil.getImage(((java.lang.String)field_Image_Name.getOldValue()), ((java.lang.String)parameter_FIN_IMG_PATH.getValue())));
        }
        else if (id == 33)
        {
            value = (java.lang.String)(((java.lang.String)field_Project_Bank_Name.getOldValue())+ "(" +((java.lang.String)field_BranchName.getOldValue()) +")");
        }
        else if (id == 34)
        {
            value = (java.lang.String)("Condition Of Opening Foreign Currency Account With Private Bank at "+((java.lang.String)parameter_TodayDate.getValue()));
        }
        else if (id == 35)
        {
            value = (java.lang.String)(((java.lang.String)field_BranchName.getOldValue()));
        }
        else if (id == 36)
        {
            value = (java.util.Date)(((java.util.Date)variable_TODAY.getOldValue()));
        }
        else if (id == 37)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getOldValue()));
        }
        else if (id == 38)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountUSD.getOldValue()));
        }
        else if (id == 39)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)field_USD.getOldValue())));
        }
        else if (id == 40)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountEUR.getOldValue()));
        }
        else if (id == 41)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)field_EUR.getOldValue())));
        }
        else if (id == 42)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountTHB.getOldValue()));
        }
        else if (id == 43)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)field_THB.getOldValue())));
        }
        else if (id == 44)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountJPY.getOldValue()));
        }
        else if (id == 45)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)field_JPY.getOldValue())));
        }
        else if (id == 46)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountINR.getOldValue()));
        }
        else if (id == 47)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)field_INR.getOldValue())));
        }
        else if (id == 48)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountMYR.getOldValue()));
        }
        else if (id == 49)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)field_MYR.getOldValue())));
        }
        else if (id == 50)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountSGD.getOldValue()));
        }
        else if (id == 51)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)field_SGD.getOldValue())));
        }
        else if (id == 52)
        {
            value = (java.lang.String)(((java.lang.String)field_Project_Bank_Name.getOldValue()));
        }
        else if (id == 53)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getOldValue())+1);
        }
        else if (id == 54)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 55)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 56)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 57)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 58)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 59)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 60)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 61)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 62)
        {
            value = (java.lang.String)("Co-operative Bank");
        }
        else if (id == 63)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 64)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 65)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 66)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 67)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 68)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 69)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getOldValue())+2);
        }
        else if (id == 70)
        {
            value = (java.lang.String)("Myawaddy Bank");
        }
        else if (id == 71)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 72)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 73)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 74)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 75)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 76)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 77)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 78)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 79)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 80)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 81)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 82)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 83)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 84)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 85)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getOldValue())+3);
        }
        else if (id == 86)
        {
            value = (java.lang.String)("Myanmar Oriental Bank");
        }
        else if (id == 87)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 88)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 89)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 90)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 91)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 92)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 93)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 94)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 95)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 96)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 97)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 98)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 99)
        {
            value = (java.lang.String)('-');
        }

        return value;
    }


    /**
     *
     */
    Object evaluateOld1(int id)
    {
        Object value = null;

        if (id >= 200)
        {
            value = evaluateOld2(id);
        }
        else if (id == 100)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 101)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getOldValue())+4);
        }
        else if (id == 102)
        {
            value = (java.lang.String)("Tun Foundation Bank");
        }
        else if (id == 103)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 104)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 105)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 106)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 107)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 108)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 109)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 110)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 111)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 112)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 113)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 114)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 115)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 116)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 117)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 118)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 119)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 120)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 121)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 122)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 123)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 124)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 125)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 126)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 127)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 128)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 129)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 130)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 131)
        {
            value = (java.lang.String)("Myanmar Industrial Development Bank");
        }
        else if (id == 132)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getOldValue())+5);
        }
        else if (id == 133)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getOldValue())+6);
        }
        else if (id == 134)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 135)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 136)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 137)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 138)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 139)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 140)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 141)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 142)
        {
            value = (java.lang.String)("Innwa Bank");
        }
        else if (id == 143)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getOldValue())+7);
        }
        else if (id == 144)
        {
            value = (java.lang.String)("Ayeyarwady Bank");
        }
        else if (id == 145)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 146)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 147)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 148)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 149)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 150)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 151)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 152)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 153)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getOldValue())+8);
        }
        else if (id == 154)
        {
            value = (java.lang.String)("United Amara Bank");
        }
        else if (id == 155)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 156)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 157)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 158)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 159)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 160)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 161)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 162)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 163)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getOldValue())+9);
        }
        else if (id == 164)
        {
            value = (java.lang.String)("Myanmar Apex Bank");
        }
        else if (id == 165)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 166)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 167)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 168)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 169)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 170)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 171)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 172)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 173)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 174)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 175)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 176)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 177)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 178)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 179)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 180)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 181)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 182)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 183)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 184)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 185)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 186)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 187)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 188)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 189)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 190)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 191)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 192)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 193)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 194)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 195)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 196)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 197)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getOldValue())+10);
        }
        else if (id == 198)
        {
            value = (java.lang.String)("Kanbawza Bank");
        }
        else if (id == 199)
        {
            value = (java.lang.String)('-');
        }

        return value;
    }


    /**
     *
     */
    Object evaluateOld2(int id)
    {
        Object value = null;

        if (id == 200)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 201)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 202)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 203)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 204)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 205)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 206)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 207)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 208)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 209)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 210)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 211)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 212)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 213)
        {
            value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
        }
        else if (id == 214)
        {
            value = (java.lang.String)("Total ( " + ((java.lang.Integer)variable_REPORT_COUNT.getOldValue())+ " ) Records Listed.");
        }
        else if (id == 215)
        {
            value = (java.lang.String)("Grand Total");
        }
        else if (id == 216)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_USDTotal.getOldValue())));
        }
        else if (id == 217)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_CountUSDTotal.getOldValue()));
        }
        else if (id == 218)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_CountEURTotal.getOldValue()));
        }
        else if (id == 219)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_EURTotal.getOldValue())));
        }
        else if (id == 220)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_THBTotal.getOldValue())));
        }
        else if (id == 221)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_CountTHBTotal.getOldValue()));
        }
        else if (id == 222)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_CountJPYTotal.getOldValue()));
        }
        else if (id == 223)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_JPYTotal.getOldValue())));
        }
        else if (id == 224)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_INRTotal.getOldValue())));
        }
        else if (id == 225)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_CountINRTotal.getOldValue()));
        }
        else if (id == 226)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_CountMYRTotal.getOldValue()));
        }
        else if (id == 227)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_MYRTotal.getOldValue())));
        }
        else if (id == 228)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_SGDTotal.getOldValue())));
        }
        else if (id == 229)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_CountSGDTotal.getOldValue()));
        }

        return value;
    }


    /**
     *
     */
    Object evaluateEstimated(int id)
    {
        Object value = null;

        if (id >= 100)
        {
            value = evaluateEstimated1(id);
        }
        else if (id == 0)
        {
            value = (java.lang.String)("");
        }
        else if (id == 1)
        {
            value = (java.sql.Connection)(null);
        }
        else if (id == 2)
        {
            value = (java.lang.String)("../images");
        }
        else if (id == 3)
        {
            value = (java.lang.String)("../jrxml");
        }
        else if (id == 4)
        {
            value = (java.lang.String)("");
        }
        else if (id == 5)
        {
            value = (java.lang.String)("CUSTOM|FIN_FOREIGN_CURR_FCYBANK.FIN_FOREIGN_CURR_FCYBANK%3%CUSTOM::|where%TodayDate%=%((java.lang.String)parameter_TodayDate.getValue())%Parameter%Date::|INP_STR%1%java.lang.String%VARCHAR2::OUT_RETCODE%4%java.math.BigDecimal%NUMBER::OUT_REC%4%java.lang.String%VARCHAR2::|TodayDate%java.sql.Timestamp%10%!NULL!%Today Date@DBQUERY%NONE%java.sql.Timestamp!@!DEFAULT!@!8!@!10%CONSTANT%N%N::|{call CUSTOM.FIN_FOREIGN_CURR_FCYBANK.FIN_FOREIGN_CURR_FCYBANK( ((java.lang.String)parameter_FIN_INP_STR.getValue())  , ((java.math.BigDecimal)parameter_FIN_OUT_RETCODE.getValue()) , ((java.lang.String)parameter_FIN_OUT_REC.getValue()) ) } |{call CUSTOM.FIN_FOREIGN_CURR_FCYBANK.FIN_FOREIGN_CURR_FCYBANK( ((java.lang.String)parameter_FIN_INP_STR.getValue())  , ((java.math.BigDecimal)parameter_FIN_OUT_RETCODE.getValue()) , ((java.lang.String)parameter_FIN_OUT_REC.getValue()) ) } |false");
        }
        else if (id == 6)
        {
            value = (java.lang.String)(((java.lang.String)parameter_TodayDate.getValue()));
        }
        else if (id == 7)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 8)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 9)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 10)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 11)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 12)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 13)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 14)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 15)
        {
            value = (java.util.Date)(DateUtil.today());
        }
        else if (id == 16)
        {
            value = (java.util.Date)(DateUtil.today());
        }
        else if (id == 17)
        {
            value = (java.sql.Connection)(null);
        }
        else if (id == 18)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountUSD.getValue()));
        }
        else if (id == 19)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_USD.getValue()));
        }
        else if (id == 20)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountEUR.getValue()));
        }
        else if (id == 21)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_EUR.getValue()));
        }
        else if (id == 22)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountTHB.getValue()));
        }
        else if (id == 23)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_THB.getValue()));
        }
        else if (id == 24)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountJPY.getValue()));
        }
        else if (id == 25)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_JPY.getValue()));
        }
        else if (id == 26)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountINR.getValue()));
        }
        else if (id == 27)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_INR.getValue()));
        }
        else if (id == 28)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountMYR.getValue()));
        }
        else if (id == 29)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_MYR.getValue()));
        }
        else if (id == 30)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountSGD.getValue()));
        }
        else if (id == 31)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_SGD.getValue()));
        }
        else if (id == 32)
        {
            value = (java.lang.String)(FinUtil.getImage(((java.lang.String)field_Image_Name.getValue()), ((java.lang.String)parameter_FIN_IMG_PATH.getValue())));
        }
        else if (id == 33)
        {
            value = (java.lang.String)(((java.lang.String)field_Project_Bank_Name.getValue())+ "(" +((java.lang.String)field_BranchName.getValue()) +")");
        }
        else if (id == 34)
        {
            value = (java.lang.String)("Condition Of Opening Foreign Currency Account With Private Bank at "+((java.lang.String)parameter_TodayDate.getValue()));
        }
        else if (id == 35)
        {
            value = (java.lang.String)(((java.lang.String)field_BranchName.getValue()));
        }
        else if (id == 36)
        {
            value = (java.util.Date)(((java.util.Date)variable_TODAY.getEstimatedValue()));
        }
        else if (id == 37)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getEstimatedValue()));
        }
        else if (id == 38)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountUSD.getValue()));
        }
        else if (id == 39)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)field_USD.getValue())));
        }
        else if (id == 40)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountEUR.getValue()));
        }
        else if (id == 41)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)field_EUR.getValue())));
        }
        else if (id == 42)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountTHB.getValue()));
        }
        else if (id == 43)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)field_THB.getValue())));
        }
        else if (id == 44)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountJPY.getValue()));
        }
        else if (id == 45)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)field_JPY.getValue())));
        }
        else if (id == 46)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountINR.getValue()));
        }
        else if (id == 47)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)field_INR.getValue())));
        }
        else if (id == 48)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountMYR.getValue()));
        }
        else if (id == 49)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)field_MYR.getValue())));
        }
        else if (id == 50)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CountSGD.getValue()));
        }
        else if (id == 51)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)field_SGD.getValue())));
        }
        else if (id == 52)
        {
            value = (java.lang.String)(((java.lang.String)field_Project_Bank_Name.getValue()));
        }
        else if (id == 53)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getEstimatedValue())+1);
        }
        else if (id == 54)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 55)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 56)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 57)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 58)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 59)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 60)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 61)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 62)
        {
            value = (java.lang.String)("Co-operative Bank");
        }
        else if (id == 63)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 64)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 65)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 66)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 67)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 68)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 69)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getEstimatedValue())+2);
        }
        else if (id == 70)
        {
            value = (java.lang.String)("Myawaddy Bank");
        }
        else if (id == 71)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 72)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 73)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 74)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 75)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 76)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 77)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 78)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 79)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 80)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 81)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 82)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 83)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 84)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 85)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getEstimatedValue())+3);
        }
        else if (id == 86)
        {
            value = (java.lang.String)("Myanmar Oriental Bank");
        }
        else if (id == 87)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 88)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 89)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 90)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 91)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 92)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 93)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 94)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 95)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 96)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 97)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 98)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 99)
        {
            value = (java.lang.String)('-');
        }

        return value;
    }


    /**
     *
     */
    Object evaluateEstimated1(int id)
    {
        Object value = null;

        if (id >= 200)
        {
            value = evaluateEstimated2(id);
        }
        else if (id == 100)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 101)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getEstimatedValue())+4);
        }
        else if (id == 102)
        {
            value = (java.lang.String)("Tun Foundation Bank");
        }
        else if (id == 103)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 104)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 105)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 106)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 107)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 108)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 109)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 110)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 111)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 112)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 113)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 114)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 115)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 116)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 117)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 118)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 119)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 120)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 121)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 122)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 123)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 124)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 125)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 126)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 127)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 128)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 129)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 130)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 131)
        {
            value = (java.lang.String)("Myanmar Industrial Development Bank");
        }
        else if (id == 132)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getEstimatedValue())+5);
        }
        else if (id == 133)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getEstimatedValue())+6);
        }
        else if (id == 134)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 135)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 136)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 137)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 138)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 139)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 140)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 141)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 142)
        {
            value = (java.lang.String)("Innwa Bank");
        }
        else if (id == 143)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getEstimatedValue())+7);
        }
        else if (id == 144)
        {
            value = (java.lang.String)("Ayeyarwady Bank");
        }
        else if (id == 145)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 146)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 147)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 148)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 149)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 150)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 151)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 152)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 153)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getEstimatedValue())+8);
        }
        else if (id == 154)
        {
            value = (java.lang.String)("United Amara Bank");
        }
        else if (id == 155)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 156)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 157)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 158)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 159)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 160)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 161)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 162)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 163)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getEstimatedValue())+9);
        }
        else if (id == 164)
        {
            value = (java.lang.String)("Myanmar Apex Bank");
        }
        else if (id == 165)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 166)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 167)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 168)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 169)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 170)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 171)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 172)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 173)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 174)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 175)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 176)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 177)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 178)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 179)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 180)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 181)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 182)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 183)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 184)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 185)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 186)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 187)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 188)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 189)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 190)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 191)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 192)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 193)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 194)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 195)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 196)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 197)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getEstimatedValue())+10);
        }
        else if (id == 198)
        {
            value = (java.lang.String)("Kanbawza Bank");
        }
        else if (id == 199)
        {
            value = (java.lang.String)('-');
        }

        return value;
    }


    /**
     *
     */
    Object evaluateEstimated2(int id)
    {
        Object value = null;

        if (id == 200)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 201)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 202)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 203)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 204)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 205)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 206)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 207)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 208)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 209)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 210)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 211)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 212)
        {
            value = (java.lang.String)('-');
        }
        else if (id == 213)
        {
            value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
        }
        else if (id == 214)
        {
            value = (java.lang.String)("Total ( " + ((java.lang.Integer)variable_REPORT_COUNT.getEstimatedValue())+ " ) Records Listed.");
        }
        else if (id == 215)
        {
            value = (java.lang.String)("Grand Total");
        }
        else if (id == 216)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_USDTotal.getEstimatedValue())));
        }
        else if (id == 217)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_CountUSDTotal.getEstimatedValue()));
        }
        else if (id == 218)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_CountEURTotal.getEstimatedValue()));
        }
        else if (id == 219)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_EURTotal.getEstimatedValue())));
        }
        else if (id == 220)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_THBTotal.getEstimatedValue())));
        }
        else if (id == 221)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_CountTHBTotal.getEstimatedValue()));
        }
        else if (id == 222)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_CountJPYTotal.getEstimatedValue()));
        }
        else if (id == 223)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_JPYTotal.getEstimatedValue())));
        }
        else if (id == 224)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_INRTotal.getEstimatedValue())));
        }
        else if (id == 225)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_CountINRTotal.getEstimatedValue()));
        }
        else if (id == 226)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_CountMYRTotal.getEstimatedValue()));
        }
        else if (id == 227)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_MYRTotal.getEstimatedValue())));
        }
        else if (id == 228)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_SGDTotal.getEstimatedValue())));
        }
        else if (id == 229)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_CountSGDTotal.getEstimatedValue()));
        }

        return value;
    }


}
