/*
 * Generated by JasperReports - 12/7/17 10:21 AM
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import com.infy.finacle.finrpt.utils.*;
import net.sf.jasperreports.engine.*;
import com.infy.finacle.finrpt.ireport.*;
import java.util.*;
import com.infy.finacle.finrpt.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
class TOD_Listing_1512618709958_201744 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_P_vi_TranDate = null;
    private JRFillParameter parameter_REPORT_TIME_ZONE = null;
    private JRFillParameter parameter_FIN_REPORT_TYPE = null;
    private JRFillParameter parameter_REPORT_FILE_RESOLVER = null;
    private JRFillParameter parameter_FIN_OUT_REC = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_FIN_REPORT_DESC = null;
    private JRFillParameter parameter_FIN_SER_FINQUERY = null;
    private JRFillParameter parameter_FINRPT_DEFAULT_FORMAT = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_REPORT_URL_HANDLER_FACTORY = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillParameter parameter_REPORT_TEMPLATES = null;
    private JRFillParameter parameter_FIN_DB_CONN = null;
    private JRFillParameter parameter_FIN_REPOS_FILE = null;
    private JRFillParameter parameter_FIN_OUT_RETCODE = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_FIN_REPORT_TO = null;
    private JRFillParameter parameter_FIN_BANKREPOS_PARAM = null;
    private JRFillParameter parameter_FIN_IMG_PATH = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_FIN_REPOS_LIST = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_P_vi_currency = null;
    private JRFillParameter parameter_FIN_SESSION_ID = null;
    private JRFillParameter parameter_FIN_TEMPLATE_PATH = null;
    private JRFillParameter parameter_FIN_APP_UTIL = null;
    private JRFillParameter parameter_REPORT_FORMAT_FACTORY = null;
    private JRFillParameter parameter_FIN_JASPER_PATH = null;
    private JRFillParameter parameter_FIN_INP_STR = null;
    private JRFillParameter parameter_P_vi_branch_code = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillField field_v_sol_desc = null;
    private JRFillField field_BankAddress = null;
    private JRFillField field_v_Demand_Loan_TOD_amount = null;
    private JRFillField field_Project_Bank_Name = null;
    private JRFillField field_BankFax = null;
    private JRFillField field_v_HP_TOD_no = null;
    private JRFillField field_v_Staff_Loan_TOD_limit_amount = null;
    private JRFillField field_v_Overdraft_TOD_amount = null;
    private JRFillField field_Image_Name = null;
    private JRFillField field_v_Staff_Loan_TOD_no = null;
    private JRFillField field_BranchName = null;
    private JRFillField field_v_Demand_Loan_TOD_limit_amount = null;
    private JRFillField field_v_HP_TOD_amount = null;
    private JRFillField field_v_Demand_Loan_TOD_no = null;
    private JRFillField field_v_Overdraft_TOD_no = null;
    private JRFillField field_v_HP_TOD_limit_amount = null;
    private JRFillField field_v_Overdraft_TOD_limit_amount = null;
    private JRFillField field_v_Staff_Loan_TOD_amount = null;
    private JRFillField field_BankPhone = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_FIN_REPOSITORY = null;
    private JRFillVariable variable_TODAY = null;
    private JRFillVariable variable_FIN_DB_CONN = null;
    private JRFillVariable variable_DemandLoanTOD_Limit_amt = null;
    private JRFillVariable variable_DemandLoanTOD_Count = null;
    private JRFillVariable variable_DemandLoanTOD_Amount = null;
    private JRFillVariable variable_Overdraft_TOD_Limit_Amt = null;
    private JRFillVariable variable_Overdraft_TOD_Count = null;
    private JRFillVariable variable_Overdraft_TOD_Amount = null;
    private JRFillVariable variable_Staff_Loan_TOD_Limit_Amt = null;
    private JRFillVariable variable_Staff_Loan_TOD_Count = null;
    private JRFillVariable variable_Staff_Loan_TOD_Amt = null;
    private JRFillVariable variable_HP_TOD_Limit_Amt = null;
    private JRFillVariable variable_HP_TOD_Count = null;
    private JRFillVariable variable_HP_TOD_Amt = null;
    private JRFillVariable variable_GrandTotal_DemandLoanTOD_Limit_Amt = null;
    private JRFillVariable variable_GrandTotal_DemandLoanTOD_Count = null;
    private JRFillVariable variable_GrandTotal_DemandLoanTOD_Amt = null;
    private JRFillVariable variable_GrandTotal_Overdraft_TOD_Limit_Amt = null;
    private JRFillVariable variable_GrandTotal_Overdraft_TOD_Count = null;
    private JRFillVariable variable_GrandTotal_Overdraft_TOD_Amt = null;
    private JRFillVariable variable_GrandTotal_Staff_Loan_TOD_Limit_Amt = null;
    private JRFillVariable variable_GrandTotal_Staff_Loan_TOD_Count = null;
    private JRFillVariable variable_GrandTotal_Staff_Loan_TOD_Amt = null;
    private JRFillVariable variable_GrandTotal_HP_TOD_Limit_Amt = null;
    private JRFillVariable variable_GrandTotal_HP_TOD_Count = null;
    private JRFillVariable variable_GrandTotal_HP_TOD_Amt = null;


    /**
     *
     */
    void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    void initParams(Map pm)
    {
        parameter_P_vi_TranDate = (JRFillParameter)pm.get("P_vi_TranDate");
        parameter_REPORT_TIME_ZONE = (JRFillParameter)pm.get("REPORT_TIME_ZONE");
        parameter_FIN_REPORT_TYPE = (JRFillParameter)pm.get("FIN_REPORT_TYPE");
        parameter_REPORT_FILE_RESOLVER = (JRFillParameter)pm.get("REPORT_FILE_RESOLVER");
        parameter_FIN_OUT_REC = (JRFillParameter)pm.get("FIN_OUT_REC");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_FIN_REPORT_DESC = (JRFillParameter)pm.get("FIN_REPORT_DESC");
        parameter_FIN_SER_FINQUERY = (JRFillParameter)pm.get("FIN_SER_FINQUERY");
        parameter_FINRPT_DEFAULT_FORMAT = (JRFillParameter)pm.get("FINRPT_DEFAULT_FORMAT");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_REPORT_URL_HANDLER_FACTORY = (JRFillParameter)pm.get("REPORT_URL_HANDLER_FACTORY");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
        parameter_REPORT_TEMPLATES = (JRFillParameter)pm.get("REPORT_TEMPLATES");
        parameter_FIN_DB_CONN = (JRFillParameter)pm.get("FIN_DB_CONN");
        parameter_FIN_REPOS_FILE = (JRFillParameter)pm.get("FIN_REPOS_FILE");
        parameter_FIN_OUT_RETCODE = (JRFillParameter)pm.get("FIN_OUT_RETCODE");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_FIN_REPORT_TO = (JRFillParameter)pm.get("FIN_REPORT_TO");
        parameter_FIN_BANKREPOS_PARAM = (JRFillParameter)pm.get("FIN_BANKREPOS_PARAM");
        parameter_FIN_IMG_PATH = (JRFillParameter)pm.get("FIN_IMG_PATH");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_FIN_REPOS_LIST = (JRFillParameter)pm.get("FIN_REPOS_LIST");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_P_vi_currency = (JRFillParameter)pm.get("P_vi_currency");
        parameter_FIN_SESSION_ID = (JRFillParameter)pm.get("FIN_SESSION_ID");
        parameter_FIN_TEMPLATE_PATH = (JRFillParameter)pm.get("FIN_TEMPLATE_PATH");
        parameter_FIN_APP_UTIL = (JRFillParameter)pm.get("FIN_APP_UTIL");
        parameter_REPORT_FORMAT_FACTORY = (JRFillParameter)pm.get("REPORT_FORMAT_FACTORY");
        parameter_FIN_JASPER_PATH = (JRFillParameter)pm.get("FIN_JASPER_PATH");
        parameter_FIN_INP_STR = (JRFillParameter)pm.get("FIN_INP_STR");
        parameter_P_vi_branch_code = (JRFillParameter)pm.get("P_vi_branch_code");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
    }


    /**
     *
     */
    void initFields(Map fm)
    {
        field_v_sol_desc = (JRFillField)fm.get("v_sol_desc");
        field_BankAddress = (JRFillField)fm.get("BankAddress");
        field_v_Demand_Loan_TOD_amount = (JRFillField)fm.get("v_Demand_Loan_TOD_amount");
        field_Project_Bank_Name = (JRFillField)fm.get("Project_Bank_Name");
        field_BankFax = (JRFillField)fm.get("BankFax");
        field_v_HP_TOD_no = (JRFillField)fm.get("v_HP_TOD_no");
        field_v_Staff_Loan_TOD_limit_amount = (JRFillField)fm.get("v_Staff_Loan_TOD_limit_amount");
        field_v_Overdraft_TOD_amount = (JRFillField)fm.get("v_Overdraft_TOD_amount");
        field_Image_Name = (JRFillField)fm.get("Image_Name");
        field_v_Staff_Loan_TOD_no = (JRFillField)fm.get("v_Staff_Loan_TOD_no");
        field_BranchName = (JRFillField)fm.get("BranchName");
        field_v_Demand_Loan_TOD_limit_amount = (JRFillField)fm.get("v_Demand_Loan_TOD_limit_amount");
        field_v_HP_TOD_amount = (JRFillField)fm.get("v_HP_TOD_amount");
        field_v_Demand_Loan_TOD_no = (JRFillField)fm.get("v_Demand_Loan_TOD_no");
        field_v_Overdraft_TOD_no = (JRFillField)fm.get("v_Overdraft_TOD_no");
        field_v_HP_TOD_limit_amount = (JRFillField)fm.get("v_HP_TOD_limit_amount");
        field_v_Overdraft_TOD_limit_amount = (JRFillField)fm.get("v_Overdraft_TOD_limit_amount");
        field_v_Staff_Loan_TOD_amount = (JRFillField)fm.get("v_Staff_Loan_TOD_amount");
        field_BankPhone = (JRFillField)fm.get("BankPhone");
    }


    /**
     *
     */
    void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
        variable_FIN_REPOSITORY = (JRFillVariable)vm.get("FIN_REPOSITORY");
        variable_TODAY = (JRFillVariable)vm.get("TODAY");
        variable_FIN_DB_CONN = (JRFillVariable)vm.get("FIN_DB_CONN");
        variable_DemandLoanTOD_Limit_amt = (JRFillVariable)vm.get("DemandLoanTOD_Limit_amt");
        variable_DemandLoanTOD_Count = (JRFillVariable)vm.get("DemandLoanTOD_Count");
        variable_DemandLoanTOD_Amount = (JRFillVariable)vm.get("DemandLoanTOD_Amount");
        variable_Overdraft_TOD_Limit_Amt = (JRFillVariable)vm.get("Overdraft_TOD_Limit_Amt");
        variable_Overdraft_TOD_Count = (JRFillVariable)vm.get("Overdraft_TOD_Count");
        variable_Overdraft_TOD_Amount = (JRFillVariable)vm.get("Overdraft_TOD_Amount");
        variable_Staff_Loan_TOD_Limit_Amt = (JRFillVariable)vm.get("Staff_Loan_TOD_Limit_Amt");
        variable_Staff_Loan_TOD_Count = (JRFillVariable)vm.get("Staff_Loan_TOD_Count");
        variable_Staff_Loan_TOD_Amt = (JRFillVariable)vm.get("Staff_Loan_TOD_Amt");
        variable_HP_TOD_Limit_Amt = (JRFillVariable)vm.get("HP_TOD_Limit_Amt");
        variable_HP_TOD_Count = (JRFillVariable)vm.get("HP_TOD_Count");
        variable_HP_TOD_Amt = (JRFillVariable)vm.get("HP_TOD_Amt");
        variable_GrandTotal_DemandLoanTOD_Limit_Amt = (JRFillVariable)vm.get("GrandTotal_DemandLoanTOD_Limit_Amt");
        variable_GrandTotal_DemandLoanTOD_Count = (JRFillVariable)vm.get("GrandTotal_DemandLoanTOD_Count");
        variable_GrandTotal_DemandLoanTOD_Amt = (JRFillVariable)vm.get("GrandTotal_DemandLoanTOD_Amt");
        variable_GrandTotal_Overdraft_TOD_Limit_Amt = (JRFillVariable)vm.get("GrandTotal_Overdraft_TOD_Limit_Amt");
        variable_GrandTotal_Overdraft_TOD_Count = (JRFillVariable)vm.get("GrandTotal_Overdraft_TOD_Count");
        variable_GrandTotal_Overdraft_TOD_Amt = (JRFillVariable)vm.get("GrandTotal_Overdraft_TOD_Amt");
        variable_GrandTotal_Staff_Loan_TOD_Limit_Amt = (JRFillVariable)vm.get("GrandTotal_Staff_Loan_TOD_Limit_Amt");
        variable_GrandTotal_Staff_Loan_TOD_Count = (JRFillVariable)vm.get("GrandTotal_Staff_Loan_TOD_Count");
        variable_GrandTotal_Staff_Loan_TOD_Amt = (JRFillVariable)vm.get("GrandTotal_Staff_Loan_TOD_Amt");
        variable_GrandTotal_HP_TOD_Limit_Amt = (JRFillVariable)vm.get("GrandTotal_HP_TOD_Limit_Amt");
        variable_GrandTotal_HP_TOD_Count = (JRFillVariable)vm.get("GrandTotal_HP_TOD_Count");
        variable_GrandTotal_HP_TOD_Amt = (JRFillVariable)vm.get("GrandTotal_HP_TOD_Amt");
    }


    /**
     *
     */
    Object evaluate(int id)
    {
        Object value = null;

        if (id == 0)
        {
            value = (java.lang.String)("");
        }
        else if (id == 1)
        {
            value = (java.sql.Connection)(null);
        }
        else if (id == 2)
        {
            value = (java.lang.String)("../images");
        }
        else if (id == 3)
        {
            value = (java.lang.String)("../jrxml");
        }
        else if (id == 4)
        {
            value = (java.lang.String)("");
        }
        else if (id == 5)
        {
            value = (java.lang.String)("");
        }
        else if (id == 6)
        {
            value = (java.lang.String)("");
        }
        else if (id == 7)
        {
            value = (java.lang.String)("CUSTOM|FIN_TOD_LISTING.FIN_TOD_LISTING%3%CUSTOM::|where%vi_TranDate%=%((java.lang.String)parameter_P_vi_TranDate.getValue())%Parameter%Date::and%vi_currency%=%((java.lang.String)parameter_P_vi_currency.getValue())%Parameter%String::and%vi_branch_code%=%((java.lang.String)parameter_P_vi_branch_code.getValue())%Parameter%String::|INP_STR%1%java.lang.String%VARCHAR2::OUT_RETCODE%4%java.math.BigDecimal%NUMBER::OUT_REC%4%java.lang.String%VARCHAR2::|P_vi_TranDate%java.sql.Timestamp%10%!NULL!%Transaction Date@DBQUERY%NONE%java.sql.Timestamp!@!DEFAULT!@!8!@!10%CONSTANT%N%N::P_vi_currency%java.lang.String%100%!NULL!%Currency Code@DBQUERY%PRODUCT!@!Cntry_Crncy_List#@#N%java.lang.String!@!DEFAULT!@!0!@!100%CONSTANT%N%N::P_vi_branch_code%java.lang.String%100%!NULL!%Branch Code@DBQUERY%PRODUCT!@!SolID_List#@#N%java.lang.String!@!DEFAULT!@!0!@!100%CONSTANT%N%N::|{call CUSTOM.FIN_TOD_LISTING.FIN_TOD_LISTING( ((java.lang.String)parameter_FIN_INP_STR.getValue())  , ((java.math.BigDecimal)parameter_FIN_OUT_RETCODE.getValue()) , ((java.lang.String)parameter_FIN_OUT_REC.getValue()) ) } |{call CUSTOM.FIN_TOD_LISTING.FIN_TOD_LISTING( ((java.lang.String)parameter_FIN_INP_STR.getValue())  , ((java.math.BigDecimal)parameter_FIN_OUT_RETCODE.getValue()) , ((java.lang.String)parameter_FIN_OUT_REC.getValue()) ) } |false");
        }
        else if (id == 8)
        {
            value = (java.lang.String)(((java.lang.String)parameter_P_vi_TranDate.getValue()) + "!" +((java.lang.String)parameter_P_vi_currency.getValue()) + "!" +((java.lang.String)parameter_P_vi_branch_code.getValue()));
        }
        else if (id == 9)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 10)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 11)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 12)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 13)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 14)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 15)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 16)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 17)
        {
            value = (java.util.Date)(DateUtil.today());
        }
        else if (id == 18)
        {
            value = (java.util.Date)(DateUtil.today());
        }
        else if (id == 19)
        {
            value = (java.sql.Connection)(null);
        }
        else if (id == 20)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_Demand_Loan_TOD_limit_amount.getValue())==null || ((java.math.BigDecimal)field_v_Demand_Loan_TOD_limit_amount.getValue())==0 ? 0.00 :((java.math.BigDecimal)field_v_Demand_Loan_TOD_limit_amount.getValue()));
        }
        else if (id == 21)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_Demand_Loan_TOD_no.getValue())==null || ((java.math.BigDecimal)field_v_Demand_Loan_TOD_no.getValue())==0 ? 0.00 :((java.math.BigDecimal)field_v_Demand_Loan_TOD_no.getValue()));
        }
        else if (id == 22)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_Demand_Loan_TOD_amount.getValue())==null || ((java.math.BigDecimal)field_v_Demand_Loan_TOD_amount.getValue())==0 ? 0.00 :((java.math.BigDecimal)field_v_Demand_Loan_TOD_amount.getValue()));
        }
        else if (id == 23)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_Overdraft_TOD_limit_amount.getValue())==null ||((java.math.BigDecimal)field_v_Overdraft_TOD_limit_amount.getValue())==0 ? 0.00 : ((java.math.BigDecimal)field_v_Overdraft_TOD_limit_amount.getValue()));
        }
        else if (id == 24)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_Overdraft_TOD_no.getValue())==null || ((java.math.BigDecimal)field_v_Overdraft_TOD_no.getValue())==0 ? 0.00 :((java.math.BigDecimal)field_v_Overdraft_TOD_no.getValue()));
        }
        else if (id == 25)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_Overdraft_TOD_amount.getValue())==null || ((java.math.BigDecimal)field_v_Overdraft_TOD_amount.getValue())==0 ? 0.00 :((java.math.BigDecimal)field_v_Overdraft_TOD_amount.getValue()));
        }
        else if (id == 26)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_Staff_Loan_TOD_limit_amount.getValue())==null || ((java.math.BigDecimal)field_v_Staff_Loan_TOD_limit_amount.getValue())==0 ? 0.00 : ((java.math.BigDecimal)field_v_Staff_Loan_TOD_limit_amount.getValue()));
        }
        else if (id == 27)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_Staff_Loan_TOD_no.getValue())==null || ((java.math.BigDecimal)field_v_Staff_Loan_TOD_no.getValue())==0 ? 0.00 :((java.math.BigDecimal)field_v_Staff_Loan_TOD_no.getValue()));
        }
        else if (id == 28)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_Staff_Loan_TOD_amount.getValue())==null ||((java.math.BigDecimal)field_v_Staff_Loan_TOD_amount.getValue())== 0 ? 0.00 :((java.math.BigDecimal)field_v_Staff_Loan_TOD_amount.getValue()));
        }
        else if (id == 29)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_HP_TOD_limit_amount.getValue())==null ||((java.math.BigDecimal)field_v_HP_TOD_limit_amount.getValue())==0 ? 0.00 : ((java.math.BigDecimal)field_v_HP_TOD_limit_amount.getValue()));
        }
        else if (id == 30)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_HP_TOD_no.getValue())==null || ((java.math.BigDecimal)field_v_HP_TOD_no.getValue())== 0 ? 0.00 : ((java.math.BigDecimal)field_v_HP_TOD_no.getValue()));
        }
        else if (id == 31)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_HP_TOD_amount.getValue())==null || ((java.math.BigDecimal)field_v_HP_TOD_amount.getValue())== 0 ? 0.00 : ((java.math.BigDecimal)field_v_HP_TOD_amount.getValue()));
        }
        else if (id == 32)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_DemandLoanTOD_Limit_amt.getValue())));
        }
        else if (id == 33)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_DemandLoanTOD_Count.getValue()));
        }
        else if (id == 34)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_DemandLoanTOD_Amount.getValue())));
        }
        else if (id == 35)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Overdraft_TOD_Limit_Amt.getValue()));
        }
        else if (id == 36)
        {
            value = (java.math.BigDecimal)((((java.math.BigDecimal)variable_Overdraft_TOD_Count.getValue())));
        }
        else if (id == 37)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Overdraft_TOD_Amount.getValue()));
        }
        else if (id == 38)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_Staff_Loan_TOD_Limit_Amt.getValue())));
        }
        else if (id == 39)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Staff_Loan_TOD_Count.getValue()));
        }
        else if (id == 40)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_Staff_Loan_TOD_Amt.getValue())));
        }
        else if (id == 41)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_HP_TOD_Limit_Amt.getValue())));
        }
        else if (id == 42)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_HP_TOD_Count.getValue()));
        }
        else if (id == 43)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_HP_TOD_Amt.getValue())));
        }
        else if (id == 44)
        {
            value = (java.lang.String)(FinUtil.getImage(((java.lang.String)field_Image_Name.getValue()),((java.lang.String)parameter_FIN_IMG_PATH.getValue())));
        }
        else if (id == 45)
        {
            value = (java.lang.String)(((java.lang.String)field_Project_Bank_Name.getValue()));
        }
        else if (id == 46)
        {
            value = (java.lang.String)("Type By Loan and Advanced Position TOD Listing (All)");
        }
        else if (id == 47)
        {
            value = (java.lang.String)("As Date : " +((java.lang.String)parameter_P_vi_TranDate.getValue()));
        }
        else if (id == 48)
        {
            value = (java.lang.String)("Currency :" + ((java.lang.String)parameter_P_vi_currency.getValue()));
        }
        else if (id == 49)
        {
            value = (java.util.Date)(((java.util.Date)variable_TODAY.getValue()));
        }
        else if (id == 50)
        {
            value = (java.lang.String)(((java.lang.String)field_v_sol_desc.getValue()));
        }
        else if (id == 51)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_DemandLoanTOD_Limit_amt.getValue())));
        }
        else if (id == 52)
        {
            value = (java.lang.Integer)(((java.math.BigDecimal)variable_DemandLoanTOD_Count.getValue()));
        }
        else if (id == 53)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_DemandLoanTOD_Amount.getValue())));
        }
        else if (id == 54)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_HP_TOD_Limit_Amt.getValue())));
        }
        else if (id == 55)
        {
            value = (java.lang.Integer)(((java.math.BigDecimal)variable_HP_TOD_Count.getValue()));
        }
        else if (id == 56)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_HP_TOD_Amt.getValue())));
        }
        else if (id == 57)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_Staff_Loan_TOD_Limit_Amt.getValue())));
        }
        else if (id == 58)
        {
            value = (java.lang.Integer)(((java.math.BigDecimal)variable_Staff_Loan_TOD_Count.getValue()));
        }
        else if (id == 59)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_Staff_Loan_TOD_Amt.getValue())));
        }
        else if (id == 60)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_Overdraft_TOD_Limit_Amt.getValue())));
        }
        else if (id == 61)
        {
            value = (java.lang.Integer)(((java.math.BigDecimal)variable_Overdraft_TOD_Count.getValue()));
        }
        else if (id == 62)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_Overdraft_TOD_Amount.getValue())));
        }
        else if (id == 63)
        {
            value = (java.lang.Integer)(((java.lang.Integer)variable_REPORT_COUNT.getValue()));
        }
        else if (id == 64)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
        }
        else if (id == 65)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_GrandTotal_DemandLoanTOD_Limit_Amt.getValue()));
        }
        else if (id == 66)
        {
            value = (java.lang.Integer)(((java.math.BigDecimal)variable_GrandTotal_DemandLoanTOD_Count.getValue()));
        }
        else if (id == 67)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_GrandTotal_DemandLoanTOD_Amt.getValue()));
        }
        else if (id == 68)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_GrandTotal_HP_TOD_Limit_Amt.getValue()));
        }
        else if (id == 69)
        {
            value = (java.lang.Integer)(((java.math.BigDecimal)variable_GrandTotal_HP_TOD_Count.getValue()));
        }
        else if (id == 70)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_GrandTotal_HP_TOD_Amt.getValue()));
        }
        else if (id == 71)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_GrandTotal_Staff_Loan_TOD_Limit_Amt.getValue()));
        }
        else if (id == 72)
        {
            value = (java.lang.Integer)(((java.math.BigDecimal)variable_GrandTotal_Staff_Loan_TOD_Count.getValue()));
        }
        else if (id == 73)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_GrandTotal_Staff_Loan_TOD_Amt.getValue()));
        }
        else if (id == 74)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_GrandTotal_Overdraft_TOD_Limit_Amt.getValue())));
        }
        else if (id == 75)
        {
            value = (java.lang.Integer)(((java.math.BigDecimal)variable_GrandTotal_Overdraft_TOD_Count.getValue()));
        }
        else if (id == 76)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_GrandTotal_Overdraft_TOD_Amt.getValue())));
        }

        return value;
    }


    /**
     *
     */
    Object evaluateOld(int id)
    {
        Object value = null;

        if (id == 0)
        {
            value = (java.lang.String)("");
        }
        else if (id == 1)
        {
            value = (java.sql.Connection)(null);
        }
        else if (id == 2)
        {
            value = (java.lang.String)("../images");
        }
        else if (id == 3)
        {
            value = (java.lang.String)("../jrxml");
        }
        else if (id == 4)
        {
            value = (java.lang.String)("");
        }
        else if (id == 5)
        {
            value = (java.lang.String)("");
        }
        else if (id == 6)
        {
            value = (java.lang.String)("");
        }
        else if (id == 7)
        {
            value = (java.lang.String)("CUSTOM|FIN_TOD_LISTING.FIN_TOD_LISTING%3%CUSTOM::|where%vi_TranDate%=%((java.lang.String)parameter_P_vi_TranDate.getValue())%Parameter%Date::and%vi_currency%=%((java.lang.String)parameter_P_vi_currency.getValue())%Parameter%String::and%vi_branch_code%=%((java.lang.String)parameter_P_vi_branch_code.getValue())%Parameter%String::|INP_STR%1%java.lang.String%VARCHAR2::OUT_RETCODE%4%java.math.BigDecimal%NUMBER::OUT_REC%4%java.lang.String%VARCHAR2::|P_vi_TranDate%java.sql.Timestamp%10%!NULL!%Transaction Date@DBQUERY%NONE%java.sql.Timestamp!@!DEFAULT!@!8!@!10%CONSTANT%N%N::P_vi_currency%java.lang.String%100%!NULL!%Currency Code@DBQUERY%PRODUCT!@!Cntry_Crncy_List#@#N%java.lang.String!@!DEFAULT!@!0!@!100%CONSTANT%N%N::P_vi_branch_code%java.lang.String%100%!NULL!%Branch Code@DBQUERY%PRODUCT!@!SolID_List#@#N%java.lang.String!@!DEFAULT!@!0!@!100%CONSTANT%N%N::|{call CUSTOM.FIN_TOD_LISTING.FIN_TOD_LISTING( ((java.lang.String)parameter_FIN_INP_STR.getValue())  , ((java.math.BigDecimal)parameter_FIN_OUT_RETCODE.getValue()) , ((java.lang.String)parameter_FIN_OUT_REC.getValue()) ) } |{call CUSTOM.FIN_TOD_LISTING.FIN_TOD_LISTING( ((java.lang.String)parameter_FIN_INP_STR.getValue())  , ((java.math.BigDecimal)parameter_FIN_OUT_RETCODE.getValue()) , ((java.lang.String)parameter_FIN_OUT_REC.getValue()) ) } |false");
        }
        else if (id == 8)
        {
            value = (java.lang.String)(((java.lang.String)parameter_P_vi_TranDate.getValue()) + "!" +((java.lang.String)parameter_P_vi_currency.getValue()) + "!" +((java.lang.String)parameter_P_vi_branch_code.getValue()));
        }
        else if (id == 9)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 10)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 11)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 12)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 13)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 14)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 15)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 16)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 17)
        {
            value = (java.util.Date)(DateUtil.today());
        }
        else if (id == 18)
        {
            value = (java.util.Date)(DateUtil.today());
        }
        else if (id == 19)
        {
            value = (java.sql.Connection)(null);
        }
        else if (id == 20)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_Demand_Loan_TOD_limit_amount.getOldValue())==null || ((java.math.BigDecimal)field_v_Demand_Loan_TOD_limit_amount.getOldValue())==0 ? 0.00 :((java.math.BigDecimal)field_v_Demand_Loan_TOD_limit_amount.getOldValue()));
        }
        else if (id == 21)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_Demand_Loan_TOD_no.getOldValue())==null || ((java.math.BigDecimal)field_v_Demand_Loan_TOD_no.getOldValue())==0 ? 0.00 :((java.math.BigDecimal)field_v_Demand_Loan_TOD_no.getOldValue()));
        }
        else if (id == 22)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_Demand_Loan_TOD_amount.getOldValue())==null || ((java.math.BigDecimal)field_v_Demand_Loan_TOD_amount.getOldValue())==0 ? 0.00 :((java.math.BigDecimal)field_v_Demand_Loan_TOD_amount.getOldValue()));
        }
        else if (id == 23)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_Overdraft_TOD_limit_amount.getOldValue())==null ||((java.math.BigDecimal)field_v_Overdraft_TOD_limit_amount.getOldValue())==0 ? 0.00 : ((java.math.BigDecimal)field_v_Overdraft_TOD_limit_amount.getOldValue()));
        }
        else if (id == 24)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_Overdraft_TOD_no.getOldValue())==null || ((java.math.BigDecimal)field_v_Overdraft_TOD_no.getOldValue())==0 ? 0.00 :((java.math.BigDecimal)field_v_Overdraft_TOD_no.getOldValue()));
        }
        else if (id == 25)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_Overdraft_TOD_amount.getOldValue())==null || ((java.math.BigDecimal)field_v_Overdraft_TOD_amount.getOldValue())==0 ? 0.00 :((java.math.BigDecimal)field_v_Overdraft_TOD_amount.getOldValue()));
        }
        else if (id == 26)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_Staff_Loan_TOD_limit_amount.getOldValue())==null || ((java.math.BigDecimal)field_v_Staff_Loan_TOD_limit_amount.getOldValue())==0 ? 0.00 : ((java.math.BigDecimal)field_v_Staff_Loan_TOD_limit_amount.getOldValue()));
        }
        else if (id == 27)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_Staff_Loan_TOD_no.getOldValue())==null || ((java.math.BigDecimal)field_v_Staff_Loan_TOD_no.getOldValue())==0 ? 0.00 :((java.math.BigDecimal)field_v_Staff_Loan_TOD_no.getOldValue()));
        }
        else if (id == 28)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_Staff_Loan_TOD_amount.getOldValue())==null ||((java.math.BigDecimal)field_v_Staff_Loan_TOD_amount.getOldValue())== 0 ? 0.00 :((java.math.BigDecimal)field_v_Staff_Loan_TOD_amount.getOldValue()));
        }
        else if (id == 29)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_HP_TOD_limit_amount.getOldValue())==null ||((java.math.BigDecimal)field_v_HP_TOD_limit_amount.getOldValue())==0 ? 0.00 : ((java.math.BigDecimal)field_v_HP_TOD_limit_amount.getOldValue()));
        }
        else if (id == 30)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_HP_TOD_no.getOldValue())==null || ((java.math.BigDecimal)field_v_HP_TOD_no.getOldValue())== 0 ? 0.00 : ((java.math.BigDecimal)field_v_HP_TOD_no.getOldValue()));
        }
        else if (id == 31)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_HP_TOD_amount.getOldValue())==null || ((java.math.BigDecimal)field_v_HP_TOD_amount.getOldValue())== 0 ? 0.00 : ((java.math.BigDecimal)field_v_HP_TOD_amount.getOldValue()));
        }
        else if (id == 32)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_DemandLoanTOD_Limit_amt.getOldValue())));
        }
        else if (id == 33)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_DemandLoanTOD_Count.getOldValue()));
        }
        else if (id == 34)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_DemandLoanTOD_Amount.getOldValue())));
        }
        else if (id == 35)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Overdraft_TOD_Limit_Amt.getOldValue()));
        }
        else if (id == 36)
        {
            value = (java.math.BigDecimal)((((java.math.BigDecimal)variable_Overdraft_TOD_Count.getOldValue())));
        }
        else if (id == 37)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Overdraft_TOD_Amount.getOldValue()));
        }
        else if (id == 38)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_Staff_Loan_TOD_Limit_Amt.getOldValue())));
        }
        else if (id == 39)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Staff_Loan_TOD_Count.getOldValue()));
        }
        else if (id == 40)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_Staff_Loan_TOD_Amt.getOldValue())));
        }
        else if (id == 41)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_HP_TOD_Limit_Amt.getOldValue())));
        }
        else if (id == 42)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_HP_TOD_Count.getOldValue()));
        }
        else if (id == 43)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_HP_TOD_Amt.getOldValue())));
        }
        else if (id == 44)
        {
            value = (java.lang.String)(FinUtil.getImage(((java.lang.String)field_Image_Name.getOldValue()),((java.lang.String)parameter_FIN_IMG_PATH.getValue())));
        }
        else if (id == 45)
        {
            value = (java.lang.String)(((java.lang.String)field_Project_Bank_Name.getOldValue()));
        }
        else if (id == 46)
        {
            value = (java.lang.String)("Type By Loan and Advanced Position TOD Listing (All)");
        }
        else if (id == 47)
        {
            value = (java.lang.String)("As Date : " +((java.lang.String)parameter_P_vi_TranDate.getValue()));
        }
        else if (id == 48)
        {
            value = (java.lang.String)("Currency :" + ((java.lang.String)parameter_P_vi_currency.getValue()));
        }
        else if (id == 49)
        {
            value = (java.util.Date)(((java.util.Date)variable_TODAY.getOldValue()));
        }
        else if (id == 50)
        {
            value = (java.lang.String)(((java.lang.String)field_v_sol_desc.getOldValue()));
        }
        else if (id == 51)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_DemandLoanTOD_Limit_amt.getOldValue())));
        }
        else if (id == 52)
        {
            value = (java.lang.Integer)(((java.math.BigDecimal)variable_DemandLoanTOD_Count.getOldValue()));
        }
        else if (id == 53)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_DemandLoanTOD_Amount.getOldValue())));
        }
        else if (id == 54)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_HP_TOD_Limit_Amt.getOldValue())));
        }
        else if (id == 55)
        {
            value = (java.lang.Integer)(((java.math.BigDecimal)variable_HP_TOD_Count.getOldValue()));
        }
        else if (id == 56)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_HP_TOD_Amt.getOldValue())));
        }
        else if (id == 57)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_Staff_Loan_TOD_Limit_Amt.getOldValue())));
        }
        else if (id == 58)
        {
            value = (java.lang.Integer)(((java.math.BigDecimal)variable_Staff_Loan_TOD_Count.getOldValue()));
        }
        else if (id == 59)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_Staff_Loan_TOD_Amt.getOldValue())));
        }
        else if (id == 60)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_Overdraft_TOD_Limit_Amt.getOldValue())));
        }
        else if (id == 61)
        {
            value = (java.lang.Integer)(((java.math.BigDecimal)variable_Overdraft_TOD_Count.getOldValue()));
        }
        else if (id == 62)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_Overdraft_TOD_Amount.getOldValue())));
        }
        else if (id == 63)
        {
            value = (java.lang.Integer)(((java.lang.Integer)variable_REPORT_COUNT.getOldValue()));
        }
        else if (id == 64)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
        }
        else if (id == 65)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_GrandTotal_DemandLoanTOD_Limit_Amt.getOldValue()));
        }
        else if (id == 66)
        {
            value = (java.lang.Integer)(((java.math.BigDecimal)variable_GrandTotal_DemandLoanTOD_Count.getOldValue()));
        }
        else if (id == 67)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_GrandTotal_DemandLoanTOD_Amt.getOldValue()));
        }
        else if (id == 68)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_GrandTotal_HP_TOD_Limit_Amt.getOldValue()));
        }
        else if (id == 69)
        {
            value = (java.lang.Integer)(((java.math.BigDecimal)variable_GrandTotal_HP_TOD_Count.getOldValue()));
        }
        else if (id == 70)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_GrandTotal_HP_TOD_Amt.getOldValue()));
        }
        else if (id == 71)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_GrandTotal_Staff_Loan_TOD_Limit_Amt.getOldValue()));
        }
        else if (id == 72)
        {
            value = (java.lang.Integer)(((java.math.BigDecimal)variable_GrandTotal_Staff_Loan_TOD_Count.getOldValue()));
        }
        else if (id == 73)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_GrandTotal_Staff_Loan_TOD_Amt.getOldValue()));
        }
        else if (id == 74)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_GrandTotal_Overdraft_TOD_Limit_Amt.getOldValue())));
        }
        else if (id == 75)
        {
            value = (java.lang.Integer)(((java.math.BigDecimal)variable_GrandTotal_Overdraft_TOD_Count.getOldValue()));
        }
        else if (id == 76)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_GrandTotal_Overdraft_TOD_Amt.getOldValue())));
        }

        return value;
    }


    /**
     *
     */
    Object evaluateEstimated(int id)
    {
        Object value = null;

        if (id == 0)
        {
            value = (java.lang.String)("");
        }
        else if (id == 1)
        {
            value = (java.sql.Connection)(null);
        }
        else if (id == 2)
        {
            value = (java.lang.String)("../images");
        }
        else if (id == 3)
        {
            value = (java.lang.String)("../jrxml");
        }
        else if (id == 4)
        {
            value = (java.lang.String)("");
        }
        else if (id == 5)
        {
            value = (java.lang.String)("");
        }
        else if (id == 6)
        {
            value = (java.lang.String)("");
        }
        else if (id == 7)
        {
            value = (java.lang.String)("CUSTOM|FIN_TOD_LISTING.FIN_TOD_LISTING%3%CUSTOM::|where%vi_TranDate%=%((java.lang.String)parameter_P_vi_TranDate.getValue())%Parameter%Date::and%vi_currency%=%((java.lang.String)parameter_P_vi_currency.getValue())%Parameter%String::and%vi_branch_code%=%((java.lang.String)parameter_P_vi_branch_code.getValue())%Parameter%String::|INP_STR%1%java.lang.String%VARCHAR2::OUT_RETCODE%4%java.math.BigDecimal%NUMBER::OUT_REC%4%java.lang.String%VARCHAR2::|P_vi_TranDate%java.sql.Timestamp%10%!NULL!%Transaction Date@DBQUERY%NONE%java.sql.Timestamp!@!DEFAULT!@!8!@!10%CONSTANT%N%N::P_vi_currency%java.lang.String%100%!NULL!%Currency Code@DBQUERY%PRODUCT!@!Cntry_Crncy_List#@#N%java.lang.String!@!DEFAULT!@!0!@!100%CONSTANT%N%N::P_vi_branch_code%java.lang.String%100%!NULL!%Branch Code@DBQUERY%PRODUCT!@!SolID_List#@#N%java.lang.String!@!DEFAULT!@!0!@!100%CONSTANT%N%N::|{call CUSTOM.FIN_TOD_LISTING.FIN_TOD_LISTING( ((java.lang.String)parameter_FIN_INP_STR.getValue())  , ((java.math.BigDecimal)parameter_FIN_OUT_RETCODE.getValue()) , ((java.lang.String)parameter_FIN_OUT_REC.getValue()) ) } |{call CUSTOM.FIN_TOD_LISTING.FIN_TOD_LISTING( ((java.lang.String)parameter_FIN_INP_STR.getValue())  , ((java.math.BigDecimal)parameter_FIN_OUT_RETCODE.getValue()) , ((java.lang.String)parameter_FIN_OUT_REC.getValue()) ) } |false");
        }
        else if (id == 8)
        {
            value = (java.lang.String)(((java.lang.String)parameter_P_vi_TranDate.getValue()) + "!" +((java.lang.String)parameter_P_vi_currency.getValue()) + "!" +((java.lang.String)parameter_P_vi_branch_code.getValue()));
        }
        else if (id == 9)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 10)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 11)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 12)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 13)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 14)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 15)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 16)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 17)
        {
            value = (java.util.Date)(DateUtil.today());
        }
        else if (id == 18)
        {
            value = (java.util.Date)(DateUtil.today());
        }
        else if (id == 19)
        {
            value = (java.sql.Connection)(null);
        }
        else if (id == 20)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_Demand_Loan_TOD_limit_amount.getValue())==null || ((java.math.BigDecimal)field_v_Demand_Loan_TOD_limit_amount.getValue())==0 ? 0.00 :((java.math.BigDecimal)field_v_Demand_Loan_TOD_limit_amount.getValue()));
        }
        else if (id == 21)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_Demand_Loan_TOD_no.getValue())==null || ((java.math.BigDecimal)field_v_Demand_Loan_TOD_no.getValue())==0 ? 0.00 :((java.math.BigDecimal)field_v_Demand_Loan_TOD_no.getValue()));
        }
        else if (id == 22)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_Demand_Loan_TOD_amount.getValue())==null || ((java.math.BigDecimal)field_v_Demand_Loan_TOD_amount.getValue())==0 ? 0.00 :((java.math.BigDecimal)field_v_Demand_Loan_TOD_amount.getValue()));
        }
        else if (id == 23)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_Overdraft_TOD_limit_amount.getValue())==null ||((java.math.BigDecimal)field_v_Overdraft_TOD_limit_amount.getValue())==0 ? 0.00 : ((java.math.BigDecimal)field_v_Overdraft_TOD_limit_amount.getValue()));
        }
        else if (id == 24)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_Overdraft_TOD_no.getValue())==null || ((java.math.BigDecimal)field_v_Overdraft_TOD_no.getValue())==0 ? 0.00 :((java.math.BigDecimal)field_v_Overdraft_TOD_no.getValue()));
        }
        else if (id == 25)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_Overdraft_TOD_amount.getValue())==null || ((java.math.BigDecimal)field_v_Overdraft_TOD_amount.getValue())==0 ? 0.00 :((java.math.BigDecimal)field_v_Overdraft_TOD_amount.getValue()));
        }
        else if (id == 26)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_Staff_Loan_TOD_limit_amount.getValue())==null || ((java.math.BigDecimal)field_v_Staff_Loan_TOD_limit_amount.getValue())==0 ? 0.00 : ((java.math.BigDecimal)field_v_Staff_Loan_TOD_limit_amount.getValue()));
        }
        else if (id == 27)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_Staff_Loan_TOD_no.getValue())==null || ((java.math.BigDecimal)field_v_Staff_Loan_TOD_no.getValue())==0 ? 0.00 :((java.math.BigDecimal)field_v_Staff_Loan_TOD_no.getValue()));
        }
        else if (id == 28)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_Staff_Loan_TOD_amount.getValue())==null ||((java.math.BigDecimal)field_v_Staff_Loan_TOD_amount.getValue())== 0 ? 0.00 :((java.math.BigDecimal)field_v_Staff_Loan_TOD_amount.getValue()));
        }
        else if (id == 29)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_HP_TOD_limit_amount.getValue())==null ||((java.math.BigDecimal)field_v_HP_TOD_limit_amount.getValue())==0 ? 0.00 : ((java.math.BigDecimal)field_v_HP_TOD_limit_amount.getValue()));
        }
        else if (id == 30)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_HP_TOD_no.getValue())==null || ((java.math.BigDecimal)field_v_HP_TOD_no.getValue())== 0 ? 0.00 : ((java.math.BigDecimal)field_v_HP_TOD_no.getValue()));
        }
        else if (id == 31)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_HP_TOD_amount.getValue())==null || ((java.math.BigDecimal)field_v_HP_TOD_amount.getValue())== 0 ? 0.00 : ((java.math.BigDecimal)field_v_HP_TOD_amount.getValue()));
        }
        else if (id == 32)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_DemandLoanTOD_Limit_amt.getEstimatedValue())));
        }
        else if (id == 33)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_DemandLoanTOD_Count.getEstimatedValue()));
        }
        else if (id == 34)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_DemandLoanTOD_Amount.getEstimatedValue())));
        }
        else if (id == 35)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Overdraft_TOD_Limit_Amt.getEstimatedValue()));
        }
        else if (id == 36)
        {
            value = (java.math.BigDecimal)((((java.math.BigDecimal)variable_Overdraft_TOD_Count.getEstimatedValue())));
        }
        else if (id == 37)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Overdraft_TOD_Amount.getEstimatedValue()));
        }
        else if (id == 38)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_Staff_Loan_TOD_Limit_Amt.getEstimatedValue())));
        }
        else if (id == 39)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Staff_Loan_TOD_Count.getEstimatedValue()));
        }
        else if (id == 40)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_Staff_Loan_TOD_Amt.getEstimatedValue())));
        }
        else if (id == 41)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_HP_TOD_Limit_Amt.getEstimatedValue())));
        }
        else if (id == 42)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_HP_TOD_Count.getEstimatedValue()));
        }
        else if (id == 43)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_HP_TOD_Amt.getEstimatedValue())));
        }
        else if (id == 44)
        {
            value = (java.lang.String)(FinUtil.getImage(((java.lang.String)field_Image_Name.getValue()),((java.lang.String)parameter_FIN_IMG_PATH.getValue())));
        }
        else if (id == 45)
        {
            value = (java.lang.String)(((java.lang.String)field_Project_Bank_Name.getValue()));
        }
        else if (id == 46)
        {
            value = (java.lang.String)("Type By Loan and Advanced Position TOD Listing (All)");
        }
        else if (id == 47)
        {
            value = (java.lang.String)("As Date : " +((java.lang.String)parameter_P_vi_TranDate.getValue()));
        }
        else if (id == 48)
        {
            value = (java.lang.String)("Currency :" + ((java.lang.String)parameter_P_vi_currency.getValue()));
        }
        else if (id == 49)
        {
            value = (java.util.Date)(((java.util.Date)variable_TODAY.getEstimatedValue()));
        }
        else if (id == 50)
        {
            value = (java.lang.String)(((java.lang.String)field_v_sol_desc.getValue()));
        }
        else if (id == 51)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_DemandLoanTOD_Limit_amt.getEstimatedValue())));
        }
        else if (id == 52)
        {
            value = (java.lang.Integer)(((java.math.BigDecimal)variable_DemandLoanTOD_Count.getEstimatedValue()));
        }
        else if (id == 53)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_DemandLoanTOD_Amount.getEstimatedValue())));
        }
        else if (id == 54)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_HP_TOD_Limit_Amt.getEstimatedValue())));
        }
        else if (id == 55)
        {
            value = (java.lang.Integer)(((java.math.BigDecimal)variable_HP_TOD_Count.getEstimatedValue()));
        }
        else if (id == 56)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_HP_TOD_Amt.getEstimatedValue())));
        }
        else if (id == 57)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_Staff_Loan_TOD_Limit_Amt.getEstimatedValue())));
        }
        else if (id == 58)
        {
            value = (java.lang.Integer)(((java.math.BigDecimal)variable_Staff_Loan_TOD_Count.getEstimatedValue()));
        }
        else if (id == 59)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_Staff_Loan_TOD_Amt.getEstimatedValue())));
        }
        else if (id == 60)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_Overdraft_TOD_Limit_Amt.getEstimatedValue())));
        }
        else if (id == 61)
        {
            value = (java.lang.Integer)(((java.math.BigDecimal)variable_Overdraft_TOD_Count.getEstimatedValue()));
        }
        else if (id == 62)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_Overdraft_TOD_Amount.getEstimatedValue())));
        }
        else if (id == 63)
        {
            value = (java.lang.Integer)(((java.lang.Integer)variable_REPORT_COUNT.getEstimatedValue()));
        }
        else if (id == 64)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
        }
        else if (id == 65)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_GrandTotal_DemandLoanTOD_Limit_Amt.getEstimatedValue()));
        }
        else if (id == 66)
        {
            value = (java.lang.Integer)(((java.math.BigDecimal)variable_GrandTotal_DemandLoanTOD_Count.getEstimatedValue()));
        }
        else if (id == 67)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_GrandTotal_DemandLoanTOD_Amt.getEstimatedValue()));
        }
        else if (id == 68)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_GrandTotal_HP_TOD_Limit_Amt.getEstimatedValue()));
        }
        else if (id == 69)
        {
            value = (java.lang.Integer)(((java.math.BigDecimal)variable_GrandTotal_HP_TOD_Count.getEstimatedValue()));
        }
        else if (id == 70)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_GrandTotal_HP_TOD_Amt.getEstimatedValue()));
        }
        else if (id == 71)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_GrandTotal_Staff_Loan_TOD_Limit_Amt.getEstimatedValue()));
        }
        else if (id == 72)
        {
            value = (java.lang.Integer)(((java.math.BigDecimal)variable_GrandTotal_Staff_Loan_TOD_Count.getEstimatedValue()));
        }
        else if (id == 73)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_GrandTotal_Staff_Loan_TOD_Amt.getEstimatedValue()));
        }
        else if (id == 74)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_GrandTotal_Overdraft_TOD_Limit_Amt.getEstimatedValue())));
        }
        else if (id == 75)
        {
            value = (java.lang.Integer)(((java.math.BigDecimal)variable_GrandTotal_Overdraft_TOD_Count.getEstimatedValue()));
        }
        else if (id == 76)
        {
            value = (java.math.BigDecimal)(Math.abs(((java.math.BigDecimal)variable_GrandTotal_Overdraft_TOD_Amt.getEstimatedValue())));
        }

        return value;
    }


}
