/*
 * Generated by JasperReports - 12/7/17 3:33 PM
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import com.infy.finacle.finrpt.utils.*;
import net.sf.jasperreports.engine.*;
import com.infy.finacle.finrpt.ireport.*;
import java.util.*;
import com.infy.finacle.finrpt.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
class Daily_Remmitance_1512637419943_397834 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_REPORT_TIME_ZONE = null;
    private JRFillParameter parameter_FIN_REPORT_TYPE = null;
    private JRFillParameter parameter_REPORT_FILE_RESOLVER = null;
    private JRFillParameter parameter_FIN_OUT_REC = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_FIN_REPORT_DESC = null;
    private JRFillParameter parameter_FIN_SER_FINQUERY = null;
    private JRFillParameter parameter_FINRPT_DEFAULT_FORMAT = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_REPORT_URL_HANDLER_FACTORY = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillParameter parameter_REPORT_TEMPLATES = null;
    private JRFillParameter parameter_FIN_DB_CONN = null;
    private JRFillParameter parameter_FIN_REPOS_FILE = null;
    private JRFillParameter parameter_FIN_OUT_RETCODE = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_FIN_REPORT_TO = null;
    private JRFillParameter parameter_FIN_BANKREPOS_PARAM = null;
    private JRFillParameter parameter_FIN_IMG_PATH = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_FIN_REPOS_LIST = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_P_vi_EndDate = null;
    private JRFillParameter parameter_P_vi_StartDate = null;
    private JRFillParameter parameter_FIN_SESSION_ID = null;
    private JRFillParameter parameter_FIN_TEMPLATE_PATH = null;
    private JRFillParameter parameter_FIN_APP_UTIL = null;
    private JRFillParameter parameter_REPORT_FORMAT_FACTORY = null;
    private JRFillParameter parameter_FIN_JASPER_PATH = null;
    private JRFillParameter parameter_FIN_INP_STR = null;
    private JRFillParameter parameter_P_vi_BranchCode = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillField field_v_tran_id = null;
    private JRFillField field_BankAddress = null;
    private JRFillField field_Project_Bank_Name = null;
    private JRFillField field_BankFax = null;
    private JRFillField field_Project_Image_Name = null;
    private JRFillField field_BankName = null;
    private JRFillField field_FaxNo = null;
    private JRFillField field_Report_Code = null;
    private JRFillField field_Name = null;
    private JRFillField field_BranchName = null;
    private JRFillField field_Commission = null;
    private JRFillField field_Address = null;
    private JRFillField field_CashAmount = null;
    private JRFillField field_FaxAmount = null;
    private JRFillField field_BrShortName = null;
    private JRFillField field_NRC = null;
    private JRFillField field_BankPhone = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_InterBranch_COUNT = null;
    private JRFillVariable variable_BankName_COUNT = null;
    private JRFillVariable variable_BranchName_COUNT = null;
    private JRFillVariable variable_FIN_REPOSITORY = null;
    private JRFillVariable variable_TODAY = null;
    private JRFillVariable variable_FIN_DB_CONN = null;
    private JRFillVariable variable_Total = null;
    private JRFillVariable variable_BranchFaxTotal = null;
    private JRFillVariable variable_BranchCommissionTotal = null;
    private JRFillVariable variable_BranchCashTotal = null;
    private JRFillVariable variable_BranchTotal = null;
    private JRFillVariable variable_BankFaxTotal = null;
    private JRFillVariable variable_BankCommissionTotal = null;
    private JRFillVariable variable_BankCashTotal = null;
    private JRFillVariable variable_BankTotal = null;
    private JRFillVariable variable_BBFaxTotal = null;
    private JRFillVariable variable_BBCommissionTotal = null;
    private JRFillVariable variable_BBCashTotal = null;
    private JRFillVariable variable_BBTotal = null;
    private JRFillVariable variable_GrandFaxTotal = null;
    private JRFillVariable variable_GrandCommissionTotal = null;
    private JRFillVariable variable_GrandCashTotal = null;
    private JRFillVariable variable_GrandTotal = null;


    /**
     *
     */
    void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    void initParams(Map pm)
    {
        parameter_REPORT_TIME_ZONE = (JRFillParameter)pm.get("REPORT_TIME_ZONE");
        parameter_FIN_REPORT_TYPE = (JRFillParameter)pm.get("FIN_REPORT_TYPE");
        parameter_REPORT_FILE_RESOLVER = (JRFillParameter)pm.get("REPORT_FILE_RESOLVER");
        parameter_FIN_OUT_REC = (JRFillParameter)pm.get("FIN_OUT_REC");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_FIN_REPORT_DESC = (JRFillParameter)pm.get("FIN_REPORT_DESC");
        parameter_FIN_SER_FINQUERY = (JRFillParameter)pm.get("FIN_SER_FINQUERY");
        parameter_FINRPT_DEFAULT_FORMAT = (JRFillParameter)pm.get("FINRPT_DEFAULT_FORMAT");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_REPORT_URL_HANDLER_FACTORY = (JRFillParameter)pm.get("REPORT_URL_HANDLER_FACTORY");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
        parameter_REPORT_TEMPLATES = (JRFillParameter)pm.get("REPORT_TEMPLATES");
        parameter_FIN_DB_CONN = (JRFillParameter)pm.get("FIN_DB_CONN");
        parameter_FIN_REPOS_FILE = (JRFillParameter)pm.get("FIN_REPOS_FILE");
        parameter_FIN_OUT_RETCODE = (JRFillParameter)pm.get("FIN_OUT_RETCODE");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_FIN_REPORT_TO = (JRFillParameter)pm.get("FIN_REPORT_TO");
        parameter_FIN_BANKREPOS_PARAM = (JRFillParameter)pm.get("FIN_BANKREPOS_PARAM");
        parameter_FIN_IMG_PATH = (JRFillParameter)pm.get("FIN_IMG_PATH");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_FIN_REPOS_LIST = (JRFillParameter)pm.get("FIN_REPOS_LIST");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_P_vi_EndDate = (JRFillParameter)pm.get("P_vi_EndDate");
        parameter_P_vi_StartDate = (JRFillParameter)pm.get("P_vi_StartDate");
        parameter_FIN_SESSION_ID = (JRFillParameter)pm.get("FIN_SESSION_ID");
        parameter_FIN_TEMPLATE_PATH = (JRFillParameter)pm.get("FIN_TEMPLATE_PATH");
        parameter_FIN_APP_UTIL = (JRFillParameter)pm.get("FIN_APP_UTIL");
        parameter_REPORT_FORMAT_FACTORY = (JRFillParameter)pm.get("REPORT_FORMAT_FACTORY");
        parameter_FIN_JASPER_PATH = (JRFillParameter)pm.get("FIN_JASPER_PATH");
        parameter_FIN_INP_STR = (JRFillParameter)pm.get("FIN_INP_STR");
        parameter_P_vi_BranchCode = (JRFillParameter)pm.get("P_vi_BranchCode");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
    }


    /**
     *
     */
    void initFields(Map fm)
    {
        field_v_tran_id = (JRFillField)fm.get("v_tran_id");
        field_BankAddress = (JRFillField)fm.get("BankAddress");
        field_Project_Bank_Name = (JRFillField)fm.get("Project_Bank_Name");
        field_BankFax = (JRFillField)fm.get("BankFax");
        field_Project_Image_Name = (JRFillField)fm.get("Project_Image_Name");
        field_BankName = (JRFillField)fm.get("BankName");
        field_FaxNo = (JRFillField)fm.get("FaxNo");
        field_Report_Code = (JRFillField)fm.get("Report_Code");
        field_Name = (JRFillField)fm.get("Name");
        field_BranchName = (JRFillField)fm.get("BranchName");
        field_Commission = (JRFillField)fm.get("Commission");
        field_Address = (JRFillField)fm.get("Address");
        field_CashAmount = (JRFillField)fm.get("CashAmount");
        field_FaxAmount = (JRFillField)fm.get("FaxAmount");
        field_BrShortName = (JRFillField)fm.get("BrShortName");
        field_NRC = (JRFillField)fm.get("NRC");
        field_BankPhone = (JRFillField)fm.get("BankPhone");
    }


    /**
     *
     */
    void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
        variable_InterBranch_COUNT = (JRFillVariable)vm.get("InterBranch_COUNT");
        variable_BankName_COUNT = (JRFillVariable)vm.get("BankName_COUNT");
        variable_BranchName_COUNT = (JRFillVariable)vm.get("BranchName_COUNT");
        variable_FIN_REPOSITORY = (JRFillVariable)vm.get("FIN_REPOSITORY");
        variable_TODAY = (JRFillVariable)vm.get("TODAY");
        variable_FIN_DB_CONN = (JRFillVariable)vm.get("FIN_DB_CONN");
        variable_Total = (JRFillVariable)vm.get("Total");
        variable_BranchFaxTotal = (JRFillVariable)vm.get("BranchFaxTotal");
        variable_BranchCommissionTotal = (JRFillVariable)vm.get("BranchCommissionTotal");
        variable_BranchCashTotal = (JRFillVariable)vm.get("BranchCashTotal");
        variable_BranchTotal = (JRFillVariable)vm.get("BranchTotal");
        variable_BankFaxTotal = (JRFillVariable)vm.get("BankFaxTotal");
        variable_BankCommissionTotal = (JRFillVariable)vm.get("BankCommissionTotal");
        variable_BankCashTotal = (JRFillVariable)vm.get("BankCashTotal");
        variable_BankTotal = (JRFillVariable)vm.get("BankTotal");
        variable_BBFaxTotal = (JRFillVariable)vm.get("BBFaxTotal");
        variable_BBCommissionTotal = (JRFillVariable)vm.get("BBCommissionTotal");
        variable_BBCashTotal = (JRFillVariable)vm.get("BBCashTotal");
        variable_BBTotal = (JRFillVariable)vm.get("BBTotal");
        variable_GrandFaxTotal = (JRFillVariable)vm.get("GrandFaxTotal");
        variable_GrandCommissionTotal = (JRFillVariable)vm.get("GrandCommissionTotal");
        variable_GrandCashTotal = (JRFillVariable)vm.get("GrandCashTotal");
        variable_GrandTotal = (JRFillVariable)vm.get("GrandTotal");
    }


    /**
     *
     */
    Object evaluate(int id)
    {
        Object value = null;

        if (id == 0)
        {
            value = (java.lang.String)("");
        }
        else if (id == 1)
        {
            value = (java.sql.Connection)(null);
        }
        else if (id == 2)
        {
            value = (java.lang.String)("../images");
        }
        else if (id == 3)
        {
            value = (java.lang.String)("../jrxml");
        }
        else if (id == 4)
        {
            value = (java.lang.String)("");
        }
        else if (id == 5)
        {
            value = (java.lang.String)("");
        }
        else if (id == 6)
        {
            value = (java.lang.String)("");
        }
        else if (id == 7)
        {
            value = (java.lang.String)("CUSTOM|FIN_DAILY_DRAWING_REMMITTANCE.FIN_DAILY_DRAWING_REMMITTANCE%3%CUSTOM::|where%vi_StartDate%=%((java.lang.String)parameter_P_vi_StartDate.getValue())%Parameter%Date::and%vi_EndDate%=%((java.lang.String)parameter_P_vi_EndDate.getValue())%Parameter%Date::and%vi_BranchCode%=%((java.lang.String)parameter_P_vi_BranchCode.getValue())%Parameter%String::|INP_STR%1%java.lang.String%VARCHAR2::OUT_RETCODE%4%java.math.BigDecimal%NUMBER::OUT_REC%4%java.lang.String%VARCHAR2::|P_vi_StartDate%java.sql.Timestamp%10%!NULL!%Start_Date@DBQUERY%NONE%java.sql.Timestamp!@!DEFAULT!@!8!@!10%CONSTANT%N%N::P_vi_EndDate%java.sql.Timestamp%10%!NULL!%End_Date@DBQUERY%NONE%java.sql.Timestamp!@!DEFAULT!@!8!@!10%CONSTANT%N%N::P_vi_BranchCode%java.lang.String%100%!NULL!%Branch_code@DBQUERY%PRODUCT!@!SolID_List#@#N%java.lang.String!@!DEFAULT!@!0!@!100%CONSTANT%N%N::|{call CUSTOM.FIN_DAILY_DRAWING_REMMITTANCE.FIN_DAILY_DRAWING_REMMITTANCE( ((java.lang.String)parameter_FIN_INP_STR.getValue())  , ((java.math.BigDecimal)parameter_FIN_OUT_RETCODE.getValue()) , ((java.lang.String)parameter_FIN_OUT_REC.getValue()) ) } |{call CUSTOM.FIN_DAILY_DRAWING_REMMITTANCE.FIN_DAILY_DRAWING_REMMITTANCE( ((java.lang.String)parameter_FIN_INP_STR.getValue())  , ((java.math.BigDecimal)parameter_FIN_OUT_RETCODE.getValue()) , ((java.lang.String)parameter_FIN_OUT_REC.getValue()) ) } |false");
        }
        else if (id == 8)
        {
            value = (java.lang.String)(((java.lang.String)parameter_P_vi_StartDate.getValue()) + "!" +((java.lang.String)parameter_P_vi_EndDate.getValue()) + "!" +((java.lang.String)parameter_P_vi_BranchCode.getValue()));
        }
        else if (id == 9)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 10)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 11)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 12)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 13)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 14)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 15)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 16)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 17)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 18)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 19)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 20)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 21)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 22)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 23)
        {
            value = (java.util.Date)(DateUtil.today());
        }
        else if (id == 24)
        {
            value = (java.util.Date)(DateUtil.today());
        }
        else if (id == 25)
        {
            value = (java.sql.Connection)(null);
        }
        else if (id == 26)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_Commission.getValue())+((java.math.BigDecimal)field_FaxAmount.getValue())+((java.math.BigDecimal)field_CashAmount.getValue()));
        }
        else if (id == 27)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_FaxAmount.getValue()));
        }
        else if (id == 28)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_Commission.getValue()));
        }
        else if (id == 29)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CashAmount.getValue()));
        }
        else if (id == 30)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BranchFaxTotal.getValue())+((java.math.BigDecimal)variable_BranchCommissionTotal.getValue())+((java.math.BigDecimal)variable_BranchCashTotal.getValue()));
        }
        else if (id == 31)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_FaxAmount.getValue()));
        }
        else if (id == 32)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_Commission.getValue()));
        }
        else if (id == 33)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CashAmount.getValue()));
        }
        else if (id == 34)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BankCommissionTotal.getValue())+((java.math.BigDecimal)variable_BankFaxTotal.getValue())+((java.math.BigDecimal)variable_BankCashTotal.getValue()));
        }
        else if (id == 35)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_FaxAmount.getValue()));
        }
        else if (id == 36)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_Commission.getValue()));
        }
        else if (id == 37)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CashAmount.getValue()));
        }
        else if (id == 38)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BBFaxTotal.getValue())+((java.math.BigDecimal)variable_BBCommissionTotal.getValue())+((java.math.BigDecimal)variable_BBCashTotal.getValue()));
        }
        else if (id == 39)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_FaxAmount.getValue()));
        }
        else if (id == 40)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_Commission.getValue()));
        }
        else if (id == 41)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CashAmount.getValue()));
        }
        else if (id == 42)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_GrandFaxTotal.getValue())+((java.math.BigDecimal)variable_GrandCommissionTotal.getValue())+((java.math.BigDecimal)variable_GrandCashTotal.getValue()));
        }
        else if (id == 43)
        {
            value = (java.lang.Object)(((java.lang.String)field_Report_Code.getValue()));
        }
        else if (id == 44)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BBTotal.getValue()));
        }
        else if (id == 45)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BBCashTotal.getValue()));
        }
        else if (id == 46)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BBCommissionTotal.getValue()));
        }
        else if (id == 47)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BBFaxTotal.getValue()));
        }
        else if (id == 48)
        {
            value = (java.lang.String)(((java.lang.String)field_Report_Code.getValue()).equals("REMIT") ? "Inter Branch Total" : "Inter Bank Total");
        }
        else if (id == 49)
        {
            value = (java.lang.Object)(((java.lang.String)field_BankName.getValue()));
        }
        else if (id == 50)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BankTotal.getValue()));
        }
        else if (id == 51)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BankCashTotal.getValue()));
        }
        else if (id == 52)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BankCommissionTotal.getValue()));
        }
        else if (id == 53)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BankFaxTotal.getValue()));
        }
        else if (id == 54)
        {
            value = (java.lang.String)(" Sub Total For " + ((java.lang.String)field_BankName.getValue()));
        }
        else if (id == 55)
        {
            value = (java.lang.Object)(((java.lang.String)field_BrShortName.getValue()));
        }
        else if (id == 56)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BranchTotal.getValue()));
        }
        else if (id == 57)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BranchCashTotal.getValue()));
        }
        else if (id == 58)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BranchCommissionTotal.getValue()));
        }
        else if (id == 59)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BranchFaxTotal.getValue()));
        }
        else if (id == 60)
        {
            value = (java.lang.String)(((java.lang.String)field_BrShortName.getValue()) + " Total");
        }
        else if (id == 61)
        {
            value = (java.lang.String)(((java.lang.String)field_Project_Bank_Name.getValue())+"(" +((java.lang.String)field_BranchName.getValue()) + ")");
        }
        else if (id == 62)
        {
            value = (java.lang.String)(((java.lang.String)field_BankPhone.getValue()));
        }
        else if (id == 63)
        {
            value = (java.lang.String)(((java.lang.String)field_BankFax.getValue()));
        }
        else if (id == 64)
        {
            value = (java.lang.String)(((java.lang.String)field_BankAddress.getValue()));
        }
        else if (id == 65)
        {
            value = (java.lang.String)(FinUtil.getImage(((java.lang.String)field_Project_Image_Name.getValue()), ((java.lang.String)parameter_FIN_IMG_PATH.getValue())));
        }
        else if (id == 66)
        {
            value = (java.util.Date)(((java.util.Date)variable_TODAY.getValue()));
        }
        else if (id == 67)
        {
            value = (java.lang.String)("Daily Drawing Remittance Listing  From "+((java.lang.String)parameter_P_vi_StartDate.getValue())+" To "+((java.lang.String)parameter_P_vi_EndDate.getValue()));
        }
        else if (id == 68)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getValue()));
        }
        else if (id == 69)
        {
            value = (java.lang.String)(((java.lang.String)field_FaxNo.getValue()));
        }
        else if (id == 70)
        {
            value = (java.lang.String)(((java.lang.String)field_Name.getValue())+","+((java.lang.String)field_NRC.getValue()));
        }
        else if (id == 71)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CashAmount.getValue()));
        }
        else if (id == 72)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_FaxAmount.getValue()));
        }
        else if (id == 73)
        {
            value = (java.lang.String)(((java.lang.String)field_BrShortName.getValue()));
        }
        else if (id == 74)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_Commission.getValue()));
        }
        else if (id == 75)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Total.getValue()));
        }
        else if (id == 76)
        {
            value = (java.lang.String)(((java.lang.String)field_v_tran_id.getValue()));
        }
        else if (id == 77)
        {
            value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
        }
        else if (id == 78)
        {
            value = (java.lang.String)(null);
        }
        else if (id == 79)
        {
            value = (java.lang.String)("Total ( " + ((java.lang.Integer)variable_REPORT_COUNT.getValue()) + " ) Records Listed.");
        }
        else if (id == 80)
        {
            value = (java.lang.String)("Grand Total");
        }
        else if (id == 81)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_GrandFaxTotal.getValue()));
        }
        else if (id == 82)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_GrandCommissionTotal.getValue()));
        }
        else if (id == 83)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_GrandCashTotal.getValue()));
        }
        else if (id == 84)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_GrandTotal.getValue()));
        }

        return value;
    }


    /**
     *
     */
    Object evaluateOld(int id)
    {
        Object value = null;

        if (id == 0)
        {
            value = (java.lang.String)("");
        }
        else if (id == 1)
        {
            value = (java.sql.Connection)(null);
        }
        else if (id == 2)
        {
            value = (java.lang.String)("../images");
        }
        else if (id == 3)
        {
            value = (java.lang.String)("../jrxml");
        }
        else if (id == 4)
        {
            value = (java.lang.String)("");
        }
        else if (id == 5)
        {
            value = (java.lang.String)("");
        }
        else if (id == 6)
        {
            value = (java.lang.String)("");
        }
        else if (id == 7)
        {
            value = (java.lang.String)("CUSTOM|FIN_DAILY_DRAWING_REMMITTANCE.FIN_DAILY_DRAWING_REMMITTANCE%3%CUSTOM::|where%vi_StartDate%=%((java.lang.String)parameter_P_vi_StartDate.getValue())%Parameter%Date::and%vi_EndDate%=%((java.lang.String)parameter_P_vi_EndDate.getValue())%Parameter%Date::and%vi_BranchCode%=%((java.lang.String)parameter_P_vi_BranchCode.getValue())%Parameter%String::|INP_STR%1%java.lang.String%VARCHAR2::OUT_RETCODE%4%java.math.BigDecimal%NUMBER::OUT_REC%4%java.lang.String%VARCHAR2::|P_vi_StartDate%java.sql.Timestamp%10%!NULL!%Start_Date@DBQUERY%NONE%java.sql.Timestamp!@!DEFAULT!@!8!@!10%CONSTANT%N%N::P_vi_EndDate%java.sql.Timestamp%10%!NULL!%End_Date@DBQUERY%NONE%java.sql.Timestamp!@!DEFAULT!@!8!@!10%CONSTANT%N%N::P_vi_BranchCode%java.lang.String%100%!NULL!%Branch_code@DBQUERY%PRODUCT!@!SolID_List#@#N%java.lang.String!@!DEFAULT!@!0!@!100%CONSTANT%N%N::|{call CUSTOM.FIN_DAILY_DRAWING_REMMITTANCE.FIN_DAILY_DRAWING_REMMITTANCE( ((java.lang.String)parameter_FIN_INP_STR.getValue())  , ((java.math.BigDecimal)parameter_FIN_OUT_RETCODE.getValue()) , ((java.lang.String)parameter_FIN_OUT_REC.getValue()) ) } |{call CUSTOM.FIN_DAILY_DRAWING_REMMITTANCE.FIN_DAILY_DRAWING_REMMITTANCE( ((java.lang.String)parameter_FIN_INP_STR.getValue())  , ((java.math.BigDecimal)parameter_FIN_OUT_RETCODE.getValue()) , ((java.lang.String)parameter_FIN_OUT_REC.getValue()) ) } |false");
        }
        else if (id == 8)
        {
            value = (java.lang.String)(((java.lang.String)parameter_P_vi_StartDate.getValue()) + "!" +((java.lang.String)parameter_P_vi_EndDate.getValue()) + "!" +((java.lang.String)parameter_P_vi_BranchCode.getValue()));
        }
        else if (id == 9)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 10)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 11)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 12)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 13)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 14)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 15)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 16)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 17)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 18)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 19)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 20)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 21)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 22)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 23)
        {
            value = (java.util.Date)(DateUtil.today());
        }
        else if (id == 24)
        {
            value = (java.util.Date)(DateUtil.today());
        }
        else if (id == 25)
        {
            value = (java.sql.Connection)(null);
        }
        else if (id == 26)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_Commission.getOldValue())+((java.math.BigDecimal)field_FaxAmount.getOldValue())+((java.math.BigDecimal)field_CashAmount.getOldValue()));
        }
        else if (id == 27)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_FaxAmount.getOldValue()));
        }
        else if (id == 28)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_Commission.getOldValue()));
        }
        else if (id == 29)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CashAmount.getOldValue()));
        }
        else if (id == 30)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BranchFaxTotal.getOldValue())+((java.math.BigDecimal)variable_BranchCommissionTotal.getOldValue())+((java.math.BigDecimal)variable_BranchCashTotal.getOldValue()));
        }
        else if (id == 31)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_FaxAmount.getOldValue()));
        }
        else if (id == 32)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_Commission.getOldValue()));
        }
        else if (id == 33)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CashAmount.getOldValue()));
        }
        else if (id == 34)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BankCommissionTotal.getOldValue())+((java.math.BigDecimal)variable_BankFaxTotal.getOldValue())+((java.math.BigDecimal)variable_BankCashTotal.getOldValue()));
        }
        else if (id == 35)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_FaxAmount.getOldValue()));
        }
        else if (id == 36)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_Commission.getOldValue()));
        }
        else if (id == 37)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CashAmount.getOldValue()));
        }
        else if (id == 38)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BBFaxTotal.getOldValue())+((java.math.BigDecimal)variable_BBCommissionTotal.getOldValue())+((java.math.BigDecimal)variable_BBCashTotal.getOldValue()));
        }
        else if (id == 39)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_FaxAmount.getOldValue()));
        }
        else if (id == 40)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_Commission.getOldValue()));
        }
        else if (id == 41)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CashAmount.getOldValue()));
        }
        else if (id == 42)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_GrandFaxTotal.getOldValue())+((java.math.BigDecimal)variable_GrandCommissionTotal.getOldValue())+((java.math.BigDecimal)variable_GrandCashTotal.getOldValue()));
        }
        else if (id == 43)
        {
            value = (java.lang.Object)(((java.lang.String)field_Report_Code.getOldValue()));
        }
        else if (id == 44)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BBTotal.getOldValue()));
        }
        else if (id == 45)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BBCashTotal.getOldValue()));
        }
        else if (id == 46)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BBCommissionTotal.getOldValue()));
        }
        else if (id == 47)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BBFaxTotal.getOldValue()));
        }
        else if (id == 48)
        {
            value = (java.lang.String)(((java.lang.String)field_Report_Code.getOldValue()).equals("REMIT") ? "Inter Branch Total" : "Inter Bank Total");
        }
        else if (id == 49)
        {
            value = (java.lang.Object)(((java.lang.String)field_BankName.getOldValue()));
        }
        else if (id == 50)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BankTotal.getOldValue()));
        }
        else if (id == 51)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BankCashTotal.getOldValue()));
        }
        else if (id == 52)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BankCommissionTotal.getOldValue()));
        }
        else if (id == 53)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BankFaxTotal.getOldValue()));
        }
        else if (id == 54)
        {
            value = (java.lang.String)(" Sub Total For " + ((java.lang.String)field_BankName.getOldValue()));
        }
        else if (id == 55)
        {
            value = (java.lang.Object)(((java.lang.String)field_BrShortName.getOldValue()));
        }
        else if (id == 56)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BranchTotal.getOldValue()));
        }
        else if (id == 57)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BranchCashTotal.getOldValue()));
        }
        else if (id == 58)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BranchCommissionTotal.getOldValue()));
        }
        else if (id == 59)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BranchFaxTotal.getOldValue()));
        }
        else if (id == 60)
        {
            value = (java.lang.String)(((java.lang.String)field_BrShortName.getOldValue()) + " Total");
        }
        else if (id == 61)
        {
            value = (java.lang.String)(((java.lang.String)field_Project_Bank_Name.getOldValue())+"(" +((java.lang.String)field_BranchName.getOldValue()) + ")");
        }
        else if (id == 62)
        {
            value = (java.lang.String)(((java.lang.String)field_BankPhone.getOldValue()));
        }
        else if (id == 63)
        {
            value = (java.lang.String)(((java.lang.String)field_BankFax.getOldValue()));
        }
        else if (id == 64)
        {
            value = (java.lang.String)(((java.lang.String)field_BankAddress.getOldValue()));
        }
        else if (id == 65)
        {
            value = (java.lang.String)(FinUtil.getImage(((java.lang.String)field_Project_Image_Name.getOldValue()), ((java.lang.String)parameter_FIN_IMG_PATH.getValue())));
        }
        else if (id == 66)
        {
            value = (java.util.Date)(((java.util.Date)variable_TODAY.getOldValue()));
        }
        else if (id == 67)
        {
            value = (java.lang.String)("Daily Drawing Remittance Listing  From "+((java.lang.String)parameter_P_vi_StartDate.getValue())+" To "+((java.lang.String)parameter_P_vi_EndDate.getValue()));
        }
        else if (id == 68)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getOldValue()));
        }
        else if (id == 69)
        {
            value = (java.lang.String)(((java.lang.String)field_FaxNo.getOldValue()));
        }
        else if (id == 70)
        {
            value = (java.lang.String)(((java.lang.String)field_Name.getOldValue())+","+((java.lang.String)field_NRC.getOldValue()));
        }
        else if (id == 71)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CashAmount.getOldValue()));
        }
        else if (id == 72)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_FaxAmount.getOldValue()));
        }
        else if (id == 73)
        {
            value = (java.lang.String)(((java.lang.String)field_BrShortName.getOldValue()));
        }
        else if (id == 74)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_Commission.getOldValue()));
        }
        else if (id == 75)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Total.getOldValue()));
        }
        else if (id == 76)
        {
            value = (java.lang.String)(((java.lang.String)field_v_tran_id.getOldValue()));
        }
        else if (id == 77)
        {
            value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
        }
        else if (id == 78)
        {
            value = (java.lang.String)(null);
        }
        else if (id == 79)
        {
            value = (java.lang.String)("Total ( " + ((java.lang.Integer)variable_REPORT_COUNT.getOldValue()) + " ) Records Listed.");
        }
        else if (id == 80)
        {
            value = (java.lang.String)("Grand Total");
        }
        else if (id == 81)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_GrandFaxTotal.getOldValue()));
        }
        else if (id == 82)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_GrandCommissionTotal.getOldValue()));
        }
        else if (id == 83)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_GrandCashTotal.getOldValue()));
        }
        else if (id == 84)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_GrandTotal.getOldValue()));
        }

        return value;
    }


    /**
     *
     */
    Object evaluateEstimated(int id)
    {
        Object value = null;

        if (id == 0)
        {
            value = (java.lang.String)("");
        }
        else if (id == 1)
        {
            value = (java.sql.Connection)(null);
        }
        else if (id == 2)
        {
            value = (java.lang.String)("../images");
        }
        else if (id == 3)
        {
            value = (java.lang.String)("../jrxml");
        }
        else if (id == 4)
        {
            value = (java.lang.String)("");
        }
        else if (id == 5)
        {
            value = (java.lang.String)("");
        }
        else if (id == 6)
        {
            value = (java.lang.String)("");
        }
        else if (id == 7)
        {
            value = (java.lang.String)("CUSTOM|FIN_DAILY_DRAWING_REMMITTANCE.FIN_DAILY_DRAWING_REMMITTANCE%3%CUSTOM::|where%vi_StartDate%=%((java.lang.String)parameter_P_vi_StartDate.getValue())%Parameter%Date::and%vi_EndDate%=%((java.lang.String)parameter_P_vi_EndDate.getValue())%Parameter%Date::and%vi_BranchCode%=%((java.lang.String)parameter_P_vi_BranchCode.getValue())%Parameter%String::|INP_STR%1%java.lang.String%VARCHAR2::OUT_RETCODE%4%java.math.BigDecimal%NUMBER::OUT_REC%4%java.lang.String%VARCHAR2::|P_vi_StartDate%java.sql.Timestamp%10%!NULL!%Start_Date@DBQUERY%NONE%java.sql.Timestamp!@!DEFAULT!@!8!@!10%CONSTANT%N%N::P_vi_EndDate%java.sql.Timestamp%10%!NULL!%End_Date@DBQUERY%NONE%java.sql.Timestamp!@!DEFAULT!@!8!@!10%CONSTANT%N%N::P_vi_BranchCode%java.lang.String%100%!NULL!%Branch_code@DBQUERY%PRODUCT!@!SolID_List#@#N%java.lang.String!@!DEFAULT!@!0!@!100%CONSTANT%N%N::|{call CUSTOM.FIN_DAILY_DRAWING_REMMITTANCE.FIN_DAILY_DRAWING_REMMITTANCE( ((java.lang.String)parameter_FIN_INP_STR.getValue())  , ((java.math.BigDecimal)parameter_FIN_OUT_RETCODE.getValue()) , ((java.lang.String)parameter_FIN_OUT_REC.getValue()) ) } |{call CUSTOM.FIN_DAILY_DRAWING_REMMITTANCE.FIN_DAILY_DRAWING_REMMITTANCE( ((java.lang.String)parameter_FIN_INP_STR.getValue())  , ((java.math.BigDecimal)parameter_FIN_OUT_RETCODE.getValue()) , ((java.lang.String)parameter_FIN_OUT_REC.getValue()) ) } |false");
        }
        else if (id == 8)
        {
            value = (java.lang.String)(((java.lang.String)parameter_P_vi_StartDate.getValue()) + "!" +((java.lang.String)parameter_P_vi_EndDate.getValue()) + "!" +((java.lang.String)parameter_P_vi_BranchCode.getValue()));
        }
        else if (id == 9)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 10)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 11)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 12)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 13)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 14)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 15)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 16)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 17)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 18)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 19)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 20)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 21)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 22)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 23)
        {
            value = (java.util.Date)(DateUtil.today());
        }
        else if (id == 24)
        {
            value = (java.util.Date)(DateUtil.today());
        }
        else if (id == 25)
        {
            value = (java.sql.Connection)(null);
        }
        else if (id == 26)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_Commission.getValue())+((java.math.BigDecimal)field_FaxAmount.getValue())+((java.math.BigDecimal)field_CashAmount.getValue()));
        }
        else if (id == 27)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_FaxAmount.getValue()));
        }
        else if (id == 28)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_Commission.getValue()));
        }
        else if (id == 29)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CashAmount.getValue()));
        }
        else if (id == 30)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BranchFaxTotal.getEstimatedValue())+((java.math.BigDecimal)variable_BranchCommissionTotal.getEstimatedValue())+((java.math.BigDecimal)variable_BranchCashTotal.getEstimatedValue()));
        }
        else if (id == 31)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_FaxAmount.getValue()));
        }
        else if (id == 32)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_Commission.getValue()));
        }
        else if (id == 33)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CashAmount.getValue()));
        }
        else if (id == 34)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BankCommissionTotal.getEstimatedValue())+((java.math.BigDecimal)variable_BankFaxTotal.getEstimatedValue())+((java.math.BigDecimal)variable_BankCashTotal.getEstimatedValue()));
        }
        else if (id == 35)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_FaxAmount.getValue()));
        }
        else if (id == 36)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_Commission.getValue()));
        }
        else if (id == 37)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CashAmount.getValue()));
        }
        else if (id == 38)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BBFaxTotal.getEstimatedValue())+((java.math.BigDecimal)variable_BBCommissionTotal.getEstimatedValue())+((java.math.BigDecimal)variable_BBCashTotal.getEstimatedValue()));
        }
        else if (id == 39)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_FaxAmount.getValue()));
        }
        else if (id == 40)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_Commission.getValue()));
        }
        else if (id == 41)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CashAmount.getValue()));
        }
        else if (id == 42)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_GrandFaxTotal.getEstimatedValue())+((java.math.BigDecimal)variable_GrandCommissionTotal.getEstimatedValue())+((java.math.BigDecimal)variable_GrandCashTotal.getEstimatedValue()));
        }
        else if (id == 43)
        {
            value = (java.lang.Object)(((java.lang.String)field_Report_Code.getValue()));
        }
        else if (id == 44)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BBTotal.getEstimatedValue()));
        }
        else if (id == 45)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BBCashTotal.getEstimatedValue()));
        }
        else if (id == 46)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BBCommissionTotal.getEstimatedValue()));
        }
        else if (id == 47)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BBFaxTotal.getEstimatedValue()));
        }
        else if (id == 48)
        {
            value = (java.lang.String)(((java.lang.String)field_Report_Code.getValue()).equals("REMIT") ? "Inter Branch Total" : "Inter Bank Total");
        }
        else if (id == 49)
        {
            value = (java.lang.Object)(((java.lang.String)field_BankName.getValue()));
        }
        else if (id == 50)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BankTotal.getEstimatedValue()));
        }
        else if (id == 51)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BankCashTotal.getEstimatedValue()));
        }
        else if (id == 52)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BankCommissionTotal.getEstimatedValue()));
        }
        else if (id == 53)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BankFaxTotal.getEstimatedValue()));
        }
        else if (id == 54)
        {
            value = (java.lang.String)(" Sub Total For " + ((java.lang.String)field_BankName.getValue()));
        }
        else if (id == 55)
        {
            value = (java.lang.Object)(((java.lang.String)field_BrShortName.getValue()));
        }
        else if (id == 56)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BranchTotal.getEstimatedValue()));
        }
        else if (id == 57)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BranchCashTotal.getEstimatedValue()));
        }
        else if (id == 58)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BranchCommissionTotal.getEstimatedValue()));
        }
        else if (id == 59)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_BranchFaxTotal.getEstimatedValue()));
        }
        else if (id == 60)
        {
            value = (java.lang.String)(((java.lang.String)field_BrShortName.getValue()) + " Total");
        }
        else if (id == 61)
        {
            value = (java.lang.String)(((java.lang.String)field_Project_Bank_Name.getValue())+"(" +((java.lang.String)field_BranchName.getValue()) + ")");
        }
        else if (id == 62)
        {
            value = (java.lang.String)(((java.lang.String)field_BankPhone.getValue()));
        }
        else if (id == 63)
        {
            value = (java.lang.String)(((java.lang.String)field_BankFax.getValue()));
        }
        else if (id == 64)
        {
            value = (java.lang.String)(((java.lang.String)field_BankAddress.getValue()));
        }
        else if (id == 65)
        {
            value = (java.lang.String)(FinUtil.getImage(((java.lang.String)field_Project_Image_Name.getValue()), ((java.lang.String)parameter_FIN_IMG_PATH.getValue())));
        }
        else if (id == 66)
        {
            value = (java.util.Date)(((java.util.Date)variable_TODAY.getEstimatedValue()));
        }
        else if (id == 67)
        {
            value = (java.lang.String)("Daily Drawing Remittance Listing  From "+((java.lang.String)parameter_P_vi_StartDate.getValue())+" To "+((java.lang.String)parameter_P_vi_EndDate.getValue()));
        }
        else if (id == 68)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getEstimatedValue()));
        }
        else if (id == 69)
        {
            value = (java.lang.String)(((java.lang.String)field_FaxNo.getValue()));
        }
        else if (id == 70)
        {
            value = (java.lang.String)(((java.lang.String)field_Name.getValue())+","+((java.lang.String)field_NRC.getValue()));
        }
        else if (id == 71)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_CashAmount.getValue()));
        }
        else if (id == 72)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_FaxAmount.getValue()));
        }
        else if (id == 73)
        {
            value = (java.lang.String)(((java.lang.String)field_BrShortName.getValue()));
        }
        else if (id == 74)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_Commission.getValue()));
        }
        else if (id == 75)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Total.getEstimatedValue()));
        }
        else if (id == 76)
        {
            value = (java.lang.String)(((java.lang.String)field_v_tran_id.getValue()));
        }
        else if (id == 77)
        {
            value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
        }
        else if (id == 78)
        {
            value = (java.lang.String)(null);
        }
        else if (id == 79)
        {
            value = (java.lang.String)("Total ( " + ((java.lang.Integer)variable_REPORT_COUNT.getEstimatedValue()) + " ) Records Listed.");
        }
        else if (id == 80)
        {
            value = (java.lang.String)("Grand Total");
        }
        else if (id == 81)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_GrandFaxTotal.getEstimatedValue()));
        }
        else if (id == 82)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_GrandCommissionTotal.getEstimatedValue()));
        }
        else if (id == 83)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_GrandCashTotal.getEstimatedValue()));
        }
        else if (id == 84)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_GrandTotal.getEstimatedValue()));
        }

        return value;
    }


}
