/*
 * Generated by JasperReports - 12/6/17 6:01 PM
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import com.infy.finacle.finrpt.utils.*;
import net.sf.jasperreports.engine.*;
import com.infy.finacle.finrpt.ireport.*;
import java.util.*;
import com.infy.finacle.finrpt.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
class Untitled_report_1_1512559874077_874940 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_P_vi_date = null;
    private JRFillParameter parameter_REPORT_TIME_ZONE = null;
    private JRFillParameter parameter_FIN_REPORT_TYPE = null;
    private JRFillParameter parameter_REPORT_FILE_RESOLVER = null;
    private JRFillParameter parameter_FIN_OUT_REC = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_FIN_REPORT_DESC = null;
    private JRFillParameter parameter_FIN_SER_FINQUERY = null;
    private JRFillParameter parameter_FINRPT_DEFAULT_FORMAT = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_REPORT_URL_HANDLER_FACTORY = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_P_vi_loanType = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillParameter parameter_REPORT_TEMPLATES = null;
    private JRFillParameter parameter_FIN_DB_CONN = null;
    private JRFillParameter parameter_FIN_OUT_RETCODE = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_FIN_REPORT_TO = null;
    private JRFillParameter parameter_FIN_IMG_PATH = null;
    private JRFillParameter parameter_FIN_BANKREPOS_PARAM = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_P_vi_branchId = null;
    private JRFillParameter parameter_P_vi_SchemeType = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_FIN_SESSION_ID = null;
    private JRFillParameter parameter_FIN_TEMPLATE_PATH = null;
    private JRFillParameter parameter_FIN_APP_UTIL = null;
    private JRFillParameter parameter_REPORT_FORMAT_FACTORY = null;
    private JRFillParameter parameter_P_vi_SchemeCode = null;
    private JRFillParameter parameter_FIN_JASPER_PATH = null;
    private JRFillParameter parameter_FIN_INP_STR = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillField field_v_BankFax = null;
    private JRFillField field_Project_Bank_Name = null;
    private JRFillField field_Project_Image_Name = null;
    private JRFillField field_v_dealerID = null;
    private JRFillField field_v_Acc_Name = null;
    private JRFillField field_v_HP_No = null;
    private JRFillField field_v_total_paidamt = null;
    private JRFillField field_v_AccountNo = null;
    private JRFillField field_v_BankPhone = null;
    private JRFillField field_v_startamount = null;
    private JRFillField field_v_BranchName = null;
    private JRFillField field_v_BankAddress = null;
    private JRFillField field_v_Payment_Term = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_sub_dealer_id_COUNT = null;
    private JRFillVariable variable_Sub_total_COUNT = null;
    private JRFillVariable variable_TODAY = null;
    private JRFillVariable variable_FIN_DB_CONN = null;
    private JRFillVariable variable_Br_name_check = null;
    private JRFillVariable variable_Schm = null;
    private JRFillVariable variable_check_var = null;
    private JRFillVariable variable_sub_start_amt = null;
    private JRFillVariable variable_sub_tot_paidamt = null;
    private JRFillVariable variable_Grand_Total_Start_Amount = null;
    private JRFillVariable variable_Grand_total_paid_amt = null;


    /**
     *
     */
    void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    void initParams(Map pm)
    {
        parameter_P_vi_date = (JRFillParameter)pm.get("P_vi_date");
        parameter_REPORT_TIME_ZONE = (JRFillParameter)pm.get("REPORT_TIME_ZONE");
        parameter_FIN_REPORT_TYPE = (JRFillParameter)pm.get("FIN_REPORT_TYPE");
        parameter_REPORT_FILE_RESOLVER = (JRFillParameter)pm.get("REPORT_FILE_RESOLVER");
        parameter_FIN_OUT_REC = (JRFillParameter)pm.get("FIN_OUT_REC");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_FIN_REPORT_DESC = (JRFillParameter)pm.get("FIN_REPORT_DESC");
        parameter_FIN_SER_FINQUERY = (JRFillParameter)pm.get("FIN_SER_FINQUERY");
        parameter_FINRPT_DEFAULT_FORMAT = (JRFillParameter)pm.get("FINRPT_DEFAULT_FORMAT");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_REPORT_URL_HANDLER_FACTORY = (JRFillParameter)pm.get("REPORT_URL_HANDLER_FACTORY");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_P_vi_loanType = (JRFillParameter)pm.get("P_vi_loanType");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
        parameter_REPORT_TEMPLATES = (JRFillParameter)pm.get("REPORT_TEMPLATES");
        parameter_FIN_DB_CONN = (JRFillParameter)pm.get("FIN_DB_CONN");
        parameter_FIN_OUT_RETCODE = (JRFillParameter)pm.get("FIN_OUT_RETCODE");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_FIN_REPORT_TO = (JRFillParameter)pm.get("FIN_REPORT_TO");
        parameter_FIN_IMG_PATH = (JRFillParameter)pm.get("FIN_IMG_PATH");
        parameter_FIN_BANKREPOS_PARAM = (JRFillParameter)pm.get("FIN_BANKREPOS_PARAM");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_P_vi_branchId = (JRFillParameter)pm.get("P_vi_branchId");
        parameter_P_vi_SchemeType = (JRFillParameter)pm.get("P_vi_SchemeType");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_FIN_SESSION_ID = (JRFillParameter)pm.get("FIN_SESSION_ID");
        parameter_FIN_TEMPLATE_PATH = (JRFillParameter)pm.get("FIN_TEMPLATE_PATH");
        parameter_FIN_APP_UTIL = (JRFillParameter)pm.get("FIN_APP_UTIL");
        parameter_REPORT_FORMAT_FACTORY = (JRFillParameter)pm.get("REPORT_FORMAT_FACTORY");
        parameter_P_vi_SchemeCode = (JRFillParameter)pm.get("P_vi_SchemeCode");
        parameter_FIN_JASPER_PATH = (JRFillParameter)pm.get("FIN_JASPER_PATH");
        parameter_FIN_INP_STR = (JRFillParameter)pm.get("FIN_INP_STR");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
    }


    /**
     *
     */
    void initFields(Map fm)
    {
        field_v_BankFax = (JRFillField)fm.get("v_BankFax");
        field_Project_Bank_Name = (JRFillField)fm.get("Project_Bank_Name");
        field_Project_Image_Name = (JRFillField)fm.get("Project_Image_Name");
        field_v_dealerID = (JRFillField)fm.get("v_dealerID");
        field_v_Acc_Name = (JRFillField)fm.get("v_Acc_Name");
        field_v_HP_No = (JRFillField)fm.get("v_HP_No");
        field_v_total_paidamt = (JRFillField)fm.get("v_total_paidamt");
        field_v_AccountNo = (JRFillField)fm.get("v_AccountNo");
        field_v_BankPhone = (JRFillField)fm.get("v_BankPhone");
        field_v_startamount = (JRFillField)fm.get("v_startamount");
        field_v_BranchName = (JRFillField)fm.get("v_BranchName");
        field_v_BankAddress = (JRFillField)fm.get("v_BankAddress");
        field_v_Payment_Term = (JRFillField)fm.get("v_Payment_Term");
    }


    /**
     *
     */
    void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
        variable_sub_dealer_id_COUNT = (JRFillVariable)vm.get("sub_dealer_id_COUNT");
        variable_Sub_total_COUNT = (JRFillVariable)vm.get("Sub_total_COUNT");
        variable_TODAY = (JRFillVariable)vm.get("TODAY");
        variable_FIN_DB_CONN = (JRFillVariable)vm.get("FIN_DB_CONN");
        variable_Br_name_check = (JRFillVariable)vm.get("Br_name_check");
        variable_Schm = (JRFillVariable)vm.get("Schm");
        variable_check_var = (JRFillVariable)vm.get("check_var");
        variable_sub_start_amt = (JRFillVariable)vm.get("sub_start_amt");
        variable_sub_tot_paidamt = (JRFillVariable)vm.get("sub_tot_paidamt");
        variable_Grand_Total_Start_Amount = (JRFillVariable)vm.get("Grand_Total_Start_Amount");
        variable_Grand_total_paid_amt = (JRFillVariable)vm.get("Grand_total_paid_amt");
    }


    /**
     *
     */
    Object evaluate(int id)
    {
        Object value = null;

        if (id == 0)
        {
            value = (java.sql.Connection)(null);
        }
        else if (id == 1)
        {
            value = (java.lang.String)("../images");
        }
        else if (id == 2)
        {
            value = (java.lang.String)("../jrxml");
        }
        else if (id == 3)
        {
            value = (java.lang.String)("");
        }
        else if (id == 4)
        {
            value = (java.lang.String)("");
        }
        else if (id == 5)
        {
            value = (java.lang.String)("");
        }
        else if (id == 6)
        {
            value = (java.lang.String)("");
        }
        else if (id == 7)
        {
            value = (java.lang.String)("");
        }
        else if (id == 8)
        {
            value = (java.lang.String)("CUSTOM|FIN_HP_INSTALLMENT_LISTING.FIN_HP_INSTALLMENT_LISTING%3%CUSTOM::|where%vi_date%=%((java.lang.String)parameter_P_vi_date.getValue())%Parameter%Date::and%vi_loanType%=%((java.lang.String)parameter_P_vi_loanType.getValue())%Parameter%String::and%vi_SchemeType%=%((java.lang.String)parameter_P_vi_SchemeType.getValue())%Parameter%String::and%vi_SchemeCode%=%((java.lang.String)parameter_P_vi_SchemeCode.getValue())%Parameter%String::and%vi_branchId%=%((java.lang.String)parameter_P_vi_branchId.getValue())%Parameter%String::|INP_STR%1%java.lang.String%VARCHAR2::OUT_RETCODE%4%java.math.BigDecimal%NUMBER::OUT_REC%4%java.lang.String%VARCHAR2::|P_vi_date%java.sql.Timestamp%10%!NULL!%Date@DBQUERY%NONE%java.sql.Timestamp!@!DEFAULT!@!8!@!10%CONSTANT%N%N::P_vi_loanType%java.lang.String%100%!NULL!%Loan_Type@DBQUERY%NONE%java.lang.String!@!SET!@!0!@!100&!&OverDraft#@#StaffLoan#@#Hire Purchase#@#Demand Loan%CONSTANT%N%N::P_vi_SchemeType%java.lang.String%100%!NULL!%Scheme_Type@DBQUERY%PRODUCT!@!Schm_Type_List#@#N%java.lang.String!@!DEFAULT!@!0!@!100%CONSTANT%N%N::P_vi_SchemeCode%java.lang.String%100%!NULL!%Scheme_Code@DBQUERY%PRODUCT!@!HSRSCCOD#@#N%java.lang.String!@!DEFAULT!@!0!@!100%CONSTANT%N%N::P_vi_branchId%java.lang.String%100%!NULL!%Branch_Code@DBQUERY%PRODUCT!@!SolID_List#@#N%java.lang.String!@!DEFAULT!@!0!@!100%CONSTANT%N%N::|{call CUSTOM.FIN_HP_INSTALLMENT_LISTING.FIN_HP_INSTALLMENT_LISTING( ((java.lang.String)parameter_FIN_INP_STR.getValue())  , ((java.math.BigDecimal)parameter_FIN_OUT_RETCODE.getValue()) , ((java.lang.String)parameter_FIN_OUT_REC.getValue()) ) } |{call CUSTOM.FIN_HP_INSTALLMENT_LISTING.FIN_HP_INSTALLMENT_LISTING( ((java.lang.String)parameter_FIN_INP_STR.getValue())  , ((java.math.BigDecimal)parameter_FIN_OUT_RETCODE.getValue()) , ((java.lang.String)parameter_FIN_OUT_REC.getValue()) ) } |false");
        }
        else if (id == 9)
        {
            value = (java.lang.String)(((java.lang.String)parameter_P_vi_date.getValue()) + "!" +((java.lang.String)parameter_P_vi_loanType.getValue()) + "!" +((java.lang.String)parameter_P_vi_SchemeType.getValue()) + "!" +((java.lang.String)parameter_P_vi_SchemeCode.getValue()) + "!" +((java.lang.String)parameter_P_vi_branchId.getValue()));
        }
        else if (id == 10)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 11)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 12)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 13)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 14)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 15)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 16)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 17)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 18)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 19)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 20)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 21)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 22)
        {
            value = (java.util.Date)(DateUtil.today());
        }
        else if (id == 23)
        {
            value = (java.util.Date)(DateUtil.today());
        }
        else if (id == 24)
        {
            value = (java.sql.Connection)(null);
        }
        else if (id == 25)
        {
            value = (java.lang.String)(((java.lang.String)parameter_P_vi_branchId.getValue()) == "null" ?"HO" : ((java.lang.String)field_v_BranchName.getValue()));
        }
        else if (id == 26)
        {
            value = (java.lang.String)(((java.lang.String)parameter_P_vi_SchemeType.getValue())== "CAA" || ((java.lang.String)parameter_P_vi_SchemeCode.getValue())== "AGDOD" ? "OverDraft" :
(((java.lang.String)parameter_P_vi_SchemeType.getValue()) == "LAA"||((java.lang.String)parameter_P_vi_SchemeCode.getValue())== "AGDHP" ?"Hire Purchase" :
(((java.lang.String)parameter_P_vi_SchemeType.getValue())=="LAA" || ((java.lang.String)parameter_P_vi_SchemeCode.getValue())== "AGHP6"  ? "Hire Purchase":
(((java.lang.String)parameter_P_vi_SchemeType.getValue())=="LAA" || ((java.lang.String)parameter_P_vi_SchemeCode.getValue())== "AGDNL"  ? "Normal Loans":
(((java.lang.String)parameter_P_vi_SchemeType.getValue())=="LAA" || ((java.lang.String)parameter_P_vi_SchemeCode.getValue())== "AGSS1"  ? "Staff Loan":
( "Staff Loan"))))));
        }
        else if (id == 27)
        {
            value = (java.lang.String)(((java.lang.String)parameter_P_vi_loanType.getValue())!= ''? ((java.lang.String)parameter_P_vi_loanType.getValue()) :((java.lang.String)parameter_P_vi_SchemeCode.getValue()));
        }
        else if (id == 28)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_startamount.getValue()));
        }
        else if (id == 29)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_total_paidamt.getValue()));
        }
        else if (id == 30)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_startamount.getValue()));
        }
        else if (id == 31)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_total_paidamt.getValue()));
        }
        else if (id == 32)
        {
            value = (java.lang.Object)(((java.lang.String)field_v_dealerID.getValue()));
        }
        else if (id == 33)
        {
            value = (java.lang.Object)(((java.lang.String)field_v_dealerID.getValue()));
        }
        else if (id == 34)
        {
            value = (java.lang.String)(null);
        }
        else if (id == 35)
        {
            value = (java.lang.String)("Sub Total");
        }
        else if (id == 36)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_sub_start_amt.getValue()));
        }
        else if (id == 37)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_sub_tot_paidamt.getValue()));
        }
        else if (id == 38)
        {
            value = (java.lang.String)("");
        }
        else if (id == 39)
        {
            value = (java.lang.String)(((java.lang.String)field_v_BankPhone.getValue()));
        }
        else if (id == 40)
        {
            value = (java.lang.String)(((java.lang.String)field_v_BankFax.getValue()));
        }
        else if (id == 41)
        {
            value = (java.lang.String)(((java.lang.String)field_v_BankAddress.getValue()));
        }
        else if (id == 42)
        {
            value = (java.lang.String)(FinUtil.getImage(((java.lang.String)field_Project_Image_Name.getValue()), ((java.lang.String)parameter_FIN_IMG_PATH.getValue())));
        }
        else if (id == 43)
        {
            value = (java.lang.String)(((java.lang.String)field_Project_Bank_Name.getValue())+"(" +((java.lang.String)field_v_BranchName.getValue()) + ")");
        }
        else if (id == 44)
        {
            value = (java.lang.String)(((java.lang.String)parameter_P_vi_loanType.getValue()) == null ?(((java.lang.String)parameter_P_vi_SchemeCode.getValue())+" Installment Listing For the month of " 
+ ((java.lang.String)parameter_P_vi_date.getValue())):(((java.lang.String)parameter_P_vi_loanType.getValue())+" Installment Listing For the month of " 
+ ((java.lang.String)parameter_P_vi_date.getValue())));
        }
        else if (id == 45)
        {
            value = (java.util.Date)(((java.util.Date)variable_TODAY.getValue()));
        }
        else if (id == 46)
        {
            value = (java.lang.String)(null);
        }
        else if (id == 47)
        {
            value = (java.lang.String)(((java.lang.String)field_v_AccountNo.getValue()));
        }
        else if (id == 48)
        {
            value = (java.lang.String)(((java.lang.String)field_v_HP_No.getValue()));
        }
        else if (id == 49)
        {
            value = (java.lang.String)(((java.lang.String)field_v_Acc_Name.getValue()));
        }
        else if (id == 50)
        {
            value = (java.lang.String)(((java.lang.String)field_v_Payment_Term.getValue()));
        }
        else if (id == 51)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getValue()));
        }
        else if (id == 52)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_startamount.getValue()));
        }
        else if (id == 53)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_total_paidamt.getValue()));
        }
        else if (id == 54)
        {
            value = (java.lang.String)(((java.lang.String)field_v_dealerID.getValue()));
        }
        else if (id == 55)
        {
            value = (java.lang.String)("Page No. : " + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
        }
        else if (id == 56)
        {
            value = (java.lang.String)("Total (" +((java.lang.Integer)variable_REPORT_COUNT.getValue())+ ") Record Listed.");
        }
        else if (id == 57)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Grand_total_paid_amt.getValue()));
        }
        else if (id == 58)
        {
            value = (java.lang.String)("");
        }
        else if (id == 59)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Grand_Total_Start_Amount.getValue()));
        }

        return value;
    }


    /**
     *
     */
    Object evaluateOld(int id)
    {
        Object value = null;

        if (id == 0)
        {
            value = (java.sql.Connection)(null);
        }
        else if (id == 1)
        {
            value = (java.lang.String)("../images");
        }
        else if (id == 2)
        {
            value = (java.lang.String)("../jrxml");
        }
        else if (id == 3)
        {
            value = (java.lang.String)("");
        }
        else if (id == 4)
        {
            value = (java.lang.String)("");
        }
        else if (id == 5)
        {
            value = (java.lang.String)("");
        }
        else if (id == 6)
        {
            value = (java.lang.String)("");
        }
        else if (id == 7)
        {
            value = (java.lang.String)("");
        }
        else if (id == 8)
        {
            value = (java.lang.String)("CUSTOM|FIN_HP_INSTALLMENT_LISTING.FIN_HP_INSTALLMENT_LISTING%3%CUSTOM::|where%vi_date%=%((java.lang.String)parameter_P_vi_date.getValue())%Parameter%Date::and%vi_loanType%=%((java.lang.String)parameter_P_vi_loanType.getValue())%Parameter%String::and%vi_SchemeType%=%((java.lang.String)parameter_P_vi_SchemeType.getValue())%Parameter%String::and%vi_SchemeCode%=%((java.lang.String)parameter_P_vi_SchemeCode.getValue())%Parameter%String::and%vi_branchId%=%((java.lang.String)parameter_P_vi_branchId.getValue())%Parameter%String::|INP_STR%1%java.lang.String%VARCHAR2::OUT_RETCODE%4%java.math.BigDecimal%NUMBER::OUT_REC%4%java.lang.String%VARCHAR2::|P_vi_date%java.sql.Timestamp%10%!NULL!%Date@DBQUERY%NONE%java.sql.Timestamp!@!DEFAULT!@!8!@!10%CONSTANT%N%N::P_vi_loanType%java.lang.String%100%!NULL!%Loan_Type@DBQUERY%NONE%java.lang.String!@!SET!@!0!@!100&!&OverDraft#@#StaffLoan#@#Hire Purchase#@#Demand Loan%CONSTANT%N%N::P_vi_SchemeType%java.lang.String%100%!NULL!%Scheme_Type@DBQUERY%PRODUCT!@!Schm_Type_List#@#N%java.lang.String!@!DEFAULT!@!0!@!100%CONSTANT%N%N::P_vi_SchemeCode%java.lang.String%100%!NULL!%Scheme_Code@DBQUERY%PRODUCT!@!HSRSCCOD#@#N%java.lang.String!@!DEFAULT!@!0!@!100%CONSTANT%N%N::P_vi_branchId%java.lang.String%100%!NULL!%Branch_Code@DBQUERY%PRODUCT!@!SolID_List#@#N%java.lang.String!@!DEFAULT!@!0!@!100%CONSTANT%N%N::|{call CUSTOM.FIN_HP_INSTALLMENT_LISTING.FIN_HP_INSTALLMENT_LISTING( ((java.lang.String)parameter_FIN_INP_STR.getValue())  , ((java.math.BigDecimal)parameter_FIN_OUT_RETCODE.getValue()) , ((java.lang.String)parameter_FIN_OUT_REC.getValue()) ) } |{call CUSTOM.FIN_HP_INSTALLMENT_LISTING.FIN_HP_INSTALLMENT_LISTING( ((java.lang.String)parameter_FIN_INP_STR.getValue())  , ((java.math.BigDecimal)parameter_FIN_OUT_RETCODE.getValue()) , ((java.lang.String)parameter_FIN_OUT_REC.getValue()) ) } |false");
        }
        else if (id == 9)
        {
            value = (java.lang.String)(((java.lang.String)parameter_P_vi_date.getValue()) + "!" +((java.lang.String)parameter_P_vi_loanType.getValue()) + "!" +((java.lang.String)parameter_P_vi_SchemeType.getValue()) + "!" +((java.lang.String)parameter_P_vi_SchemeCode.getValue()) + "!" +((java.lang.String)parameter_P_vi_branchId.getValue()));
        }
        else if (id == 10)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 11)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 12)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 13)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 14)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 15)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 16)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 17)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 18)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 19)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 20)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 21)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 22)
        {
            value = (java.util.Date)(DateUtil.today());
        }
        else if (id == 23)
        {
            value = (java.util.Date)(DateUtil.today());
        }
        else if (id == 24)
        {
            value = (java.sql.Connection)(null);
        }
        else if (id == 25)
        {
            value = (java.lang.String)(((java.lang.String)parameter_P_vi_branchId.getValue()) == "null" ?"HO" : ((java.lang.String)field_v_BranchName.getOldValue()));
        }
        else if (id == 26)
        {
            value = (java.lang.String)(((java.lang.String)parameter_P_vi_SchemeType.getValue())== "CAA" || ((java.lang.String)parameter_P_vi_SchemeCode.getValue())== "AGDOD" ? "OverDraft" :
(((java.lang.String)parameter_P_vi_SchemeType.getValue()) == "LAA"||((java.lang.String)parameter_P_vi_SchemeCode.getValue())== "AGDHP" ?"Hire Purchase" :
(((java.lang.String)parameter_P_vi_SchemeType.getValue())=="LAA" || ((java.lang.String)parameter_P_vi_SchemeCode.getValue())== "AGHP6"  ? "Hire Purchase":
(((java.lang.String)parameter_P_vi_SchemeType.getValue())=="LAA" || ((java.lang.String)parameter_P_vi_SchemeCode.getValue())== "AGDNL"  ? "Normal Loans":
(((java.lang.String)parameter_P_vi_SchemeType.getValue())=="LAA" || ((java.lang.String)parameter_P_vi_SchemeCode.getValue())== "AGSS1"  ? "Staff Loan":
( "Staff Loan"))))));
        }
        else if (id == 27)
        {
            value = (java.lang.String)(((java.lang.String)parameter_P_vi_loanType.getValue())!= ''? ((java.lang.String)parameter_P_vi_loanType.getValue()) :((java.lang.String)parameter_P_vi_SchemeCode.getValue()));
        }
        else if (id == 28)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_startamount.getOldValue()));
        }
        else if (id == 29)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_total_paidamt.getOldValue()));
        }
        else if (id == 30)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_startamount.getOldValue()));
        }
        else if (id == 31)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_total_paidamt.getOldValue()));
        }
        else if (id == 32)
        {
            value = (java.lang.Object)(((java.lang.String)field_v_dealerID.getOldValue()));
        }
        else if (id == 33)
        {
            value = (java.lang.Object)(((java.lang.String)field_v_dealerID.getOldValue()));
        }
        else if (id == 34)
        {
            value = (java.lang.String)(null);
        }
        else if (id == 35)
        {
            value = (java.lang.String)("Sub Total");
        }
        else if (id == 36)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_sub_start_amt.getOldValue()));
        }
        else if (id == 37)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_sub_tot_paidamt.getOldValue()));
        }
        else if (id == 38)
        {
            value = (java.lang.String)("");
        }
        else if (id == 39)
        {
            value = (java.lang.String)(((java.lang.String)field_v_BankPhone.getOldValue()));
        }
        else if (id == 40)
        {
            value = (java.lang.String)(((java.lang.String)field_v_BankFax.getOldValue()));
        }
        else if (id == 41)
        {
            value = (java.lang.String)(((java.lang.String)field_v_BankAddress.getOldValue()));
        }
        else if (id == 42)
        {
            value = (java.lang.String)(FinUtil.getImage(((java.lang.String)field_Project_Image_Name.getOldValue()), ((java.lang.String)parameter_FIN_IMG_PATH.getValue())));
        }
        else if (id == 43)
        {
            value = (java.lang.String)(((java.lang.String)field_Project_Bank_Name.getOldValue())+"(" +((java.lang.String)field_v_BranchName.getOldValue()) + ")");
        }
        else if (id == 44)
        {
            value = (java.lang.String)(((java.lang.String)parameter_P_vi_loanType.getValue()) == null ?(((java.lang.String)parameter_P_vi_SchemeCode.getValue())+" Installment Listing For the month of " 
+ ((java.lang.String)parameter_P_vi_date.getValue())):(((java.lang.String)parameter_P_vi_loanType.getValue())+" Installment Listing For the month of " 
+ ((java.lang.String)parameter_P_vi_date.getValue())));
        }
        else if (id == 45)
        {
            value = (java.util.Date)(((java.util.Date)variable_TODAY.getOldValue()));
        }
        else if (id == 46)
        {
            value = (java.lang.String)(null);
        }
        else if (id == 47)
        {
            value = (java.lang.String)(((java.lang.String)field_v_AccountNo.getOldValue()));
        }
        else if (id == 48)
        {
            value = (java.lang.String)(((java.lang.String)field_v_HP_No.getOldValue()));
        }
        else if (id == 49)
        {
            value = (java.lang.String)(((java.lang.String)field_v_Acc_Name.getOldValue()));
        }
        else if (id == 50)
        {
            value = (java.lang.String)(((java.lang.String)field_v_Payment_Term.getOldValue()));
        }
        else if (id == 51)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getOldValue()));
        }
        else if (id == 52)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_startamount.getOldValue()));
        }
        else if (id == 53)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_total_paidamt.getOldValue()));
        }
        else if (id == 54)
        {
            value = (java.lang.String)(((java.lang.String)field_v_dealerID.getOldValue()));
        }
        else if (id == 55)
        {
            value = (java.lang.String)("Page No. : " + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
        }
        else if (id == 56)
        {
            value = (java.lang.String)("Total (" +((java.lang.Integer)variable_REPORT_COUNT.getOldValue())+ ") Record Listed.");
        }
        else if (id == 57)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Grand_total_paid_amt.getOldValue()));
        }
        else if (id == 58)
        {
            value = (java.lang.String)("");
        }
        else if (id == 59)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Grand_Total_Start_Amount.getOldValue()));
        }

        return value;
    }


    /**
     *
     */
    Object evaluateEstimated(int id)
    {
        Object value = null;

        if (id == 0)
        {
            value = (java.sql.Connection)(null);
        }
        else if (id == 1)
        {
            value = (java.lang.String)("../images");
        }
        else if (id == 2)
        {
            value = (java.lang.String)("../jrxml");
        }
        else if (id == 3)
        {
            value = (java.lang.String)("");
        }
        else if (id == 4)
        {
            value = (java.lang.String)("");
        }
        else if (id == 5)
        {
            value = (java.lang.String)("");
        }
        else if (id == 6)
        {
            value = (java.lang.String)("");
        }
        else if (id == 7)
        {
            value = (java.lang.String)("");
        }
        else if (id == 8)
        {
            value = (java.lang.String)("CUSTOM|FIN_HP_INSTALLMENT_LISTING.FIN_HP_INSTALLMENT_LISTING%3%CUSTOM::|where%vi_date%=%((java.lang.String)parameter_P_vi_date.getValue())%Parameter%Date::and%vi_loanType%=%((java.lang.String)parameter_P_vi_loanType.getValue())%Parameter%String::and%vi_SchemeType%=%((java.lang.String)parameter_P_vi_SchemeType.getValue())%Parameter%String::and%vi_SchemeCode%=%((java.lang.String)parameter_P_vi_SchemeCode.getValue())%Parameter%String::and%vi_branchId%=%((java.lang.String)parameter_P_vi_branchId.getValue())%Parameter%String::|INP_STR%1%java.lang.String%VARCHAR2::OUT_RETCODE%4%java.math.BigDecimal%NUMBER::OUT_REC%4%java.lang.String%VARCHAR2::|P_vi_date%java.sql.Timestamp%10%!NULL!%Date@DBQUERY%NONE%java.sql.Timestamp!@!DEFAULT!@!8!@!10%CONSTANT%N%N::P_vi_loanType%java.lang.String%100%!NULL!%Loan_Type@DBQUERY%NONE%java.lang.String!@!SET!@!0!@!100&!&OverDraft#@#StaffLoan#@#Hire Purchase#@#Demand Loan%CONSTANT%N%N::P_vi_SchemeType%java.lang.String%100%!NULL!%Scheme_Type@DBQUERY%PRODUCT!@!Schm_Type_List#@#N%java.lang.String!@!DEFAULT!@!0!@!100%CONSTANT%N%N::P_vi_SchemeCode%java.lang.String%100%!NULL!%Scheme_Code@DBQUERY%PRODUCT!@!HSRSCCOD#@#N%java.lang.String!@!DEFAULT!@!0!@!100%CONSTANT%N%N::P_vi_branchId%java.lang.String%100%!NULL!%Branch_Code@DBQUERY%PRODUCT!@!SolID_List#@#N%java.lang.String!@!DEFAULT!@!0!@!100%CONSTANT%N%N::|{call CUSTOM.FIN_HP_INSTALLMENT_LISTING.FIN_HP_INSTALLMENT_LISTING( ((java.lang.String)parameter_FIN_INP_STR.getValue())  , ((java.math.BigDecimal)parameter_FIN_OUT_RETCODE.getValue()) , ((java.lang.String)parameter_FIN_OUT_REC.getValue()) ) } |{call CUSTOM.FIN_HP_INSTALLMENT_LISTING.FIN_HP_INSTALLMENT_LISTING( ((java.lang.String)parameter_FIN_INP_STR.getValue())  , ((java.math.BigDecimal)parameter_FIN_OUT_RETCODE.getValue()) , ((java.lang.String)parameter_FIN_OUT_REC.getValue()) ) } |false");
        }
        else if (id == 9)
        {
            value = (java.lang.String)(((java.lang.String)parameter_P_vi_date.getValue()) + "!" +((java.lang.String)parameter_P_vi_loanType.getValue()) + "!" +((java.lang.String)parameter_P_vi_SchemeType.getValue()) + "!" +((java.lang.String)parameter_P_vi_SchemeCode.getValue()) + "!" +((java.lang.String)parameter_P_vi_branchId.getValue()));
        }
        else if (id == 10)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 11)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 12)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 13)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 14)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 15)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 16)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 17)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 18)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 19)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 20)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 21)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 22)
        {
            value = (java.util.Date)(DateUtil.today());
        }
        else if (id == 23)
        {
            value = (java.util.Date)(DateUtil.today());
        }
        else if (id == 24)
        {
            value = (java.sql.Connection)(null);
        }
        else if (id == 25)
        {
            value = (java.lang.String)(((java.lang.String)parameter_P_vi_branchId.getValue()) == "null" ?"HO" : ((java.lang.String)field_v_BranchName.getValue()));
        }
        else if (id == 26)
        {
            value = (java.lang.String)(((java.lang.String)parameter_P_vi_SchemeType.getValue())== "CAA" || ((java.lang.String)parameter_P_vi_SchemeCode.getValue())== "AGDOD" ? "OverDraft" :
(((java.lang.String)parameter_P_vi_SchemeType.getValue()) == "LAA"||((java.lang.String)parameter_P_vi_SchemeCode.getValue())== "AGDHP" ?"Hire Purchase" :
(((java.lang.String)parameter_P_vi_SchemeType.getValue())=="LAA" || ((java.lang.String)parameter_P_vi_SchemeCode.getValue())== "AGHP6"  ? "Hire Purchase":
(((java.lang.String)parameter_P_vi_SchemeType.getValue())=="LAA" || ((java.lang.String)parameter_P_vi_SchemeCode.getValue())== "AGDNL"  ? "Normal Loans":
(((java.lang.String)parameter_P_vi_SchemeType.getValue())=="LAA" || ((java.lang.String)parameter_P_vi_SchemeCode.getValue())== "AGSS1"  ? "Staff Loan":
( "Staff Loan"))))));
        }
        else if (id == 27)
        {
            value = (java.lang.String)(((java.lang.String)parameter_P_vi_loanType.getValue())!= ''? ((java.lang.String)parameter_P_vi_loanType.getValue()) :((java.lang.String)parameter_P_vi_SchemeCode.getValue()));
        }
        else if (id == 28)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_startamount.getValue()));
        }
        else if (id == 29)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_total_paidamt.getValue()));
        }
        else if (id == 30)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_startamount.getValue()));
        }
        else if (id == 31)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_total_paidamt.getValue()));
        }
        else if (id == 32)
        {
            value = (java.lang.Object)(((java.lang.String)field_v_dealerID.getValue()));
        }
        else if (id == 33)
        {
            value = (java.lang.Object)(((java.lang.String)field_v_dealerID.getValue()));
        }
        else if (id == 34)
        {
            value = (java.lang.String)(null);
        }
        else if (id == 35)
        {
            value = (java.lang.String)("Sub Total");
        }
        else if (id == 36)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_sub_start_amt.getEstimatedValue()));
        }
        else if (id == 37)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_sub_tot_paidamt.getEstimatedValue()));
        }
        else if (id == 38)
        {
            value = (java.lang.String)("");
        }
        else if (id == 39)
        {
            value = (java.lang.String)(((java.lang.String)field_v_BankPhone.getValue()));
        }
        else if (id == 40)
        {
            value = (java.lang.String)(((java.lang.String)field_v_BankFax.getValue()));
        }
        else if (id == 41)
        {
            value = (java.lang.String)(((java.lang.String)field_v_BankAddress.getValue()));
        }
        else if (id == 42)
        {
            value = (java.lang.String)(FinUtil.getImage(((java.lang.String)field_Project_Image_Name.getValue()), ((java.lang.String)parameter_FIN_IMG_PATH.getValue())));
        }
        else if (id == 43)
        {
            value = (java.lang.String)(((java.lang.String)field_Project_Bank_Name.getValue())+"(" +((java.lang.String)field_v_BranchName.getValue()) + ")");
        }
        else if (id == 44)
        {
            value = (java.lang.String)(((java.lang.String)parameter_P_vi_loanType.getValue()) == null ?(((java.lang.String)parameter_P_vi_SchemeCode.getValue())+" Installment Listing For the month of " 
+ ((java.lang.String)parameter_P_vi_date.getValue())):(((java.lang.String)parameter_P_vi_loanType.getValue())+" Installment Listing For the month of " 
+ ((java.lang.String)parameter_P_vi_date.getValue())));
        }
        else if (id == 45)
        {
            value = (java.util.Date)(((java.util.Date)variable_TODAY.getEstimatedValue()));
        }
        else if (id == 46)
        {
            value = (java.lang.String)(null);
        }
        else if (id == 47)
        {
            value = (java.lang.String)(((java.lang.String)field_v_AccountNo.getValue()));
        }
        else if (id == 48)
        {
            value = (java.lang.String)(((java.lang.String)field_v_HP_No.getValue()));
        }
        else if (id == 49)
        {
            value = (java.lang.String)(((java.lang.String)field_v_Acc_Name.getValue()));
        }
        else if (id == 50)
        {
            value = (java.lang.String)(((java.lang.String)field_v_Payment_Term.getValue()));
        }
        else if (id == 51)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getEstimatedValue()));
        }
        else if (id == 52)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_startamount.getValue()));
        }
        else if (id == 53)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)field_v_total_paidamt.getValue()));
        }
        else if (id == 54)
        {
            value = (java.lang.String)(((java.lang.String)field_v_dealerID.getValue()));
        }
        else if (id == 55)
        {
            value = (java.lang.String)("Page No. : " + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
        }
        else if (id == 56)
        {
            value = (java.lang.String)("Total (" +((java.lang.Integer)variable_REPORT_COUNT.getEstimatedValue())+ ") Record Listed.");
        }
        else if (id == 57)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Grand_total_paid_amt.getEstimatedValue()));
        }
        else if (id == 58)
        {
            value = (java.lang.String)("");
        }
        else if (id == 59)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Grand_Total_Start_Amount.getEstimatedValue()));
        }

        return value;
    }


}
