/*
 * Generated by JasperReports - 12/20/17 9:34 AM
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import com.infy.finacle.finrpt.utils.*;
import net.sf.jasperreports.engine.*;
import com.infy.finacle.finrpt.ireport.*;
import java.util.*;
import com.infy.finacle.finrpt.*;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
class Day32Book32Without32Reversal_1513739079763_402889 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_REPORT_TIME_ZONE = null;
    private JRFillParameter parameter_TransactionDate = null;
    private JRFillParameter parameter_FIN_REPORT_TYPE = null;
    private JRFillParameter parameter_REPORT_FILE_RESOLVER = null;
    private JRFillParameter parameter_FIN_OUT_REC = null;
    private JRFillParameter parameter_BranchCode = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_FIN_REPORT_DESC = null;
    private JRFillParameter parameter_FIN_SER_FINQUERY = null;
    private JRFillParameter parameter_FINRPT_DEFAULT_FORMAT = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_REPORT_URL_HANDLER_FACTORY = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_ReversalType = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillParameter parameter_REPORT_TEMPLATES = null;
    private JRFillParameter parameter_FIN_DB_CONN = null;
    private JRFillParameter parameter_FIN_REPOS_FILE = null;
    private JRFillParameter parameter_FIN_OUT_RETCODE = null;
    private JRFillParameter parameter_Currency = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_FIN_REPORT_TO = null;
    private JRFillParameter parameter_FIN_BANKREPOS_PARAM = null;
    private JRFillParameter parameter_FIN_IMG_PATH = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_FIN_REPOS_LIST = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_FIN_SESSION_ID = null;
    private JRFillParameter parameter_FIN_TEMPLATE_PATH = null;
    private JRFillParameter parameter_FIN_APP_UTIL = null;
    private JRFillParameter parameter_REPORT_FORMAT_FACTORY = null;
    private JRFillParameter parameter_FIN_JASPER_PATH = null;
    private JRFillParameter parameter_FIN_INP_STR = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillField field_v_BankFax = null;
    private JRFillField field_Amount = null;
    private JRFillField field_Description = null;
    private JRFillField field_Project_Bank_Name = null;
    private JRFillField field_AccountNumber = null;
    private JRFillField field_Project_Image_Name = null;
    private JRFillField field_Account_Type = null;
    private JRFillField field_GLSH = null;
    private JRFillField field_Part_Tran_Type = null;
    private JRFillField field_Tran_Type = null;
    private JRFillField field_Init_Bank = null;
    private JRFillField field_v_BankPhone = null;
    private JRFillField field_v_BranchName = null;
    private JRFillField field_v_BankAddress = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_GLSH_COUNT = null;
    private JRFillVariable variable_FIN_REPOSITORY = null;
    private JRFillVariable variable_TODAY = null;
    private JRFillVariable variable_FIN_DB_CONN = null;
    private JRFillVariable variable_D_Cash = null;
    private JRFillVariable variable_D_Transfer = null;
    private JRFillVariable variable_D_Clearing = null;
    private JRFillVariable variable_C_Cash = null;
    private JRFillVariable variable_C_Transfer = null;
    private JRFillVariable variable_C_Clearing = null;
    private JRFillVariable variable_Debit = null;
    private JRFillVariable variable_Credit = null;
    private JRFillVariable variable_D_CashTotal = null;
    private JRFillVariable variable_D_TransferTotal = null;
    private JRFillVariable variable_D_ClearingTotal = null;
    private JRFillVariable variable_DebitTotal = null;
    private JRFillVariable variable_C_CashTotal = null;
    private JRFillVariable variable_C_TransferTotal = null;
    private JRFillVariable variable_C_ClearingTotal = null;
    private JRFillVariable variable_CreditTotal = null;
    private JRFillVariable variable_D_Cash_GrandTotal = null;
    private JRFillVariable variable_D_Transfer_GrandTotal = null;
    private JRFillVariable variable_D_Clearing_GrandTotal = null;
    private JRFillVariable variable_Debit_GrandTotal = null;
    private JRFillVariable variable_C_Cash_GrandTotal = null;
    private JRFillVariable variable_C_Transfer_GrandTotal = null;
    private JRFillVariable variable_C_Clearing_GrandTotal = null;
    private JRFillVariable variable_Credit_GrandTotal = null;


    /**
     *
     */
    void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    void initParams(Map pm)
    {
        parameter_REPORT_TIME_ZONE = (JRFillParameter)pm.get("REPORT_TIME_ZONE");
        parameter_TransactionDate = (JRFillParameter)pm.get("TransactionDate");
        parameter_FIN_REPORT_TYPE = (JRFillParameter)pm.get("FIN_REPORT_TYPE");
        parameter_REPORT_FILE_RESOLVER = (JRFillParameter)pm.get("REPORT_FILE_RESOLVER");
        parameter_FIN_OUT_REC = (JRFillParameter)pm.get("FIN_OUT_REC");
        parameter_BranchCode = (JRFillParameter)pm.get("BranchCode");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_FIN_REPORT_DESC = (JRFillParameter)pm.get("FIN_REPORT_DESC");
        parameter_FIN_SER_FINQUERY = (JRFillParameter)pm.get("FIN_SER_FINQUERY");
        parameter_FINRPT_DEFAULT_FORMAT = (JRFillParameter)pm.get("FINRPT_DEFAULT_FORMAT");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_REPORT_URL_HANDLER_FACTORY = (JRFillParameter)pm.get("REPORT_URL_HANDLER_FACTORY");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_ReversalType = (JRFillParameter)pm.get("ReversalType");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
        parameter_REPORT_TEMPLATES = (JRFillParameter)pm.get("REPORT_TEMPLATES");
        parameter_FIN_DB_CONN = (JRFillParameter)pm.get("FIN_DB_CONN");
        parameter_FIN_REPOS_FILE = (JRFillParameter)pm.get("FIN_REPOS_FILE");
        parameter_FIN_OUT_RETCODE = (JRFillParameter)pm.get("FIN_OUT_RETCODE");
        parameter_Currency = (JRFillParameter)pm.get("Currency");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_FIN_REPORT_TO = (JRFillParameter)pm.get("FIN_REPORT_TO");
        parameter_FIN_BANKREPOS_PARAM = (JRFillParameter)pm.get("FIN_BANKREPOS_PARAM");
        parameter_FIN_IMG_PATH = (JRFillParameter)pm.get("FIN_IMG_PATH");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_FIN_REPOS_LIST = (JRFillParameter)pm.get("FIN_REPOS_LIST");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_FIN_SESSION_ID = (JRFillParameter)pm.get("FIN_SESSION_ID");
        parameter_FIN_TEMPLATE_PATH = (JRFillParameter)pm.get("FIN_TEMPLATE_PATH");
        parameter_FIN_APP_UTIL = (JRFillParameter)pm.get("FIN_APP_UTIL");
        parameter_REPORT_FORMAT_FACTORY = (JRFillParameter)pm.get("REPORT_FORMAT_FACTORY");
        parameter_FIN_JASPER_PATH = (JRFillParameter)pm.get("FIN_JASPER_PATH");
        parameter_FIN_INP_STR = (JRFillParameter)pm.get("FIN_INP_STR");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
    }


    /**
     *
     */
    void initFields(Map fm)
    {
        field_v_BankFax = (JRFillField)fm.get("v_BankFax");
        field_Amount = (JRFillField)fm.get("Amount");
        field_Description = (JRFillField)fm.get("Description");
        field_Project_Bank_Name = (JRFillField)fm.get("Project_Bank_Name");
        field_AccountNumber = (JRFillField)fm.get("AccountNumber");
        field_Project_Image_Name = (JRFillField)fm.get("Project_Image_Name");
        field_Account_Type = (JRFillField)fm.get("Account_Type");
        field_GLSH = (JRFillField)fm.get("GLSH");
        field_Part_Tran_Type = (JRFillField)fm.get("Part_Tran_Type");
        field_Tran_Type = (JRFillField)fm.get("Tran_Type");
        field_Init_Bank = (JRFillField)fm.get("Init_Bank");
        field_v_BankPhone = (JRFillField)fm.get("v_BankPhone");
        field_v_BranchName = (JRFillField)fm.get("v_BranchName");
        field_v_BankAddress = (JRFillField)fm.get("v_BankAddress");
    }


    /**
     *
     */
    void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
        variable_GLSH_COUNT = (JRFillVariable)vm.get("GLSH_COUNT");
        variable_FIN_REPOSITORY = (JRFillVariable)vm.get("FIN_REPOSITORY");
        variable_TODAY = (JRFillVariable)vm.get("TODAY");
        variable_FIN_DB_CONN = (JRFillVariable)vm.get("FIN_DB_CONN");
        variable_D_Cash = (JRFillVariable)vm.get("D_Cash");
        variable_D_Transfer = (JRFillVariable)vm.get("D_Transfer");
        variable_D_Clearing = (JRFillVariable)vm.get("D_Clearing");
        variable_C_Cash = (JRFillVariable)vm.get("C_Cash");
        variable_C_Transfer = (JRFillVariable)vm.get("C_Transfer");
        variable_C_Clearing = (JRFillVariable)vm.get("C_Clearing");
        variable_Debit = (JRFillVariable)vm.get("Debit");
        variable_Credit = (JRFillVariable)vm.get("Credit");
        variable_D_CashTotal = (JRFillVariable)vm.get("D_CashTotal");
        variable_D_TransferTotal = (JRFillVariable)vm.get("D_TransferTotal");
        variable_D_ClearingTotal = (JRFillVariable)vm.get("D_ClearingTotal");
        variable_DebitTotal = (JRFillVariable)vm.get("DebitTotal");
        variable_C_CashTotal = (JRFillVariable)vm.get("C_CashTotal");
        variable_C_TransferTotal = (JRFillVariable)vm.get("C_TransferTotal");
        variable_C_ClearingTotal = (JRFillVariable)vm.get("C_ClearingTotal");
        variable_CreditTotal = (JRFillVariable)vm.get("CreditTotal");
        variable_D_Cash_GrandTotal = (JRFillVariable)vm.get("D_Cash_GrandTotal");
        variable_D_Transfer_GrandTotal = (JRFillVariable)vm.get("D_Transfer_GrandTotal");
        variable_D_Clearing_GrandTotal = (JRFillVariable)vm.get("D_Clearing_GrandTotal");
        variable_Debit_GrandTotal = (JRFillVariable)vm.get("Debit_GrandTotal");
        variable_C_Cash_GrandTotal = (JRFillVariable)vm.get("C_Cash_GrandTotal");
        variable_C_Transfer_GrandTotal = (JRFillVariable)vm.get("C_Transfer_GrandTotal");
        variable_C_Clearing_GrandTotal = (JRFillVariable)vm.get("C_Clearing_GrandTotal");
        variable_Credit_GrandTotal = (JRFillVariable)vm.get("Credit_GrandTotal");
    }


    /**
     *
     */
    Object evaluate(int id)
    {
        Object value = null;

        if (id == 0)
        {
            value = (java.lang.String)("");
        }
        else if (id == 1)
        {
            value = (java.sql.Connection)(null);
        }
        else if (id == 2)
        {
            value = (java.lang.String)("../images");
        }
        else if (id == 3)
        {
            value = (java.lang.String)("../jrxml");
        }
        else if (id == 4)
        {
            value = (java.lang.String)("");
        }
        else if (id == 5)
        {
            value = (java.lang.String)("");
        }
        else if (id == 6)
        {
            value = (java.lang.String)("");
        }
        else if (id == 7)
        {
            value = (java.lang.String)("");
        }
        else if (id == 8)
        {
            value = (java.lang.String)("CUSTOM|FIN_DAY_BOOK_DOMESTIC.FIN_DAY_BOOK_DOMESTIC%3%CUSTOM::|where%TransactionDate%=%((java.lang.String)parameter_TransactionDate.getValue())%Parameter%Date::and%Currency%=%((java.lang.String)parameter_Currency.getValue())%Parameter%String::and%ReversalType%=%((java.lang.String)parameter_ReversalType.getValue())%Parameter%String::and%BranchCode%=%((java.lang.String)parameter_BranchCode.getValue())%Parameter%String::|INP_STR%1%java.lang.String%VARCHAR2::OUT_RETCODE%4%java.math.BigDecimal%NUMBER::OUT_REC%4%java.lang.String%VARCHAR2::|TransactionDate%java.sql.Timestamp%10%!NULL!%Transaction Date@DBQUERY%NONE%java.sql.Timestamp!@!DEFAULT!@!8!@!10%CONSTANT%N%N::Currency%java.lang.String%100%!NULL!%Currency@DBQUERY%PRODUCT!@!HSRCTCCY#@#N%java.lang.String!@!DEFAULT!@!0!@!100%CONSTANT%N%N::ReversalType%java.lang.String%100%!NULL!%Reversal Type@DBQUERY%NONE%java.lang.String!@!SET!@!0!@!100&!&Without Reversal#@#With Reversal%CONSTANT%N%N::BranchCode%java.lang.String%100%!NULL!%Branch Code@DBQUERY%PRODUCT!@!SolID_List#@#N%java.lang.String!@!DEFAULT!@!0!@!100%CONSTANT%N%N::|{call CUSTOM.FIN_DAY_BOOK_DOMESTIC.FIN_DAY_BOOK_DOMESTIC( ((java.lang.String)parameter_FIN_INP_STR.getValue())  , ((java.math.BigDecimal)parameter_FIN_OUT_RETCODE.getValue()) , ((java.lang.String)parameter_FIN_OUT_REC.getValue()) ) } |{call CUSTOM.FIN_DAY_BOOK_DOMESTIC.FIN_DAY_BOOK_DOMESTIC( ((java.lang.String)parameter_FIN_INP_STR.getValue())  , ((java.math.BigDecimal)parameter_FIN_OUT_RETCODE.getValue()) , ((java.lang.String)parameter_FIN_OUT_REC.getValue()) ) } |false");
        }
        else if (id == 9)
        {
            value = (java.lang.String)(((java.lang.String)parameter_TransactionDate.getValue()) + "!" +((java.lang.String)parameter_Currency.getValue()) + "!" +((java.lang.String)parameter_ReversalType.getValue()) + "!" +((java.lang.String)parameter_BranchCode.getValue()));
        }
        else if (id == 10)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 11)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 12)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 13)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 14)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 15)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 16)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 17)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 18)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 19)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 20)
        {
            value = (java.util.Date)(DateUtil.today());
        }
        else if (id == 21)
        {
            value = (java.util.Date)(DateUtil.today());
        }
        else if (id == 22)
        {
            value = (java.sql.Connection)(null);
        }
        else if (id == 23)
        {
            value = (java.math.BigDecimal)((((java.lang.String)field_Init_Bank.getValue()).equals(((java.lang.String)parameter_BranchCode.getValue())) 
&& ((java.lang.String)field_Tran_Type.getValue()).equals( "C" ) 
&& ((java.lang.String)field_Part_Tran_Type.getValue()).equals( "D" )
) ? ((java.math.BigDecimal)field_Amount.getValue()) : 0.00);
        }
        else if (id == 24)
        {
            value = (java.math.BigDecimal)((((java.lang.String)field_Init_Bank.getValue())!= ((java.lang.String)parameter_BranchCode.getValue())  
&& ((java.lang.String)field_Tran_Type.getValue()).equals( "C" )
 &&   ((java.lang.String)field_Part_Tran_Type.getValue()).equals( "D" ) )
 || (((java.lang.String)field_Tran_Type.getValue()).equals( "T" ) && ((java.lang.String)field_Part_Tran_Type.getValue()).equals( "D" )) ? ((java.math.BigDecimal)field_Amount.getValue()) : 0.00);
        }
        else if (id == 25)
        {
            value = (java.math.BigDecimal)(((java.lang.String)field_Tran_Type.getValue()).equals( "L" ) && ((java.lang.String)field_Part_Tran_Type.getValue()).equals( "D" ) ? ((java.math.BigDecimal)field_Amount.getValue()) : 0.00);
        }
        else if (id == 26)
        {
            value = (java.math.BigDecimal)((((java.lang.String)field_Init_Bank.getValue()).equals(((java.lang.String)parameter_BranchCode.getValue()))
&&((java.lang.String)field_Tran_Type.getValue()).equals( "C" ) 
&& ((java.lang.String)field_Part_Tran_Type.getValue()).equals( "C" )
) ? ((java.math.BigDecimal)field_Amount.getValue()) : 0.00);
        }
        else if (id == 27)
        {
            value = (java.math.BigDecimal)(((((java.lang.String)field_Init_Bank.getValue())!=((java.lang.String)parameter_BranchCode.getValue()) && ((java.lang.String)field_Tran_Type.getValue()).equals( "C" ) && ((java.lang.String)field_Part_Tran_Type.getValue()).equals( "C" ))  || (((java.lang.String)field_Tran_Type.getValue()).equals( "T" ) && ((java.lang.String)field_Part_Tran_Type.getValue()).equals( "C" ))) ? ((java.math.BigDecimal)field_Amount.getValue()) : 0.00);
        }
        else if (id == 28)
        {
            value = (java.math.BigDecimal)(((java.lang.String)field_Tran_Type.getValue()).equals( "L" ) && ((java.lang.String)field_Part_Tran_Type.getValue()).equals( "C" ) ? ((java.math.BigDecimal)field_Amount.getValue()) : 0.00);
        }
        else if (id == 29)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_Cash.getValue())+((java.math.BigDecimal)variable_D_Transfer.getValue())+((java.math.BigDecimal)variable_D_Clearing.getValue()));
        }
        else if (id == 30)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_Cash.getValue())+((java.math.BigDecimal)variable_C_Transfer.getValue())+((java.math.BigDecimal)variable_C_Clearing.getValue()));
        }
        else if (id == 31)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_Cash.getValue()));
        }
        else if (id == 32)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_Transfer.getValue()));
        }
        else if (id == 33)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_Clearing.getValue()));
        }
        else if (id == 34)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Debit.getValue()));
        }
        else if (id == 35)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_Cash.getValue()));
        }
        else if (id == 36)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_Transfer.getValue()));
        }
        else if (id == 37)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_Clearing.getValue()));
        }
        else if (id == 38)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Credit.getValue()));
        }
        else if (id == 39)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_Cash.getValue()));
        }
        else if (id == 40)
        {
            value = (java.math.BigDecimal)(0);
        }
        else if (id == 41)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_Transfer.getValue()));
        }
        else if (id == 42)
        {
            value = (java.math.BigDecimal)(0);
        }
        else if (id == 43)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_Clearing.getValue()));
        }
        else if (id == 44)
        {
            value = (java.math.BigDecimal)(0);
        }
        else if (id == 45)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Debit.getValue()));
        }
        else if (id == 46)
        {
            value = (java.math.BigDecimal)(0);
        }
        else if (id == 47)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_Cash.getValue()));
        }
        else if (id == 48)
        {
            value = (java.math.BigDecimal)(0);
        }
        else if (id == 49)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_Transfer.getValue()));
        }
        else if (id == 50)
        {
            value = (java.math.BigDecimal)(0);
        }
        else if (id == 51)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_Clearing.getValue()));
        }
        else if (id == 52)
        {
            value = (java.math.BigDecimal)(0);
        }
        else if (id == 53)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Credit.getValue()));
        }
        else if (id == 54)
        {
            value = (java.math.BigDecimal)(0);
        }
        else if (id == 55)
        {
            value = (java.lang.Object)(((java.lang.String)field_GLSH.getValue()));
        }
        else if (id == 56)
        {
            value = (java.lang.String)("Sub Total");
        }
        else if (id == 57)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_CashTotal.getValue()));
        }
        else if (id == 58)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_TransferTotal.getValue()));
        }
        else if (id == 59)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_ClearingTotal.getValue()));
        }
        else if (id == 60)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_DebitTotal.getValue()));
        }
        else if (id == 61)
        {
            value = (java.lang.String)(" ");
        }
        else if (id == 62)
        {
            value = (java.lang.String)(" ");
        }
        else if (id == 63)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_CashTotal.getValue()));
        }
        else if (id == 64)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_TransferTotal.getValue()));
        }
        else if (id == 65)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_ClearingTotal.getValue()));
        }
        else if (id == 66)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_CreditTotal.getValue()));
        }
        else if (id == 67)
        {
            value = (java.lang.String)(((java.lang.String)field_Project_Bank_Name.getValue())+"(" + ((java.lang.String)field_v_BranchName.getValue()) + ")");
        }
        else if (id == 68)
        {
            value = (java.lang.String)(((java.lang.String)field_v_BankPhone.getValue()));
        }
        else if (id == 69)
        {
            value = (java.lang.String)(((java.lang.String)field_v_BankFax.getValue()));
        }
        else if (id == 70)
        {
            value = (java.lang.String)(((java.lang.String)field_v_BankAddress.getValue()));
        }
        else if (id == 71)
        {
            value = (java.lang.String)(FinUtil.getImage(((java.lang.String)field_Project_Image_Name.getValue()), ((java.lang.String)parameter_FIN_IMG_PATH.getValue())));
        }
        else if (id == 72)
        {
            value = (java.lang.String)("Day Book For Domestic "+((java.lang.String)parameter_ReversalType.getValue()) + " as at " + ((java.lang.String)parameter_TransactionDate.getValue()));
        }
        else if (id == 73)
        {
            value = (java.util.Date)(((java.util.Date)variable_TODAY.getValue()));
        }
        else if (id == 74)
        {
            value = (java.lang.String)(" Currency : "+((java.lang.String)parameter_Currency.getValue()).toUpperCase());
        }
        else if (id == 75)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getValue()));
        }
        else if (id == 76)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_Cash.getValue()));
        }
        else if (id == 77)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_Transfer.getValue()));
        }
        else if (id == 78)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Debit.getValue()));
        }
        else if (id == 79)
        {
            value = (java.lang.String)(((java.lang.String)field_AccountNumber.getValue()));
        }
        else if (id == 80)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_Clearing.getValue()));
        }
        else if (id == 81)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_Clearing.getValue()));
        }
        else if (id == 82)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_Cash.getValue()));
        }
        else if (id == 83)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_Transfer.getValue()));
        }
        else if (id == 84)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Credit.getValue()));
        }
        else if (id == 85)
        {
            value = (java.lang.String)(((java.lang.String)field_Description.getValue()));
        }
        else if (id == 86)
        {
            value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getValue()));
        }
        else if (id == 87)
        {
            value = (java.lang.String)("Total ( " + ((java.lang.Integer)variable_REPORT_COUNT.getValue())+ " ) Records Listed.");
        }
        else if (id == 88)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_Cash_GrandTotal.getValue()));
        }
        else if (id == 89)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_Transfer_GrandTotal.getValue()));
        }
        else if (id == 90)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_Clearing_GrandTotal.getValue()));
        }
        else if (id == 91)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Debit_GrandTotal.getValue()));
        }
        else if (id == 92)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_Transfer_GrandTotal.getValue()));
        }
        else if (id == 93)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_Clearing_GrandTotal.getValue()));
        }
        else if (id == 94)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Credit_GrandTotal.getValue()));
        }
        else if (id == 95)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_Cash_GrandTotal.getValue()));
        }

        return value;
    }


    /**
     *
     */
    Object evaluateOld(int id)
    {
        Object value = null;

        if (id == 0)
        {
            value = (java.lang.String)("");
        }
        else if (id == 1)
        {
            value = (java.sql.Connection)(null);
        }
        else if (id == 2)
        {
            value = (java.lang.String)("../images");
        }
        else if (id == 3)
        {
            value = (java.lang.String)("../jrxml");
        }
        else if (id == 4)
        {
            value = (java.lang.String)("");
        }
        else if (id == 5)
        {
            value = (java.lang.String)("");
        }
        else if (id == 6)
        {
            value = (java.lang.String)("");
        }
        else if (id == 7)
        {
            value = (java.lang.String)("");
        }
        else if (id == 8)
        {
            value = (java.lang.String)("CUSTOM|FIN_DAY_BOOK_DOMESTIC.FIN_DAY_BOOK_DOMESTIC%3%CUSTOM::|where%TransactionDate%=%((java.lang.String)parameter_TransactionDate.getValue())%Parameter%Date::and%Currency%=%((java.lang.String)parameter_Currency.getValue())%Parameter%String::and%ReversalType%=%((java.lang.String)parameter_ReversalType.getValue())%Parameter%String::and%BranchCode%=%((java.lang.String)parameter_BranchCode.getValue())%Parameter%String::|INP_STR%1%java.lang.String%VARCHAR2::OUT_RETCODE%4%java.math.BigDecimal%NUMBER::OUT_REC%4%java.lang.String%VARCHAR2::|TransactionDate%java.sql.Timestamp%10%!NULL!%Transaction Date@DBQUERY%NONE%java.sql.Timestamp!@!DEFAULT!@!8!@!10%CONSTANT%N%N::Currency%java.lang.String%100%!NULL!%Currency@DBQUERY%PRODUCT!@!HSRCTCCY#@#N%java.lang.String!@!DEFAULT!@!0!@!100%CONSTANT%N%N::ReversalType%java.lang.String%100%!NULL!%Reversal Type@DBQUERY%NONE%java.lang.String!@!SET!@!0!@!100&!&Without Reversal#@#With Reversal%CONSTANT%N%N::BranchCode%java.lang.String%100%!NULL!%Branch Code@DBQUERY%PRODUCT!@!SolID_List#@#N%java.lang.String!@!DEFAULT!@!0!@!100%CONSTANT%N%N::|{call CUSTOM.FIN_DAY_BOOK_DOMESTIC.FIN_DAY_BOOK_DOMESTIC( ((java.lang.String)parameter_FIN_INP_STR.getValue())  , ((java.math.BigDecimal)parameter_FIN_OUT_RETCODE.getValue()) , ((java.lang.String)parameter_FIN_OUT_REC.getValue()) ) } |{call CUSTOM.FIN_DAY_BOOK_DOMESTIC.FIN_DAY_BOOK_DOMESTIC( ((java.lang.String)parameter_FIN_INP_STR.getValue())  , ((java.math.BigDecimal)parameter_FIN_OUT_RETCODE.getValue()) , ((java.lang.String)parameter_FIN_OUT_REC.getValue()) ) } |false");
        }
        else if (id == 9)
        {
            value = (java.lang.String)(((java.lang.String)parameter_TransactionDate.getValue()) + "!" +((java.lang.String)parameter_Currency.getValue()) + "!" +((java.lang.String)parameter_ReversalType.getValue()) + "!" +((java.lang.String)parameter_BranchCode.getValue()));
        }
        else if (id == 10)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 11)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 12)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 13)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 14)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 15)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 16)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 17)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 18)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 19)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 20)
        {
            value = (java.util.Date)(DateUtil.today());
        }
        else if (id == 21)
        {
            value = (java.util.Date)(DateUtil.today());
        }
        else if (id == 22)
        {
            value = (java.sql.Connection)(null);
        }
        else if (id == 23)
        {
            value = (java.math.BigDecimal)((((java.lang.String)field_Init_Bank.getOldValue()).equals(((java.lang.String)parameter_BranchCode.getValue())) 
&& ((java.lang.String)field_Tran_Type.getOldValue()).equals( "C" ) 
&& ((java.lang.String)field_Part_Tran_Type.getOldValue()).equals( "D" )
) ? ((java.math.BigDecimal)field_Amount.getOldValue()) : 0.00);
        }
        else if (id == 24)
        {
            value = (java.math.BigDecimal)((((java.lang.String)field_Init_Bank.getOldValue())!= ((java.lang.String)parameter_BranchCode.getValue())  
&& ((java.lang.String)field_Tran_Type.getOldValue()).equals( "C" )
 &&   ((java.lang.String)field_Part_Tran_Type.getOldValue()).equals( "D" ) )
 || (((java.lang.String)field_Tran_Type.getOldValue()).equals( "T" ) && ((java.lang.String)field_Part_Tran_Type.getOldValue()).equals( "D" )) ? ((java.math.BigDecimal)field_Amount.getOldValue()) : 0.00);
        }
        else if (id == 25)
        {
            value = (java.math.BigDecimal)(((java.lang.String)field_Tran_Type.getOldValue()).equals( "L" ) && ((java.lang.String)field_Part_Tran_Type.getOldValue()).equals( "D" ) ? ((java.math.BigDecimal)field_Amount.getOldValue()) : 0.00);
        }
        else if (id == 26)
        {
            value = (java.math.BigDecimal)((((java.lang.String)field_Init_Bank.getOldValue()).equals(((java.lang.String)parameter_BranchCode.getValue()))
&&((java.lang.String)field_Tran_Type.getOldValue()).equals( "C" ) 
&& ((java.lang.String)field_Part_Tran_Type.getOldValue()).equals( "C" )
) ? ((java.math.BigDecimal)field_Amount.getOldValue()) : 0.00);
        }
        else if (id == 27)
        {
            value = (java.math.BigDecimal)(((((java.lang.String)field_Init_Bank.getOldValue())!=((java.lang.String)parameter_BranchCode.getValue()) && ((java.lang.String)field_Tran_Type.getOldValue()).equals( "C" ) && ((java.lang.String)field_Part_Tran_Type.getOldValue()).equals( "C" ))  || (((java.lang.String)field_Tran_Type.getOldValue()).equals( "T" ) && ((java.lang.String)field_Part_Tran_Type.getOldValue()).equals( "C" ))) ? ((java.math.BigDecimal)field_Amount.getOldValue()) : 0.00);
        }
        else if (id == 28)
        {
            value = (java.math.BigDecimal)(((java.lang.String)field_Tran_Type.getOldValue()).equals( "L" ) && ((java.lang.String)field_Part_Tran_Type.getOldValue()).equals( "C" ) ? ((java.math.BigDecimal)field_Amount.getOldValue()) : 0.00);
        }
        else if (id == 29)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_Cash.getOldValue())+((java.math.BigDecimal)variable_D_Transfer.getOldValue())+((java.math.BigDecimal)variable_D_Clearing.getOldValue()));
        }
        else if (id == 30)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_Cash.getOldValue())+((java.math.BigDecimal)variable_C_Transfer.getOldValue())+((java.math.BigDecimal)variable_C_Clearing.getOldValue()));
        }
        else if (id == 31)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_Cash.getOldValue()));
        }
        else if (id == 32)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_Transfer.getOldValue()));
        }
        else if (id == 33)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_Clearing.getOldValue()));
        }
        else if (id == 34)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Debit.getOldValue()));
        }
        else if (id == 35)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_Cash.getOldValue()));
        }
        else if (id == 36)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_Transfer.getOldValue()));
        }
        else if (id == 37)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_Clearing.getOldValue()));
        }
        else if (id == 38)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Credit.getOldValue()));
        }
        else if (id == 39)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_Cash.getOldValue()));
        }
        else if (id == 40)
        {
            value = (java.math.BigDecimal)(0);
        }
        else if (id == 41)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_Transfer.getOldValue()));
        }
        else if (id == 42)
        {
            value = (java.math.BigDecimal)(0);
        }
        else if (id == 43)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_Clearing.getOldValue()));
        }
        else if (id == 44)
        {
            value = (java.math.BigDecimal)(0);
        }
        else if (id == 45)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Debit.getOldValue()));
        }
        else if (id == 46)
        {
            value = (java.math.BigDecimal)(0);
        }
        else if (id == 47)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_Cash.getOldValue()));
        }
        else if (id == 48)
        {
            value = (java.math.BigDecimal)(0);
        }
        else if (id == 49)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_Transfer.getOldValue()));
        }
        else if (id == 50)
        {
            value = (java.math.BigDecimal)(0);
        }
        else if (id == 51)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_Clearing.getOldValue()));
        }
        else if (id == 52)
        {
            value = (java.math.BigDecimal)(0);
        }
        else if (id == 53)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Credit.getOldValue()));
        }
        else if (id == 54)
        {
            value = (java.math.BigDecimal)(0);
        }
        else if (id == 55)
        {
            value = (java.lang.Object)(((java.lang.String)field_GLSH.getOldValue()));
        }
        else if (id == 56)
        {
            value = (java.lang.String)("Sub Total");
        }
        else if (id == 57)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_CashTotal.getOldValue()));
        }
        else if (id == 58)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_TransferTotal.getOldValue()));
        }
        else if (id == 59)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_ClearingTotal.getOldValue()));
        }
        else if (id == 60)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_DebitTotal.getOldValue()));
        }
        else if (id == 61)
        {
            value = (java.lang.String)(" ");
        }
        else if (id == 62)
        {
            value = (java.lang.String)(" ");
        }
        else if (id == 63)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_CashTotal.getOldValue()));
        }
        else if (id == 64)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_TransferTotal.getOldValue()));
        }
        else if (id == 65)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_ClearingTotal.getOldValue()));
        }
        else if (id == 66)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_CreditTotal.getOldValue()));
        }
        else if (id == 67)
        {
            value = (java.lang.String)(((java.lang.String)field_Project_Bank_Name.getOldValue())+"(" + ((java.lang.String)field_v_BranchName.getOldValue()) + ")");
        }
        else if (id == 68)
        {
            value = (java.lang.String)(((java.lang.String)field_v_BankPhone.getOldValue()));
        }
        else if (id == 69)
        {
            value = (java.lang.String)(((java.lang.String)field_v_BankFax.getOldValue()));
        }
        else if (id == 70)
        {
            value = (java.lang.String)(((java.lang.String)field_v_BankAddress.getOldValue()));
        }
        else if (id == 71)
        {
            value = (java.lang.String)(FinUtil.getImage(((java.lang.String)field_Project_Image_Name.getOldValue()), ((java.lang.String)parameter_FIN_IMG_PATH.getValue())));
        }
        else if (id == 72)
        {
            value = (java.lang.String)("Day Book For Domestic "+((java.lang.String)parameter_ReversalType.getValue()) + " as at " + ((java.lang.String)parameter_TransactionDate.getValue()));
        }
        else if (id == 73)
        {
            value = (java.util.Date)(((java.util.Date)variable_TODAY.getOldValue()));
        }
        else if (id == 74)
        {
            value = (java.lang.String)(" Currency : "+((java.lang.String)parameter_Currency.getValue()).toUpperCase());
        }
        else if (id == 75)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getOldValue()));
        }
        else if (id == 76)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_Cash.getOldValue()));
        }
        else if (id == 77)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_Transfer.getOldValue()));
        }
        else if (id == 78)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Debit.getOldValue()));
        }
        else if (id == 79)
        {
            value = (java.lang.String)(((java.lang.String)field_AccountNumber.getOldValue()));
        }
        else if (id == 80)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_Clearing.getOldValue()));
        }
        else if (id == 81)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_Clearing.getOldValue()));
        }
        else if (id == 82)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_Cash.getOldValue()));
        }
        else if (id == 83)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_Transfer.getOldValue()));
        }
        else if (id == 84)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Credit.getOldValue()));
        }
        else if (id == 85)
        {
            value = (java.lang.String)(((java.lang.String)field_Description.getOldValue()));
        }
        else if (id == 86)
        {
            value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()));
        }
        else if (id == 87)
        {
            value = (java.lang.String)("Total ( " + ((java.lang.Integer)variable_REPORT_COUNT.getOldValue())+ " ) Records Listed.");
        }
        else if (id == 88)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_Cash_GrandTotal.getOldValue()));
        }
        else if (id == 89)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_Transfer_GrandTotal.getOldValue()));
        }
        else if (id == 90)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_Clearing_GrandTotal.getOldValue()));
        }
        else if (id == 91)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Debit_GrandTotal.getOldValue()));
        }
        else if (id == 92)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_Transfer_GrandTotal.getOldValue()));
        }
        else if (id == 93)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_Clearing_GrandTotal.getOldValue()));
        }
        else if (id == 94)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Credit_GrandTotal.getOldValue()));
        }
        else if (id == 95)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_Cash_GrandTotal.getOldValue()));
        }

        return value;
    }


    /**
     *
     */
    Object evaluateEstimated(int id)
    {
        Object value = null;

        if (id == 0)
        {
            value = (java.lang.String)("");
        }
        else if (id == 1)
        {
            value = (java.sql.Connection)(null);
        }
        else if (id == 2)
        {
            value = (java.lang.String)("../images");
        }
        else if (id == 3)
        {
            value = (java.lang.String)("../jrxml");
        }
        else if (id == 4)
        {
            value = (java.lang.String)("");
        }
        else if (id == 5)
        {
            value = (java.lang.String)("");
        }
        else if (id == 6)
        {
            value = (java.lang.String)("");
        }
        else if (id == 7)
        {
            value = (java.lang.String)("");
        }
        else if (id == 8)
        {
            value = (java.lang.String)("CUSTOM|FIN_DAY_BOOK_DOMESTIC.FIN_DAY_BOOK_DOMESTIC%3%CUSTOM::|where%TransactionDate%=%((java.lang.String)parameter_TransactionDate.getValue())%Parameter%Date::and%Currency%=%((java.lang.String)parameter_Currency.getValue())%Parameter%String::and%ReversalType%=%((java.lang.String)parameter_ReversalType.getValue())%Parameter%String::and%BranchCode%=%((java.lang.String)parameter_BranchCode.getValue())%Parameter%String::|INP_STR%1%java.lang.String%VARCHAR2::OUT_RETCODE%4%java.math.BigDecimal%NUMBER::OUT_REC%4%java.lang.String%VARCHAR2::|TransactionDate%java.sql.Timestamp%10%!NULL!%Transaction Date@DBQUERY%NONE%java.sql.Timestamp!@!DEFAULT!@!8!@!10%CONSTANT%N%N::Currency%java.lang.String%100%!NULL!%Currency@DBQUERY%PRODUCT!@!HSRCTCCY#@#N%java.lang.String!@!DEFAULT!@!0!@!100%CONSTANT%N%N::ReversalType%java.lang.String%100%!NULL!%Reversal Type@DBQUERY%NONE%java.lang.String!@!SET!@!0!@!100&!&Without Reversal#@#With Reversal%CONSTANT%N%N::BranchCode%java.lang.String%100%!NULL!%Branch Code@DBQUERY%PRODUCT!@!SolID_List#@#N%java.lang.String!@!DEFAULT!@!0!@!100%CONSTANT%N%N::|{call CUSTOM.FIN_DAY_BOOK_DOMESTIC.FIN_DAY_BOOK_DOMESTIC( ((java.lang.String)parameter_FIN_INP_STR.getValue())  , ((java.math.BigDecimal)parameter_FIN_OUT_RETCODE.getValue()) , ((java.lang.String)parameter_FIN_OUT_REC.getValue()) ) } |{call CUSTOM.FIN_DAY_BOOK_DOMESTIC.FIN_DAY_BOOK_DOMESTIC( ((java.lang.String)parameter_FIN_INP_STR.getValue())  , ((java.math.BigDecimal)parameter_FIN_OUT_RETCODE.getValue()) , ((java.lang.String)parameter_FIN_OUT_REC.getValue()) ) } |false");
        }
        else if (id == 9)
        {
            value = (java.lang.String)(((java.lang.String)parameter_TransactionDate.getValue()) + "!" +((java.lang.String)parameter_Currency.getValue()) + "!" +((java.lang.String)parameter_ReversalType.getValue()) + "!" +((java.lang.String)parameter_BranchCode.getValue()));
        }
        else if (id == 10)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 11)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 12)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 13)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 14)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 15)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 16)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 17)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 18)
        {
            value = (java.lang.Integer)(new Integer(1));
        }
        else if (id == 19)
        {
            value = (java.lang.Integer)(new Integer(0));
        }
        else if (id == 20)
        {
            value = (java.util.Date)(DateUtil.today());
        }
        else if (id == 21)
        {
            value = (java.util.Date)(DateUtil.today());
        }
        else if (id == 22)
        {
            value = (java.sql.Connection)(null);
        }
        else if (id == 23)
        {
            value = (java.math.BigDecimal)((((java.lang.String)field_Init_Bank.getValue()).equals(((java.lang.String)parameter_BranchCode.getValue())) 
&& ((java.lang.String)field_Tran_Type.getValue()).equals( "C" ) 
&& ((java.lang.String)field_Part_Tran_Type.getValue()).equals( "D" )
) ? ((java.math.BigDecimal)field_Amount.getValue()) : 0.00);
        }
        else if (id == 24)
        {
            value = (java.math.BigDecimal)((((java.lang.String)field_Init_Bank.getValue())!= ((java.lang.String)parameter_BranchCode.getValue())  
&& ((java.lang.String)field_Tran_Type.getValue()).equals( "C" )
 &&   ((java.lang.String)field_Part_Tran_Type.getValue()).equals( "D" ) )
 || (((java.lang.String)field_Tran_Type.getValue()).equals( "T" ) && ((java.lang.String)field_Part_Tran_Type.getValue()).equals( "D" )) ? ((java.math.BigDecimal)field_Amount.getValue()) : 0.00);
        }
        else if (id == 25)
        {
            value = (java.math.BigDecimal)(((java.lang.String)field_Tran_Type.getValue()).equals( "L" ) && ((java.lang.String)field_Part_Tran_Type.getValue()).equals( "D" ) ? ((java.math.BigDecimal)field_Amount.getValue()) : 0.00);
        }
        else if (id == 26)
        {
            value = (java.math.BigDecimal)((((java.lang.String)field_Init_Bank.getValue()).equals(((java.lang.String)parameter_BranchCode.getValue()))
&&((java.lang.String)field_Tran_Type.getValue()).equals( "C" ) 
&& ((java.lang.String)field_Part_Tran_Type.getValue()).equals( "C" )
) ? ((java.math.BigDecimal)field_Amount.getValue()) : 0.00);
        }
        else if (id == 27)
        {
            value = (java.math.BigDecimal)(((((java.lang.String)field_Init_Bank.getValue())!=((java.lang.String)parameter_BranchCode.getValue()) && ((java.lang.String)field_Tran_Type.getValue()).equals( "C" ) && ((java.lang.String)field_Part_Tran_Type.getValue()).equals( "C" ))  || (((java.lang.String)field_Tran_Type.getValue()).equals( "T" ) && ((java.lang.String)field_Part_Tran_Type.getValue()).equals( "C" ))) ? ((java.math.BigDecimal)field_Amount.getValue()) : 0.00);
        }
        else if (id == 28)
        {
            value = (java.math.BigDecimal)(((java.lang.String)field_Tran_Type.getValue()).equals( "L" ) && ((java.lang.String)field_Part_Tran_Type.getValue()).equals( "C" ) ? ((java.math.BigDecimal)field_Amount.getValue()) : 0.00);
        }
        else if (id == 29)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_Cash.getEstimatedValue())+((java.math.BigDecimal)variable_D_Transfer.getEstimatedValue())+((java.math.BigDecimal)variable_D_Clearing.getEstimatedValue()));
        }
        else if (id == 30)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_Cash.getEstimatedValue())+((java.math.BigDecimal)variable_C_Transfer.getEstimatedValue())+((java.math.BigDecimal)variable_C_Clearing.getEstimatedValue()));
        }
        else if (id == 31)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_Cash.getEstimatedValue()));
        }
        else if (id == 32)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_Transfer.getEstimatedValue()));
        }
        else if (id == 33)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_Clearing.getEstimatedValue()));
        }
        else if (id == 34)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Debit.getEstimatedValue()));
        }
        else if (id == 35)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_Cash.getEstimatedValue()));
        }
        else if (id == 36)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_Transfer.getEstimatedValue()));
        }
        else if (id == 37)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_Clearing.getEstimatedValue()));
        }
        else if (id == 38)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Credit.getEstimatedValue()));
        }
        else if (id == 39)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_Cash.getEstimatedValue()));
        }
        else if (id == 40)
        {
            value = (java.math.BigDecimal)(0);
        }
        else if (id == 41)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_Transfer.getEstimatedValue()));
        }
        else if (id == 42)
        {
            value = (java.math.BigDecimal)(0);
        }
        else if (id == 43)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_Clearing.getEstimatedValue()));
        }
        else if (id == 44)
        {
            value = (java.math.BigDecimal)(0);
        }
        else if (id == 45)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Debit.getEstimatedValue()));
        }
        else if (id == 46)
        {
            value = (java.math.BigDecimal)(0);
        }
        else if (id == 47)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_Cash.getEstimatedValue()));
        }
        else if (id == 48)
        {
            value = (java.math.BigDecimal)(0);
        }
        else if (id == 49)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_Transfer.getEstimatedValue()));
        }
        else if (id == 50)
        {
            value = (java.math.BigDecimal)(0);
        }
        else if (id == 51)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_Clearing.getEstimatedValue()));
        }
        else if (id == 52)
        {
            value = (java.math.BigDecimal)(0);
        }
        else if (id == 53)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Credit.getEstimatedValue()));
        }
        else if (id == 54)
        {
            value = (java.math.BigDecimal)(0);
        }
        else if (id == 55)
        {
            value = (java.lang.Object)(((java.lang.String)field_GLSH.getValue()));
        }
        else if (id == 56)
        {
            value = (java.lang.String)("Sub Total");
        }
        else if (id == 57)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_CashTotal.getEstimatedValue()));
        }
        else if (id == 58)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_TransferTotal.getEstimatedValue()));
        }
        else if (id == 59)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_ClearingTotal.getEstimatedValue()));
        }
        else if (id == 60)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_DebitTotal.getEstimatedValue()));
        }
        else if (id == 61)
        {
            value = (java.lang.String)(" ");
        }
        else if (id == 62)
        {
            value = (java.lang.String)(" ");
        }
        else if (id == 63)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_CashTotal.getEstimatedValue()));
        }
        else if (id == 64)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_TransferTotal.getEstimatedValue()));
        }
        else if (id == 65)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_ClearingTotal.getEstimatedValue()));
        }
        else if (id == 66)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_CreditTotal.getEstimatedValue()));
        }
        else if (id == 67)
        {
            value = (java.lang.String)(((java.lang.String)field_Project_Bank_Name.getValue())+"(" + ((java.lang.String)field_v_BranchName.getValue()) + ")");
        }
        else if (id == 68)
        {
            value = (java.lang.String)(((java.lang.String)field_v_BankPhone.getValue()));
        }
        else if (id == 69)
        {
            value = (java.lang.String)(((java.lang.String)field_v_BankFax.getValue()));
        }
        else if (id == 70)
        {
            value = (java.lang.String)(((java.lang.String)field_v_BankAddress.getValue()));
        }
        else if (id == 71)
        {
            value = (java.lang.String)(FinUtil.getImage(((java.lang.String)field_Project_Image_Name.getValue()), ((java.lang.String)parameter_FIN_IMG_PATH.getValue())));
        }
        else if (id == 72)
        {
            value = (java.lang.String)("Day Book For Domestic "+((java.lang.String)parameter_ReversalType.getValue()) + " as at " + ((java.lang.String)parameter_TransactionDate.getValue()));
        }
        else if (id == 73)
        {
            value = (java.util.Date)(((java.util.Date)variable_TODAY.getEstimatedValue()));
        }
        else if (id == 74)
        {
            value = (java.lang.String)(" Currency : "+((java.lang.String)parameter_Currency.getValue()).toUpperCase());
        }
        else if (id == 75)
        {
            value = (java.lang.String)(((java.lang.Integer)variable_REPORT_COUNT.getEstimatedValue()));
        }
        else if (id == 76)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_Cash.getEstimatedValue()));
        }
        else if (id == 77)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_Transfer.getEstimatedValue()));
        }
        else if (id == 78)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Debit.getEstimatedValue()));
        }
        else if (id == 79)
        {
            value = (java.lang.String)(((java.lang.String)field_AccountNumber.getValue()));
        }
        else if (id == 80)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_Clearing.getEstimatedValue()));
        }
        else if (id == 81)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_Clearing.getEstimatedValue()));
        }
        else if (id == 82)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_Cash.getEstimatedValue()));
        }
        else if (id == 83)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_Transfer.getEstimatedValue()));
        }
        else if (id == 84)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Credit.getEstimatedValue()));
        }
        else if (id == 85)
        {
            value = (java.lang.String)(((java.lang.String)field_Description.getValue()));
        }
        else if (id == 86)
        {
            value = (java.lang.Integer)(((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()));
        }
        else if (id == 87)
        {
            value = (java.lang.String)("Total ( " + ((java.lang.Integer)variable_REPORT_COUNT.getEstimatedValue())+ " ) Records Listed.");
        }
        else if (id == 88)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_Cash_GrandTotal.getEstimatedValue()));
        }
        else if (id == 89)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_Transfer_GrandTotal.getEstimatedValue()));
        }
        else if (id == 90)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_D_Clearing_GrandTotal.getEstimatedValue()));
        }
        else if (id == 91)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Debit_GrandTotal.getEstimatedValue()));
        }
        else if (id == 92)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_Transfer_GrandTotal.getEstimatedValue()));
        }
        else if (id == 93)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_Clearing_GrandTotal.getEstimatedValue()));
        }
        else if (id == 94)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_Credit_GrandTotal.getEstimatedValue()));
        }
        else if (id == 95)
        {
            value = (java.math.BigDecimal)(((java.math.BigDecimal)variable_C_Cash_GrandTotal.getEstimatedValue()));
        }

        return value;
    }


}
